// CHAWI 1 — Dictionnaire Chaoui (latin)
window.dicoChawi1 = {
    "À (lieu)":  "gher";       
"À (temps)":  "Al,Ar";
"À-côtés":"Tamawin ,Tighemrin";   
"À-côtés de l'histoire":  "Tamawin n umezruy";
"À-coups (par ~)":  "S-urjiji";
"À-coups; (sans ~)":"War-arjiji  Nk-arjiji";
"À-peu-près":"Amzun";
"A priori loc adv":"S azara";
"A tantôt ": "Al_adteqqel ,al ad teqqel tfuyt";    
"Abaissement": "Asider Asehwi";
"Abaisser": "Sider ,Sehwa";
"Abaisser ":"( s') Ader ,ttader, uder";
"Abat-jour": "Tillamba";
"Abâtardir":"Skebbel ,skebbal";
"Abats": "Igheddiden, tidewwar'in";
"Abandon": "Ajj'ay";  
"Abandonner ":"Jj' ,ttejj', jj'a, Llef,ttellef";
"Abaque ":"Tafelwit";      
"Abasourdir":"Smuz'ji,smuz'jay";
"Abattre (egorger un animal)":"ghr's";
"Abattre (un objet, un arbre)":"Sid'u ,sid'aw";
"Abatteur d'animaux,le boucher":"Abuci Agherras";
"Abatteur d'arbre , bucheron":" Azeddam";
"Abcès":"Tuksi";
"Abdomen": "Aaddis Ahbud' ";
"Abeille":"Tizizwit";
"Abeille (nom de l'espece)": "Tizizwa";
"Abêtir qqn": "Seghyel , seghyal"; 
"Abêtir s' ":"Seghyel iman nns";
"Abîme" :"Anu (Inan) ,Abtul (Ibtal)";
"Abîmer": "Rahad ,Tterhid";
"Ablution":"Asbagh wud'u";
"Ablutions (faire ses ~)": "sbegh  ud'u,sebbegh _ud'u";
"Aboiement":"Ashawhaw";   
"Abolition":"Isir";          
"Abonder":"A3errem";
"Abord (d’)":"S tizar  ,Di tazwara";
"Aborder Ami ":"ttami";        
"Aboutir":"Seghled' ,Sawed' ";   
"Aboyer":"Shawhew , shawhaw";     
"Abreuver":"Sured ,Sessew";
"Abréviation":"Tazegzilt";   
"Abri":"Tasghift,Taseddarit";
"Abricot":"Aber'ghugh";
"Abricotier":"Taber'ghught";
"Abricots sechés":"Afermas";
"Abricots verts":"Busemmum";
"Abriter s' " : "Sder";
"Absence":"Aze'rti, Iba ,ibaten";  
"Absent": "Amz'erti, Amabay";     
"Absenter (s’)":"Z'erta";
"Absinthe":"Izri";    
"Absorbant":"Az'emmay"; 
"Absorber":"Z'mi";
"Absoudre":"Sesuret";
"Abstenir (s’)":"Gguma,ttgguma,Uggel";
"Abstention ":"Aggumi,Aggal";
"Accélérateur":"Azerrab";
"Accélération":"Azrab";    
"Accélérer":"Zreb";
"Accent":"Aghdebbu";      
"Accentuer":"ghdebbu,tteghdebbu";      
"Acceptation":"Taz’ayett ,Asyah";   
"Accepter":"Z’ayet, Syeh";      
"Accès":"Adaf"; 
"Accommodation":"Ameckiked";     
"Accommoder":"Meckiked";
"Accompagnateur":"Amsegli";      
"Accompagnement":"Azday";     
"Accord":"Amtawi";  
"Accoster":"Ami , ttami";        
"Accoucher ":"Arew ,ttarew";
"Accouchement":"Araw";
"Accoupler":"Zdi ,ttezdi, zda";
"Accoutumer S' ":"Numm ,ttnumma";
"Accrocher":"Sillegh,sillagh";            
"Accroissement":"Aserni ,Asgyam";  
"Accroitre":"Serni,Sgyem ";
"Accroupir s’":"Ge3mez,ttge3maz,Sgummer";
"Accueil(-des invités)":"Asniju ,Asnuju,Asnubbeg ";
"Accueillir(- des invités)":"Snuju,Sniju ,snijaw";  
"Accumulation":"Acellif";      
"Accumuler ":"Layem Hawel Cellef";   
"Accusation ":"Tardayt";
"Accuser":"Rdu";
"Achat":"Asagh ,Asghay";
"Acheter":"Segh,ssagh, sgha";    
"Acheteur":"Amesghay,Amsagh";
"Achever ":"Mmir ,temmir,Semket,Sala";
"Acide":"Asemmum,Amaghus";
"Acidité":"Tamaghusit ,Tasmmumit";
"Acier":"Uzzal";
"Acquérir ":"Lummez’ ";     
"Acte théâtral":"Asekkir";
"Action":"Tagayt";
"Activité":"Armud ,irmad";      
"Actualité":"Tamirt";    
"Actuel":"Amiran";
"Actuellement":"Imira,Tura";   
"Addition":"Arnay,Aserni";
"Additionner":"Serni";
"Adhérent":"Ameltagh";
"Adhérer":"Ltegh";     
"Adhésion":"Altagh";
"Adieu":"Asifed’ ";           
"Adjoint":"Ammazul,immuzal";
"Admettre":"Sidemr";
"Administrateur":"Anedbal";
"Administratif":"Adeblan";
"Administration":"Tadbelt";
"Administrer":"Dbel";
"Admirable":"Anegraz";
"Admiration":"Agaraz";
"Admirer":"Grez";
"Admissible":"Amsidmer";
"Admission":"Asidmer";
"Adolescence":"Tanubi";
"Adolescent":"Anubi, inubiyen"; 
"Adolescente":"Tanubit,tinubiyin"; 
"Adopter":"Zdel";
"Adoption":"Azdal";         
"Adresse":"Taddrisa";
"Adulte":"Amagur";
"Adversaire":"Afna ,ifnayen";
"Aérer":"Sahhew";
"Aéroport":"Annar uferfer";
"Affaiblir (s-)":"Rhem ,rehhem,Nzef";
"Affaiblir (faire-)":"Serhem ,serham,Senzef";
"Affaiblissement":"Arham,Anzaf";
"Affaire":"Taghawsa ,Awez’lu ,iwez’la";      
"Affamé":"Amelluz' ,Imelliz’ ";
"Affectif":"Amurnan";
"Affichage":"Tanezla";
"Affirmatif":"Ilaw";
"Affirmation":"Tilawt";
"Affirmer":"Sentem";
"Affranchi":"Aderfi ,iderfan";
"Affranchir":"Sedref";      
"Affronter":"Sidmer,Sudem";
"Afin que":"Baca,Amma";
"Agacer":"Cettet";
"Âge":"Uta ,utawin,Awta";
"Âge(celui/ceux de son - )":"Uta nns ,Utawin nns";
"Agent":"Ameggi ,imegga";
"Agir (faire)":"Segg";
"Agitateur":"Asmessay";
"Agitation ":"Tasmessit";
"Agiter":"Smessay";
"Agneau":"Izmer ,izmaren, Anejj'umi";
"Agonie":"Aselghef";
"Agoniser":"Selghef";
"Agréable ":"Amagraz ,Iz’il"
}