window.dico2 = {

 "anabdou":"Été,ⴰⵏⴰⴱⴷⵓ ",
 "tissira":"Chaussures,ⵜⵉⵙⵉⵔⴰ",
 "takon":"Talon,ⵜⴰⴽⵓⵏ ",
 "tqacha":"Chaussettes,ⵜⵇⴰⵛⵔ",
 "sawar":"Pantalon,ⵙⴰⵡⴰⵔ",
 "kamisita":"Tee-shirt,ⴽⴰⵎⵉⵙⵉⵜⴰ ",
 "falda":"Jupe,ⴼⴰⵍⴷⴰ",
 "qandoura":"Robe,ⵇⴰⵏⴷⵓⵔⴰ ",
 "aqaftan":"Caftan,ⴰⵇⴰⴼⵟⴰⵏ",
 "palto":"Manteau,ⴱⴰⵍⵜⵓ ",
 "tachambouchte":"Foulard,ⵜⴰⵛⴰⵎⴱⵓⵛⵜ",
 "tsadhikh":"Je suis timide,ⵜⵙⴰⴷⵉⵅ ",
 "3esbekh":"Je suis en colère,ⵄⴰⵙⴱⵅ ",
 "fahekh":"Je suis heureux,ⴼⴰⵃⵅ",
 "hazenkh":"Je suis triste,ⵃⴰⵣⵏⵅ",
 "qendekh":"Je m'ennuie,ⵇⴰⵏⴷⵅ",
 "chahekh":"Je déteste,ⵛⴰⵃⴰⵅ",
 "t3jibay":"J'aime bien,ⵜⵄⵊⵉⴱⴰⵢ ",
 "takhsekh":"J'aime (amour),ⵜⴰⵅⵙⵅ",
 "tatokh":"J'oublie,ⵜⴰⵜⵓⵅ ",
 "tfakakh":"Je pense,ⵜⴼⴰⴽⴰⵅ",
 "fahmekh":"Je comprends,ⴼⴰⵀⵎⵅ ",
 "iqseh":"Dur,ⵉⵇⵙⵃ",
 "isher":"Facile,ⵉⵙⵀⵔ",
 "kif kif":"Pareil,ⴽⵉⴼ ⴽⵉⴼ ",
 "ma3lich":"Pas grave,ⵎⴰⵄⵍⵉⵛ ",
 "za3ma":"Genre,ⵣⴰⵄⵎⴰ ",
 "rchighed":"Papier,ⵔⵛⵉⵖⴹ ",
 "tawriqt":"Feuille,ⵜⴰⵡⵔⵉⵇⵜ",
 "tsa3at":"L'heure,ⵜⵙⴰⵄⴰⵜ",
 "tfawt":"Lumière,ⵜⴼⴰⵡⵜ",
 "tsadjest":"Sombre,ⵜⵙⴰⴶⵉⵙⵜ",
 "ichakrad":"Pieds de mouton,ⵉⵛⴰⴽⵔⴰⴷ ",
 "itaqsay":"J'ai mal,ⵉⵜⵇⵙⴰⵢ",
 "iteqsay rhar":"Je suis susceptible,ⵉⵜⵇⵙⴰⵢ ⵔⵃⴰⵔ ",
 "iteqsay or ino":"J'ai mal au cœur,ⵉⵜⵇⵙⴰⵢ ⵓⵔⵉⵏⵓ",
 "jahekh":"Je suis blessé,ⵊⴰⵃⴻⵅ ",
 "faqekh":"Je suis réveillé,ⴼⴰⵇⵅ ",
 "tsekh":"Je dors,ⵜⵙⴰⵅ ",
 "inza":"Nez,ⵉⵏⵣⴰ ",
 "amezzough":"Oreille,ⴰⵎⵥⵓⵖ",
 "aqemouch":"Bouche,ⴰⵇⵎⵓⵛ ",
 "aqyou3":"Crâne,ⴰⵇⵢⵓⵄ ",
 "azdjif":"Tête,ⴰⵣⴶⵉⴼ ",
 "adjen":"Cervelle,ⴰⴷⵊⵏ ",
 "tit":"Œil,ⵜⵉⵟ ",
 "tittawen":"Yeux,ⵜⵉⵟⴰⵡⵉⵏ",
 "udem":"Face/figure,ⵓⴷⴻⵎ",
 "aghoumboub":"Visage,ⴰⵖⵎⴱⵓⴱ",
 "a3ediss":"Ventre,ⴰⵄⴷⵉⵙ",
 "foud":"Genou,ⴼⵢⴷ",
 "ifadden":"Genoux,ⵉⴼⴰⴷⴷⴻⵏ",
 "bourourou":"Colon (intestin),ⴱⵓⵔⵓⵔⵓ ",
 "iref":"Cochon,ⵉⵔⴰⴼ ",
 "tafonasste":"Vache,ⵜⴰⴼⵓⵏⴰⵙⵜ",
 "aghyor":"Âne,ⴰⵖⵢⵓⵔ",
 "tyazite":"Poule,ⵜⵢⴰⵥⵉⵜ ",
 "yazid":"Coq,ⵢⴰⵥⵉⴹ",
 "aqenni":"Lapin,ⴰⵇⴻⵏⵏⵉ ",
 "ichfa":"Tortue,ⵉⵛⴼⴰ",
 "aghrar":"Escargot,ⴰⵖⵔⴰⵔ",
 "asrem":"Poisson,ⴰⵙⵔⵎ ",
 "aqzin":"Chien,ⴰⵇⵣⵉⵏ",
 "amchich":"Chat,ⴰⵎⵛⵉⵛ",
 "moch":"Chat,ⵎⵓⵛ",
 "ouchen":"Renard,ⵓⵛⴻⵏ",
 "boharo":"Lion,ⴱⵓⵀⴰⵔⵓ ",
 "zarafa":"Girafe,ⵣⴰⵔⴰⴼⴰ ",
 "lfil":"Éléphant,ⵍⴼⵉⵍ",
 "qaqra":"Grenouille,ⵇⴰⵇⵔⴰ",
 "reqfar":"Bouton (de chemise),ⵔⴻⵇⴼⴰⵔ",
 "ghayata":"Biscuit,ⵖⴰⵢⴰⵜⴰ",
 "inwajiwen":"Les invités,ⵉⵏⵡⴰⵊⵉⵡⵉⵏ",
 "agham":"Tiens,ⴰⵖⴰⵎ",
 "taff":"Tiens/prends,ⵜⴰⴼⴼ ",
 "fakka":"Penser,ⴼⴰⴽⴽⴰ ",
 "moun":"Accompagner,ⵎⵓⵏ",
 "smoun":"Rassembler,ⵙⵎⵓⵏ",
 "khza":"Regarder,ⵅⵣⴰ ",
 "ira":"Jouer,ⵉⵔⴰⵔ",
 "ech":"Manger,ⵉⵛ ",
 "zdawwa":"Critiquer,se moquer,ⵣⴷⴰⵡⵡⴰ",
 "jbed":"Tirer,ⵊⴱⴰⴷ ",
 "ksi":"Prendre,enlever,supprimer,ⴽⵙⵉ ",
 "chti":"Prendre,ⵛⵜⵉ",
 "harlch":"Être malade,ⵀⴰⵔⵍⵛ",
 "souw":"Boire,ⵙⵓ",
 "az":"Casser,taper,ⴰⵣ ",
 "iqqs":"Piquer,faire mal,ⵉⵇⵇⵙ ",
 "ga3d":"Monter,ⴳⴰⵄⴷ",
 "ari":"Monter,écrire,ⴰⵔⵉ",
 "safar":"Voyager,ⵙⴰⴼⴰⵔ",
 "sara":"Se promener,ⵙⴰⵔⴰ",
 "saqsi":"Demander,ⵙⴰⵇⵙⵉ ",
 "harq":"Avoir mal,ⵃⴰⵔⵇ",
 "adef":"Entrer,ⴰⴷⴼ ",
 "af":"Trouver,ⴰⴼ",
 "khes":"Vouloir,ⵅⴰⵙ ",
 "tekhs":"Aimer (amour),",
 "azou":"Chercher,vouloir,ⴰⵣⵢ",
 "merch":"Se marier,ⵎⴻⵔⵛ",
 "egg":"Faire,ⵉⴳⴳ ",
 "sqa":"Se taire,ⵙⵇⴰ ",
 "kar":"Se lever,ⴽⴰⵔ",
 "qar":"Raconter,dire,ⵇⴰⵔ",
 "ini":"Dire,ⵉⵏⵉ",
 "khdem":"Travailler,faire,ⵅⴷⵎ",
 "sessou":"Faire boire,arroser,ⵙⴻⵙⵓ",
 "saqar":"Fabriquer,ⵙⴰⵇⴰⵔ",
 "ndah":"Conduire,ⵏⴷⴰⵀ",
 "sigha":"Passer (donner),ⵙⵉⵖⴰ",
 "ouch":"Donner,ⵓⵛ",
 "quim":"Rester,manquer,s'asseoir,ⵇⵓⵉⵎ",
 "awid":"Apporter,ramener,ⴰⵡⵉⴷ",
 "ngh":"Tuer,ⵏⵏⵖ",
 "setch":"Nourrir,ⵙⴻⵜⵛ",
 "tou":"Oublier,ⵜⵓ",
 "qra":"Lire,ⵇⵔⴰ",
 "msagar":"Rencontrer,ⵎⵙⴰⴳⴰⵔ",
 "aqer":"Voler,ⴰⵇⴻⵔ",
 "ba3d":"Éloigner,ⴱⴰⵄⴷ",
 "r7em":"Reculer,ⵔⵃⵎ",
 "agwaj":"Éloigner,ⴰⴳⵡⴰⵊ",
 "hayad":"Reculer,ⵃⴰⵢⴰⴷ",
 "qaber":"Regarder,matter,rester planté,ⵇⴰⴱⵔ",
 "ghanij":"Chanter,ⵖⴰⵏⵉⵊ ",
 "wadar":"Se perdre,ⵡⴰⴹⴰⵔ",
 "wouda":"Faire ses ablutions,ⵡⵓⴷⴰ",
 "farej":"Regarder à la TV,ⴼⴰⵔⵊ",
 "bedder":"Changer,ⴱⴰⴷⵔ",
 "faire":"Iteg,ⵉⵜⴳ ",
 "dire":"Isawar,ⵉⵙⴰⵡⴻ",
 "pouvoir":"Izama,ⵉⵣⴰⵎⴰ",
 "aller":"Igwa,ⵉⴳⵡⴰ ",
 "voir":"Itwara,ⵉⵜⵡⴰⵔⴰ",
 "savoir":"Issen,ⵉⵙⵙⵏ",
 "vouloir":"Yazzou,ⵢⴰⵣⵣⵓ ",
 "venir":"Itassed,ⵉⵜⴰⵙⵙⴷ",
 "devoir":"Ikhessa,ⵉⵅⵙⵙⴰ ",
 "croire":"Itiqa,ⵉⵜⵉⵇⴰ ",
 "trouver":"Itaf,ⵉⵜⴰⴼ ",
 "donner":"Itich,ⵉⵜⵉⵛ",
 "prendre":"Iksi,ⵉⴽⵙⵉ",
 "parler":"Isawar/Itqassa,ⵉⵜⵇⵙⵙⴰ",
 "passer":"I3dou,ⵉⵄⴷⵓ",
 "mettre":"Iga,ⵉⴳⴰ",
 "tenir":"Itef,ⵉⵜⴻⴼ ",
 "laisser":"Ismeh/Ijja,ⵉⵊⵊⴰ ",
 "rester":"Iqim,ⵉⵇⵉⵎ",
 "entendre":"Itasra,ⵉⵜⴰⵙⵔⴰ ",
 "regarder":"Ighaza/Itwara,ⵉⵖⴰⵣⴰ",
 "répondre":"Itjawab/yara,ⵢⴰⵔⴰ ",
 "connaître":"Issen,ⵉⵙⵙⵏ",
 "arriver":"Youssad,ⵢⵓⵙⵙⴰⴷ",
 "J'ai":"Ray/rari,ⵔⴰⵢ",
 "tu as":"Rak/rach,ⵔⴰⴽ",
 "tu as fem":"Ram,ⵔⴰⵎ",
 "il a":"Ras,ⵔⴰⵙ",
 "nous avons":"Ranekh,ⵔⴰⵏⵖ",
 "vous avez":"Rakom/Rawem,ⵔⴰⴽⵓⵎ",
 "vous avez fem":"Rakent/Rachent,ⵔⴰⴽⴻⵏⵜ ",
 "ils ont":"Rassen,ⵔⴰⵙⴻⵏ ",
 "elles ont":"Rassent,ⵔⴰⵙⵙⴻⵏⵜ",
 "je vais":"Adahekh,ⴰⴷⴰⵀⵖ ",
 "tu vas":"Atahed,ⴰⵜⴰⵀⴻⴷ",
 "il va":"Itah,ⵉⵜⴰⵏⵀ",
 "elle va":"trah,ⵜⵔⴰⵀ",
 "nous allons":"Anrah,ⴰⵏⵔⴰⵀ",
 "vous allez":"Atahem,ⴰⵜⴰⵀⴻⵎ",
 "ils vont":"Adrahen,ⴰⵜⴰⵀⴻⵏ ",
 "je mange":"Tetekh,ⵜⴻⵜⴻⵅ",
 "tu manges":"Teted,ⵜⴻⵜⴻⴷ",
 "il mange":"Itat,ⵉⵜⴰⵜ",
 "nous mangeons":"Ntat,ⵏⵜⴰⵜ ",
 "vous mangez":"Tetem,ⵜⴻⵜⴻⵎ",
 "ils mangent":"Teten,ⵜⴻⵜⴻⵏ",
 "je suis":"Aqay,ⴰⵇⴰⵢ",
 "tu es":"Aqachek/aqachem,ⴰⵇⵢⴰⵛⴻⴽ",
 "il est":"Aqat,ⴰⵇⴰⵜ",
 "nous sommes":"Aqanekh,ⴰⵇⴰⵏⴻⵅ",
 "vous êtes":"Aqawem/aqakom/aqakent,ⴰⵇⴰⴽⵓⵎ",
 "ils sont , elles sont":"Aqan/aqant,ⴰⵇⴰⵏ",
 "j'ai":"Ghay,ⵖⴰⵢ",
 "tu as":"Ghak/gham,ⵖⴰⴽ ",
 "il a/ elle a":"Ghas,ⵖⴰⵙ",
 "nous avons":"Ghanekh,ⵖⴰⵏⴻⵅ",
 "vous avez":"ghawem/ghakent,ⵖⴰⵡⴻⵎ",
 "ils / elles ont":"Ghassen/ghassent,ⵖⴰⵙⵙⴻⵏ",
 "je fais":"Tegegh,ⵜⴻⴳⵖ",
 "tu fais":"Tagad,ⵜⴰⴳⴰⴷ",
 "il fait":"Iteg,ⵉⵜⴻⴳ",
 "nous faisons":"Ntag,",
 "vous faîtes":"Tagam/Tagant,ⵜⴰⴳⴰⵎ ",
 "ils fonts ,elles fonts":"Tagan,ⵜⴰⴳⴰⵏ ",
 "je dit":"Qakh,ⵇⴰⵖ",
 "tu dis":"Taqad,ⵜⴰⵇⴰⴷ",
 "il dit,elle dit":"Iqqa/thaqa,ⵉⵇⵇⴰ",
 "nous disons":"Naqqa,ⵏⴰⵇⵇⴰ",
 "vous disez":"Taqqam,ⵜⴰⵇⵇⴰⵎ ",
 "ils disent, elles disent":"qan/qante,ⵇⴰⵏ ",
 "je peux":"zamakh,ⵣⴰⵎⴰⵖ",
 "tu peux":"tzamad,ⵜⵣⴰⵎⴰⴷ",
 "il peut ,elle peut":"izamma/tzamma,ⵉⵣⴰⵎⵎⴰ",
 "nous pouvons":"Nzama,ⵏⵣⴰⵎⴰ ",
 "vous pouvez":"tzamam,ⵜⵣⴰⵎⴰⵎ",
 "ils peuvent":"zamam,ⵣⴰⵎⴰⵎ",
 "ino":"Mon,ma,mes,ⵉⵏⵓ",
 "inech":"Ton,ta,tes,ⵉⵏⴻⵛ ",
 "inem":"Ton,ta,tes,ⵉⵏⴻⵎ",
 "inas":"Son,sa,ses,ⵉⵏⴰⵙ ",
 "innegh":"Notre,nos,ⵉⵏⵏⴻⵖ",
 "inwoum":"Votre,vos,ⵉⵏⵡⵓⵎ ",
 "inkoum":"Votre,vos,ⵉⵏⴽⵓⵎ",
 "inssen":"Leur,leurs,ⵉⵏⵙⵙⴻⵏ ",
 "inssent":"Leur,leurs,ⵉⵏⵙⵙⴻⵏⵜ ",
 "i":"à,pour,ⵉ",
 "kh , khef":"sur,ⵅ ",
 "ghar":"vers,ⵖⴰⵔ",
 "zi":"de,depuis,ⵣⵉ ",
 "n'":"de,ⵏ",
 "dhi":"dans,ⴷⵉ",
 "macha":"mais,ⵎⴰⵛⴰ ",
 "lebda":"toujours,ⵔⴻⴱⴷⴰ ",
 "3ammas":"jamais,ⵄⴰⵎⴰⵚ",
 "zich":"tôt,autrefois,avant,jadis,ⵣⵉⵛ",
 "dawahda":"après,plus tard,ⴷⴰⵡⴰⵀⴷⴰ",
 "oucha":"donc,ensuite,et puis,ⵓⵛⴰ ",
 "ar":"jusqu'à,ⴰⵔ",
 "roukha":"maintenant,à ce moment,ⵔⵓⵅⴰ",
 "deghya":"vite,de suite,ⴷⵖⵢⴰ",
 "s'oumari":"vite,de suite,ⵙ'ⵓⵎⴰⵔⵉ",
 "zath":"devant,ⵣⴰⵜ",
 "qibar":"en face,ⵇⵉⴱⴰⵔ",
 "tafé":"à côté,ⵜⴰⴼⴻⵔ",
 "manaya":"ceci,ⵎⴰⵏⴰⵢⴰ",
 "manayni":"cela,ⵎⴰⵏⴰⵢⵏⵉ",
 "umi":"lorsque,qui ?,ⵓⵎⵉ",
 "Mri":"lorsque,durant,ⵎⵔⵉ ",
 "min":"lorsque,ce que,quoi que ?,ⵎⵉⵏ ",
 "wi":"qui ?,ⵡⵉ",
 "manwen":"lequel ?,ⵎⴰⵏⵡⴻⵏ",
 "ma":"est-ce que,ⵎⴰ",
 "mamech":"comment,ⵎⴰⵎⴻⵛ",
 "mach7ar":"combien,ⵎⴰⵛⵃⴰⵔ ",
 "mani":"où ?,ⵎⴰⵏⵉ",
 "manis":"d'où ?,ⵎⴰⵏⵉⵙ",
 "mayemmi":"pourquoi ?,ⵎⴰⵢⴻⵎⵉ",
 "maghar":"pourquoi ?,ⵎⴰⵖⴰⵔ",
 "mermi":"quand ?,ⵎⴻⵔⵎⵉ ",
 "chan":"quelques,ⵛⴰⵏ",
 "woni":"celui,ⵡⵓⵏⵉ",
 "win":"celui,ⵡⵉⵏ",
 "tin":"celle,ⵜⵉⵏ",
 "teni":"celle,ⵜⴻⵏⵉ ",
 "yini":"ceux,ⵢⵉⵏⵉ ",
 "dinni":"là-bas,ⴷⵉⵏⵏⵉ",
 "din":"y (il y a),",
 "zegwami":"depuis,ⵣⴻⴳⵯⴰⵎⵉ ",
 "attas":"beaucoup,ⴰⵟⴰⵙ",
 "drust":"peu,ⴷⵔⵓⵙⵜ",
 "Aqqa":"voilà,ⴰⵇⵇⴰ",
 "mintazod ataswed":"Que veux-tu boire ?,ⵎⵉⵏ ⵜⴰⵣⵓⴷ ⴰⵜⵙⵡⴰⴷ ",
 "tadath negh tadath nwem":"Notre maison est la vôtre,ⵜⴰⴷⴰⵝ ⵏⵖ ⵜⴰⴷⴰⵜ ⵏⵡⵎ",
 "sonand":"Ils sonnent (téléphone ou porte),ⵙⵓⵏⵏⴰⴷ",
 "rah azem tawath":"Va ouvrir la porte,ⵔⴰⵃ ⴰⵣⴻⵎ ⵜⴰⵡⴰⵔⵜ",
 "odin":"C'est qui ? (quand on frappe),ⵓⴷⵉⵏ ",
 "amni":"Comme ça,ⴰⵎⵏⵉ ",
 "prendre":"Agh,ⴰⵖ",
  "sécher":"Azgh,ⴰⵣⵖ",
  "être Accessible (prix)":"Arfeq,ⴰⵔⴼⵇ",
  "être Bon Marché":"Arkhes,ⴰⵔⵅⵙ",
  "se Fatiguer":"Aher,ⴰⵀⵔ",
  "s’enfuir":"Arwer,ⴰⵔⵡⴻⵔ",
  "refuser":"Ag,ⴰⴳ",
  "s'éloigner":"Agwj,ⴰⴳⵡⵊ",
  "revenir":"ArjeƐ,ⴰⵔⴷⵄ",
  "s’user/ Être Usé":"Archa,ⴰⵔⵛⴰ",
  "se Pencher":"Adar,ⴰⴷⴰⵔ",
  "courir":"Azer,ⴰⵣⵔ",
  "entrer":"Adef,ⴰⴷⴼ",
  "trouver":"Af,ⴰⴼ",
  "apporter":"Awi,ⴰⵡⵉ",
  "vider":"Ar,ⴰⵔ",
  "prêter / Emprunter":"ArḌeri,ⴰⵔⴹⵔⵉ",
  "endosser":"Arbu,ⴰⵔⴱⵓ",
  "se Poser Se Percher (sur La Branche)":"Ars,ⴰⵔⵙ",
  "ouvrir":"ArẒam,ⴰⵔⵥⴰⵎ",
  "ajouter":"Arni,ⴰⵔⵏⵉ",
  "écrire":"Ari,ⴰⵔⵉ",
  "être Prés De":"Ades,ⴰⴷⵙ",
  "venir":"As,ⴰⵙ",
  "manger (+excès)":"Argheb,ⴰⵔⵖⴱ",
  "enfanter":"Aru,ⴰⵔⵓ",
  "prendre Le Petit Déjeuner":"Argheq,ⴰⵔⵖⵇ",
  "casser":"ArẒ,ⴰⵔⵥ",
  "puiser (eau)":"Ajam,ⴰⵊⴰⵎ",
  "rentrer Chez Soi":"ArkuḤ,ⴰⵔⴽⵯⵃ",
  "chercher":"Arzu,ⴰⵔⵣⵓ",
  "croire":"Amen,ⴰⵎⵏ",
  "donner Une Fortune":"Arzeq,ⴰⵔⵣⵇ",
  "dépecer":"Azu,ⴰⵣⵓ",
  "voler (biens D’autrui)":"Achar,ⴰⵛⴰⵔ",
  "devoir (dettes)":"Ars,ⴰⵔⵙ",
  "avoir Un Rapport Parenté":"As,ⴰⵙ",
  "trembler":"Arjij,ⴰⵔⵊⵉⵊ",
  "donner L’ordre":"AmaṚ,ⴰⵎⴰⵕ",
  "se replier":"ArẒ ,ⴰⵔⵥ",
  "avoir Mal Aux Yeux":"AḌen,ⴰⴹⵏ",
  "accrocher":"Ajer,ⴰⵊⵔ",
  "se salir":"Ames,ⴰⵎⵙ",
  "être Au Courant…":"Argeb,ⴰⵔⴳⴱ",
  "brûler":"Argh,ⴰⵔⵖ",
  "mélanger":"AṚwi,ⴰⵕⵡⵉ",
  "lâcher":"Arkhu,ⴰⵔⵅⵓ",
  "accepter":"ArḌa,ⴰⵔⴹⴰ",
  "arriver":"AWḌ,ⴰⵡⴹ",
  "en avoir assez":"AẒ,ⴰⵥ",
  "garder (bétail)":"Arwes,ⴰⵔⵡⵙ",
  "être jaloux":"Assem,ⴰⵙⵎ",
  "être amer":"ArẒeg,ⴰⵔⵥⴳ",
  "bénir":"ArḌa,ⴰⵔⴹⴰ",
  "être / Devenir Mou":"ArḌab,ⴰⵔⴹⴰⴱ",
  "tressaillir":"ArmiMi,ⴰⵔⵎⵉⵎⵉ",
  "triompher":"Arna,ⴰⵔⵏⴰ",
  "vomir":"AṚ,ⴰⵕ",
  "pointer":"AṚcham,ⴰⵕⵛⴰⵎ",
  "être Content":"AṚcheq,ⴰⵕⵛⵇ",
  "se Mettre Dans Un Coin":"ArKen,ⴰⵔⴽⴰⵏ",
  "donner Des Coups De Pieds":"Archer,ⴰⵔⵛⵔ",
  "grincer (les Dent)":"ARugses,ⴰⵔⵓⴳⵙⴻⵙ",
  "eparpiller":"ArDej,ⴰⵔⴷⴻⵊ",
  "se rendre compte":"Acha,ⴰⵛⴰ",
  "acheter des céréales":"Aju,ⴰⵊⵓ",
  "se reposer,rester calme":"ArYeḤ,ⴰⵔⵢⵃ",
  "piquer (âne)":"Achem,ⴰⵛⵎ",
  "être profond":"Adjegh,ⴰⴶⵖ",
  "monter":"Ari,ⴰⵔⵉ",
  "obliger à…":"BeZez,ⴱⵣⴻⵣ",
  "dépasser l’âge du mariage":"Bur,ⴱⵓⵔ",
  "doubler un tissu":"BeṬen,ⴱⵟⵏ",
  "être très tendre":"Bzuzi,ⴱⵣⵓⵣⵉ",
  "manquer (travail)":"BaṬer,ⴱⴰⵟⵔ",
  "être usés (habits)":"Buri,ⴱⵓⵔⵉ",
  "se plaindre":"Bara,ⴱⴰⵔⴰ",
  "s’affaisser":"Barch,ⴱⴰⵔⵛ",
  "se ceundre":"Byes,ⴱⵢⵙ",
  "moudre en grosses graines":"Bri,ⴱⵔⵉ",
  "eventrer":"BƐeẒ,ⴱⵄⵥ",
  "s’èloigner":"BaƐed,ⴱⴰⵄⴷ",
  "enfoncer":"BeẒ,ⴱⵥ",
  "changer":"BeDer,ⴱⴷⵔ",
  "construire":"Bna,ⴱⵏⴰ",
  "remplir (+excès)":"Beghbegh,ⴱⵖⴱⵖ",
  "entamer":"BdeƐ ,ⴱⴷⵄ",
  "annoncer Une Bonne Nouvelle":"BechaṚ,ⴱⵛⴰⵕ",
  "déshonorer":"Bahter,ⴱⴰⵀⵜⵔ",
  "coller avec force":"BeqaḌ,ⴱⵇⴰⴹ",
  "placer dans une cachette":"Bar,ⴱⴰⵔ",
  "epurer la laine":"Barwer,ⴱⴰⵔⵡⵔ",
  "se mettre debout":"BeD,ⴱⴷ",
  "noircir":"Barchene,ⴱⴰⵔⵛⵏ",
  "devenir fou":"Buhri,ⴱⵓⵀⵔⵉ",
  "etouffer":"Bukhsi,ⴱⵓⵅⵙⵉ",
  "sourire timidement":"BiSem,ⴱⵉⵙⵎ",
  "être / devenir enroué":"BuybeḤ,ⴱⵓⵢⴱⵃ",
  "être avare":"Bkher,ⴱⵅⵔ",
  "être pubère":"Bregh,ⴱⵔⵖ",
  "regarder (+ Étonnement)":"Beheg,ⴱⵀⴳ",
  "être trop mouillé":"Bejbej,ⴱⵊⴱⵊ",
  "bâter":"BardeƐ,ⴱⴰⵔⴷⵄ",
  "se rouler par terre":"BarkikeḌ,ⴱⴰⵔⴽⵉⴽⴹ",
  "crier (en public)":"BareḤ,ⴱⴰⵔⵃ",
  "faire le fier-à-bras":"BaṚen,ⴱⴰⵕⵏ",
  "être muet, muselé":"BKem,ⴱⴽⵎ",
  "se fâcher":"BaReq,ⴱⴰⵔⵇ",
  "apparaître":"Ḍehar,ⴹⵀⴰⵔ",
  "retourner,revenir":"Dwer,ⴷⵡⵔ",
  "vivre":"Dar,ⴷⴰⵔ",
  "grater les cordes d’une guitar":"Denden,ⴷⴻⵏⴷⴻⵏ",
  "cheminer lentement":"Darej,ⴷⴰⵔⵊ",
  "se cacher":"DuRi,ⴷⵓⵔⵉ",
  "galoper":"DaƐlak,ⴷⴰⵄⵍⴰⴽ",
  "suer":"Ded,ⴷⴻⴷ",
  "durer":"Dum,ⴷⵓⵎ",
  "bouder":"Ḍiq,ⴹⵉⵇ",
  "être ,devenir fragile":"ḌƐef,ⴹⵄⴼ",
  "réparer les chaussures":"Ḍaref,ⴹⴰⵔⴼ",
  "dresser animal":"ḌweƐ,ⴹⵡⵄ",
  "boire d’un seul trait":"Dardar,ⴷⴰⵔⴷⴰⵔ",
  "bousculer":"DaRem,ⴷⴰⵔⵎ",
  "suivre":"Ḍfar,ⴹⴼⴰⵔ",
  "faire du mal":"ḌaR,ⴹⴰⵔ",
  "voler ailes":"Ḍu,ⴹⵓ",
  "garantir":"Ḍmen,ⴹⵎⵏ",
  "parvenir":"Dark,ⴷⴰⵔⴽ",
  "appeler à la prière":"Den,ⴷⵏ",
  "construire un toit":"Ḍarz,ⴹⴰⵔⵣ",
  "meurtrir":"Degdeg,ⴷⴳⴷⴳ",
  "se débrouiller":"ḌeBar,ⴹⴱⴰⵔ",
  "convoiter":"ḌmeƐ,ⴹⵎⵄ",
  "se rouiler":"Dra,ⴷⵔⴰ",
  "descendre":"Ḍar,ⴹⴰⵔ",
  "préserver":"DƐem,ⴷⵄⵎ",
  "attacher (+ Paître)":"ḌeweṚ,ⴹⵡⵕ",
  "se Perdre":"ḌaYeƐ,ⴹⴰⵢⵄ",
  "mettre une matière grasse":"Dhen,ⴷⵀⵏ",
  "s’éloigner":"ḌaReq,ⴹⴰⵔⵇ",
  "faire un acte maladroit":"Dfech,ⴷⴼⵛ",
  "battre les cartes":"ḌmeṢ,ⴹⵎⵚ",
  "recouvrir":"Der,ⴷⵔ",
  "donner un coup":"Dkhem,ⴷⵅⵎ",
  "rendre responsable":"DeNa,ⴷⵏⴰ",
  "introduire dans le four":"Ḍarkh,ⴹⴰⵔⵅ",
  "repousser":"DeMer,ⴷⵎⵔ",
  "devenir sourd":"Duhcher,ⴷⵓⵀⵛⵔ",
  "être glacés de froid pieds":"DuBez,ⴷⵓⴱⵣ",
  "détonner":"DarḌeq,ⴷⴰⵔⴹⵇ",
  "exploser":"DeƐdeƐ,ⴷⵄⴷⵄ",
  "préparer une purée de fèves":"Ḍarz TamṚaqt,ⴹⴰⵔⵣ ⵜⴰⵎⵕⴰⵇⵜ",
  "rire":"ḌḤech,ⴹⵃⵛ",
  "avoir bon goût":"Ḍab,ⴹⴰⴱ",
  "plier":"Ḍfes,ⴹⴼⵙ",
  "retourner":"Ḍarn,ⴹⴰⵔⵏ",
  "être charmant":"Ḍarf,ⴹⴰⵔⴼ",
  "être / devenir aveugle":"Ḍarger,ⴹⴰⵔⴳⵔ",
  "se brûler ,avoir trop chaud":"DƐeq,ⴷⵄⵇ",
  "se précipiter sur":"DaRech,ⴷⴰⵔⵛ",
  "être lourd":"Dqer,ⴷⵇⵔ",
  "devenir":"Deḥa,ⴷⵃⴰ",
  "travailler le cuir":"Dbegh,ⴷⴱⵖ",
  "retourner la terre":"Fars,ⴼⴰⵔⵙ",
  "loucher":"FaryeḌ,ⴼⴰⵔⵢⴹ",
  "se rétablir":"Faja,ⴼⴰⵊⴰ",
  "distinguer":"Farz,ⴼⴰⵔⵣ",
  "se casser en mille morceaux":"FtuTes,ⴼⵜⵓⵜⵙ",
  "grelotter":"Frires,ⴼⵔⵉⵔⵙ",
  "attraper le fou-rire":"Farkikeḥ,ⴼⴰⵔⴽⵉⴽⵃ",
  "bâcler":"Farfech,ⴼⴰⵔⴼⵛ",
  "nager":"FteḤ,ⴼⵜⵃ",
  "devenir léger":"Fses,ⴼⵙⴻⵙ",
  "nettoyer la laine":"Fsu,ⴼⵙⵓ",
  "mettre à sécher":"Fsar,ⴼⵙⴰⵔ",
  "être gâté (enfant)":"FcheḤ,ⴼⵛⴻⵃ",
  "se lever à l’aube":"Fejar,ⴼⵊⴰⵔ",
  "tâtonner":"Fafa,ⴼⴰⴼⴰ",
  "s’envoler":"Farfar,ⴼⴰⵔⴼⴰⵔ",
  "se Distraire":"FuRej,ⴼⵓⵔⵊ",
  "libérer":"FeK,ⴼⴽ",
  "tailler / découper":"FeṢer,ⴼⵚⵔ",
  "découdre":"Fteq,ⴼⵜⵇ",
  "verser":"FaRegh,ⴼⴰⵔⵖ",
  "rouler du couscous":"Fter,ⴼⵜⵔ",
  "détacher":"Fsy,ⴼⵙⵢ",
  "penser":"FeKeṚ,ⴼⴽⵕ",
  "dévoyer":"Feles,ⴼⵍⵙ",
  "déchirer d’un seul coup":"Fri,ⴼⵔⵉ",
  "déjeuner":"FḌar,ⴼⴹⴰⵔ",
  "balayer":"FarḌ,ⴼⴰⵔⴹ",
  "cuire à la vapeur":"FeWaṚ,ⴼⵡⴰⵕ",
  "comprendre":"Fhem,ⴼⵀⵎ",
  "inspecter":"FeṬech,ⴼⵟⵛ",
  "dévoiler":"FḌeḤ,ⴼⴹⵃ",
  "trier ,nettoyer":"Farn,ⴼⴰⵔⵏ",
  "mâcher":"FeẒ,ⴼⵥ",
  "manquer de pudeur":"Fuhart,ⴼⵓⵀⴰⵔⵜ",
  "se déverser":"FeYeḌ,ⴼⵢⴻⴹ",
  "s’essouffler":"FqiQas,ⴼⵇⵉⵇⴰⵙ",
  "être / devenir tordu":"Fargh,ⴼⴰⵔⵖ",
  "se lasser":"Fcher,ⴼⵛⵔ",
  "avoir soif":"Fad,ⴼⴰⴷ",
  "diviser":"Farq,ⴼⴰⵔⵇ",
  "sortir De La Coquille":"Fruri,ⴼⵔⵓⵔⵉ",
  "eclater":"Fekhs,ⴼⵅⵙ",
  "avoir bonne mine":"FuNek,ⴼⵓⵏⴽ",
  "mourir / être épuisé":"Fna,ⴼⵏⴰ",
  "sortir":"Fegh,ⴼⵖ",
  "se réveiller":"Faq,ⴼⴰⵇ",
  "se cacher":"Far,ⴼⴰⵔ",
  "s’avérer":"Fu,ⴼⵓ",
  "pratiquer l’agriculture":"FadjeḤ,ⴼⴰⴶⵃ",
  "croire, sembler":"Ghir,ⵖⵉⵔ",
  "s’éclipser / être avalé":"Ghri,ⵖⵔⵉ",
  "sombrer":"GhḌes,ⵖⴹⵙ",
  "avoir mauvaise mine":"GhaYaṚ,ⵖⴰⵢⴰⵕ",
  "pousser plantes":"Ghmi,ⵖⵎⵉ",
  "avoir faim":"DjaẒ,ⴶⴰⵥ",
  "guérir":"Genfa,ⴳⵏⴼⴰ",
  "être épais":"GdaṚ,ⴳⴷⴰⵕ",
  "couler":"Gharq,ⵖⴰⵔⵇ",
  "disparaître":"Ghab,ⵖⴰⴱ",
  "déménager":"Gaj,ⴳⴰⵊ",
  "trahir":"Ghdar,ⵖⴷⴰⵔ",
  "se régaler":"GheBa,ⵖⴱⴰ",
  "compenser":"Gharm,ⵖⴰⵔⵎ",
  "grignoter":"GheẒ,ⵖⵥ",
  "tamiser":"Gharber,ⵖⴰⵔⴱⵔ",
  "faire/mettre / être":"G,ⴳ",
  "reprocher":"Djem,ⴶⵎ",
  "étudier,lire":"Ghar,ⵖⴰⵔ",
  "guider":"GeWed,ⴳⵡⴷ",
  "creuser":"Ghez,ⵖⵣ",
  "tricher":"Ghech,ⵖⵛ",
  "faire tomber":"GhḌer,ⵖⴹⵔ",
  "se relever":"GaƐed,ⴳⴰⵄⴷ",
  "cligner de l’oeil":"Ghmez,ⵖⵎⵣ",
  "corriger quelq’un mérite":"Ghzu,ⵖⵣⵓ",
  "mettre en prison":"GheYes,ⵖⵢⵙ",
  "avoir peur":"Gwed,ⴳⵡⴷ",
  "se révolter":"GheWegh,ⵖⵡⵖ",
  "manger plus de pain":"GeWez,ⴳⵡⵣ",
  "déchirer":"Ghars,ⵖⴰⵔⵙ",
  "pétrir":"Gw,ⴳⵡ",
  "égorger":"Ghars,ⵖⴰⵔⵙ",
  "divorcer":"Djef,ⴶⴼ",
  "faire des présages":"GeZen,ⴳⵣⵏ",
  "se hâter":"Ghawer,ⵖⴰⵡⵔ",
  "avorter":"Ghry,ⵖⵔⵢ",
  "piller":"GecheḌ,ⴳⵛⴹ",
  "chanter":"Ghenej,ⵖⵏⵊ",
  "gagner":"Ghreb,ⵖⵔⴱ",
  "avaler en grandes quantités":"Gharghar,ⵖⴰⵔⵖⴰⵔ",
  "secourir":"Ghat,ⵖⴰⵜ",
  "se fouler le pied":"Djaghzem,ⴶⴰⵖⵣⵎ",
  "boire à tire-larigot":"Gargeb,ⴳⴰⵔⴳⴱ",
  "être distrait":"Ghfer,ⵖⴼⵔ",
  "dégringoler":"HruBez,ⵀⵔⵓⴱⵣ",
  "lyncher":"Hicher,ⵀⵉⵛⵔ",
  "érrer":"Hum,ⵀⵓⵎ",
  "s’habiller élégamment":"HeẒet,ⵀⵥⵜ",
  "couler à flots eau":"Harhar,ⵀⴰⵔⵀⴰⵔ",
  "arriver lieu":"KhḌer,ⵅⴹⵔ",
  "vouloir":"Khes,ⵅⵙ",
  "se limiter":"Ḥed,ⵃⴷ",
  "retirer brusquement":"KhḌef,ⵅⴹⴼ",
  "avoir besoin":"Ḥdej,ⵃⴷⵊ",
  "brûler vivement":"Ḥdeq,ⵃⴷⵇ",
  "compatir":"Ḥin,ⵃⵉⵏ",
  "obetenir sa part":"Ḥart,ⵃⴰⵔⵜ",
  "surveiller":"ḤḌa,ⵃⴹⴰ",
  "être chaud":"Ḥma,ⵃⵎⴰ",
  "être étroit ,bloquer le passage":"Ḥsar,ⵃⵙⴰⵔ",
  "frissonner":"ḤtiTi,ⵃⵜⵉⵜⵉ",
  "vagabonder":"ḤaḤa,ⵃⴰⵃⴰ",
  "chasser les mouches":"ḤaReb,ⵃⴰⵔⴱ",
  "avoir des soucis":"ḤiSef,ⵃⵉⵙⴼ",
  "glisser entre les mains":"ḤruṬef,ⵃⵔⵓⵟⴼ",
  "boiter":"ḤiḌar,ⵃⵉⴹⴰⵔ",
  "s’écarter":"ḤaYed,ⵃⴰⵢⴻⴷ",
  "laisser":"Hta,ⵀⵜⴰ",
  "compter":"Ḥseb,ⵃⵙⴱ",
  "couper de l’herbe":"Ḥtech,ⵃⵜⵛ",
  "se raser":"ḤeF,ⵃⴼ",
  "jeter qq. chose violement":"Ḥri,ⵃⵔⵉ",
  "embêter":"Hwer,ⵀⵡⵔ",
  "Casser En Petits Morceaux":"Hechem,ⵀⵛⵎ",
  "donner un supplément":"HeDaṚ,ⵀⴷⴰⵕ",
  "gâcher, renier":"ḤaRem,ⵃⴰⵔⵎ",
  "ramasser du bois":"Ḥarwech,ⵃⴰⵔⵡⵛ",
  "envier":"Ḥsed,ⵃⵙⴷ",
  "obliger":"ḤeTem,ⵃⵜⵎ",
  "ramasser vite":"Ḥru,ⵃⵔⵓ",
  "dire / faire des bêtises":"HeGar,ⵀⴳⴰⵔ",
  "remuer":"ḤaRech,ⵃⴰⵔⵛ",
  "enduire":"ḤeNech,ⵃⵏⵛ",
  "menacer":"HuD,ⵀⵓⴷ",
  "jeter des pierres":"Ḥejar,ⵃⵊⴰⵔ",
  "frictionner":"Ḥek,ⵃⴽ",
  "tirer le sceau du puits":"Ḥreb,ⵃⵔⴱ",
  "niveler la terre":"ḤeMaṚ,ⵃⵎⴰⵕ",
  "demander en mariage":"KhḌeb,ⵅⴹⴱ",
  "gouverner,toucher":"Ḥkem,ⵃⴽⵎ",
  "remplacer":"Khref,ⵅⵔⴼ",
  "circoncire":"Khten,ⵅⵜⵏ",
  "être métayer":"KheMes,ⵅⵎⵙ",
  "esquiver":"Khnes,ⵅⵏⵙ",
  "travailler":"Khdem,ⵅⴷⵎ",
  "se tromper":"KhḌa,ⵅⴹⴰ",
  "moudre":"Ḥri,ⵃⵔⵉ",
  "rattraper":"Ḥart,ⵃⴰⵔⵜ",
  "faire attention":"Ḥawr,ⵃⴰⵡⵔ",
  "être en crue rivière":"Ḥmer,ⵃⵎⵔ",
  "être pris / coincé":"ḤṢer,ⵃⵚⵔ",
  "se lancer":"HuB,ⵀⵓⴱ",
  "tourner autour de":"Ḥrara,ⵃⵔⴰⵔⴰ",
  "être enroulé dans un tissu":"ḤnuNeḌ,ⵃⵏⵓⵏⴹ",
  "ramper , glisser":"Ḥrurd,ⵃⵔⵓⵔⴷ",
  "être / devenir mécontent":"KheYeq,ⵅⵢⵇ",
  "inquiéter":"Khewej,ⵅⵡⵊ",
  "confisquer":"ḤeWes,ⵃⵡⵙ",
  "cafouiller":"KharweḌ,ⵅⴰⵔⵡⴹ",
  "apprendre":"ḤfeḌ,ⵃⴼⴹ",
  "être dans le besoin":"ḤeWej,ⵃⵡⵊ",
  "remercier dieu":"Ḥmed,ⵃⵎⴷ",
  "démolir":"Hdem,ⵀⴷⵎ",
  "limiter":"ḤeD,ⵃⴷ",
  "frapper Brusquement":"KhbeḌ,ⵅⴱⴹ",
  "arracher":"KhḌef,ⵅⴹⴼ",
  "prendre sa part":"Ḥuz,ⵃⵓⵣ",
  "paître":"Hda,ⵀⴷⴰ",
  "toucher":"Ḥada,ⵃⴰⴷⴰ",
  "payer":"KhedjeṢ,ⵅⴶⵚ",
  "cacher":"KheMer,ⵅⵎⵔ",
  "être déréglé":"Khsar,ⵅⵙⴰⵔ",
  "griffer":"Khbech,ⵅⴱⵛ",
  "perdre":"Khsar,ⵅⵙⴰⵔ",
  "faire tourner":"ḤeNeḌ,ⵃⵏⴹ",
  "créer le désordre":"HarweḌ,ⵀⴰⵔⵡⴹ",
  "coudre":"kheYeḌ,ⵅⵢⴻⴹ",
  "regarder":"Khzar,ⵅⵣⴰⵔ",
  "avoir des hallucinations":"Khayer,ⵅⴰⵢⵔ",
  "maudire":"Khza,ⵅⵣⴰ",
  "mettre au dépôt":"Khzen,ⵅⵣⵏ",
  "faire choisir":"KheyaṚ,ⵅⵢⴰⵕ",
  "soulever":"HeZ,ⵀⵣ",
  "briser":"HaRem,ⵀⴰⵔⵎ",
  "être enfin prêt":"ḤeZem,ⵃⵣⵎ",
  "glisser":"ḤrudjeḌ,ⵃⵔⵓⴶⴹ",
  "être présent":"ḤḌar,ⵃⴹⴰⵔ",
  "être facile":"Hwen,ⵀⵡⵏ",
  "ne pas supporter":"Ḥmer,ⵃⵎⵔ",
  "rougir peau":"HaRa,ⵀⴰⵔⴰ",
  "cogiter":"KhaRaṢ,ⵅⴰⵔⴰⵚ",
  "s’écrouler":"Hrura,ⵀⵔⵓⵔⴰ",
  "se brûler":"Ḥraq,ⵃⵔⴰⵇ",
  "naître":"Khreq,ⵅⵔⵇ",
  "être / devenir rond":"ḤnuNi,ⵃⵏⵓⵏⵉ",
  "réfléchir":"Hendez,ⵀⵏⴷⵣ",
  "se faire":"Khreq,ⵅⵔⴻⵇ",
  "planter":"Ẓu,ⵥⵓ",
  "falloir, Manquer":"KheṢ,ⵅⵚ",
  "être ,exister":"Iri,ⵉⵔⵉ",
  "être cher objets":"Ighra,ⵉⵖⵔⴰ",
  "se faner":"ISraw,ⵉⵙⵔⴰⵡ",
  "être large":"Iriw,ⵉⵔⵉⵡ",
  "choisir":"IkhḌar,ⵉⵅⴹⴰⵔ",
  "avoir des envies":"Init,ⵉⵏⵉⵜ",
  "s’habiller":"IrḌ,ⵉⵔⴹ",
  "jouer":"Irar,ⵉⵔⴰⵔ",
  "dire":"Ini,ⵉⵏⵉ",
  "être filtré ,tamisé":"Ifif,ⵉⴼⵉⴼ",
  "évoquer":"Idar,ⵉⴷⴰⵔ",
  "être lavé":"Irid,ⵉⵔⵉⴷ",
  "être délicieux":"IziḌ,ⵉⵣⵉⴹ",
  "être propre":"Izdeg,ⵉⵣⴷⴳ",
  "peser les céréales":"IzeḌ,ⵉⵣⴹ",
  "devancer":"Izar,ⵉⵣⴰⵔ",
  "surpasser":"If / Uf,ⵉⴼ / ⵓⴼ",
  "mourir non musulman":"Jef,ⵊⴼ",
  "donner naissance":"J (d),ⵊ (ⴷ)",
  "peindre les murs chaux":"JeYar,ⵊⵢⴰⵔ",
  "être / devenir muet":"Jnew,ⵊⵏⵡ",
  "geler":"Jres,ⵊⵔⵙ",
  "jurer":"Jadj,ⵊⴰⴶ",
  "ne pas prendre plantes":"JaReḤ,ⵊⴰⵔⵃ",
  "devenir granuleux":"Jben,ⵊⴱⵏ",
  "réunir ,accumuler":"Jru,ⵊⵔⵓ",
  "faire la guerre sainte":"Jahed,ⵊⴰⵀⴷ",
  "pousser humains":"Jma,ⵊⵎⴰ",
  "passer la serpilliére":"Jef,ⵊⴼ",
  "répartir les cartes":"JaRa,ⵊⴰⵔⴰ",
  "éssayer":"JaṚeb,ⵊⴰⵕⴱ",
  "être dernier":"Jura,ⵊⵓⵔⴰ",
  "être gelé":"Jmed,ⵊⵎⴷ",
  "regarder + Surprise":"JƐaṚ,ⵊⵄⴰⵕ",
  "crier fort":"JeƐjeƐ,ⵊⵄⵊⵄ",
  "tirer":"Jbed,ⵊⴱⴷ",
  "ramasser":"Jru,ⵊⵔⵓ",
  "entraîner":"JaṚ,ⵊⴰⵕ",
  "mijoter":"JeMaṚ,ⵊⵎⵕ",
  "réparer":"JbaṚ,ⵊⴱⵕ",
  "Étrangler":"JeYef,ⵊⵢⴼ",
  "laper":"Jer,ⵊⵔ",
  "gazouiller":"Jaw,ⵊⴰⵡ",
  "boire d’une seul gorgée":"Jghem,ⵊⵖⵎ",
  "pécher ,chasser":"Jmar,ⵊⵎⴰⵔ",
  "être fort":"Jhed,ⵊⵀⴷ",
  "se rassasier":"Jiwen,ⵊⵉⵡⵏ",
  "se lever":"Kar,ⴽⴰⵔ",
  "se maquiller les yeux":"KeḤer,ⴽⵃⵔ",
  "geler , être gelé":"Kuchem,ⴽⵓⵛⵎ",
  "se recroqueviller":"KuMech,ⴽⵓⵎⵛ",
  "ricaner":"KeḤkeḤ,ⴽⵃⴽⵃ",
  "être crépu":"Karnuni,ⴽⴰⵔⵏⵓⵏⵉ",
  "s’rsclaffer":"KeƐkeƐ,ⴽⵄⴽⵄ",
  "enlever":"Kes,ⴽⵙ",
  "dévaliser":"KecheḌ,ⴽⵛⴹ",
  "charger quelqu’un de quelque chose":"KeLef,ⴽⵍⴼ",
  "couvrir d’un linceul":"KeFen,ⴽⴼⵏ",
  "terminer":"KeMer,ⴽⵎⵔ",
  "bien traiter quelqu’un":"KeBaṚ,ⴽⴱⴰⵕ",
  "fumer":"KeYef,ⴽⵢⴼ",
  "tenir bon":"Kabar,ⴽⴰⴱⴰⵔ",
  "perdre sa couleur":"Kchef,ⴽⵛⴼ",
  "deviner":"Kachef,ⴽⴰⵛⴼ",
  "démentir":"KeDeb,ⴽⴷⴱ",
  "saigner du nez":"Kunzar,ⴽⵓⵏⵣⴰⵔ",
  "jouir":"KuKeḌ,ⴽⵓⴽⴹ",
  "mettre à l’excès":"KeTar,ⴽⵜⴰⵔ",
  "gâter":"KeFes,ⴽⴼⵙ",
  "être entamé pain":"KuṬef,ⴽⵓⵟⴼ",
  "briller multicolore":"Lulech,ⵍⵓⵍⵛ",
  "prononcer Allah":"Lehleh,ⵍⵀⵍⵀ",
  "se peigner":"McheḌ,ⵎⵛⴹ",
  "grandir":"MghaṚ,ⵎⵖⴰⵕ",
  "être petit ,rapetisser":"MẒy,ⵎⵥⵢ",
  "avoir une bonne santé":"MneƐ,ⵎⵏⵄ",
  "mourir":"Met,ⵎⵜ",
  "ramper":"Mudjegh,ⵎⵓⴶⵖ",
  "être houleux ,tourner tête":"Muj,ⵎⵓⵊ",
  "avancer à 4 pattes":"Murd,ⵎⵓⵔⴷ",
  "mourir asphyxié":"MurḌes,ⵎⵓⵔⴹⵙ",
  "s’étendre au même le sol":"MaReḤ,ⵎⴰⵔⵃ",
  "malmener":"Mermed,ⵎⵔⵎⴷ",
  "accompagner":"Mun,ⵎⵓⵏ",
  "effacer":"MḤa,ⵎⵃⴰ",
  "essuyer":"MseḤ,ⵎⵙⵃ",
  "moissonner":"Mjar,ⵎⵊⴰⵔ",
  "comparer":"MeTer,ⵎⵜⵔ",
  "attacher solidement":"MḤeḌ,ⵎⵃⴹ",
  "dîner":"Munsu,ⵎⵓⵏⵙⵓ",
  "faire souffrir":"MeḤen,ⵎⵃⵏ",
  "se marier":"Mrech,ⵎⵔⵛ",
  "se pencher":"MeYer,ⵎⵢⵔ",
  "manquer de sel":"Mses,ⵎⵙⴻⵙ",
  "être enragé":"MuZar,ⵎⵓⵣⴰⵔ",
  "se déplacer":"MuṬi,ⵎⵓⵟⵉ",
  "devenir ami":"Mduker,ⵎⴷⵓⴽⵔ",
  "être égaux":"MquDa,ⵎⵇⵓⴷⴰ",
  "se rencontrer":"Msagar,ⵎⵙⴰⴳⴰⵔ",
  "tresser":"Mud,ⵎⵓⴷ",
  "battre fortement":"Marḥ,ⵎⴰⵔⵃ",
  "se fatiguer":"MaRat,ⵎⴰⵔⴰⵜ",
  "être / devenir blanc":"Mrer,ⵎⵔⴻⵔ",
  "être salé":"Mreḥ,ⵎⵔⵃ",
  "avoir mal à la tête":"Mrudji,ⵎⵔⵓⴶⵉ",
  "frotter":"Msed,ⵎⵙⴷ",
  "Frapper À La Tête (sang)":"Marz,ⵎⴰⵔⵣ",
  "être solide":"Mten,ⵎⵜⵏ",
  "se quereller femmes":"MchuBech,ⵎⵛⵓⴱⵛ",
  "se disputer debout hommes":"MughẒer,ⵎⵓⵖⵥⵔ",
  "être difficile":"Mra,ⵎⵔⴰ",
  "se moquer":"Marḍen,ⵎⴰⵔⴹⵏ",
  "perdre le nord":"Mhafa,ⵎⵀⴰⴼⴰ",
  "être imperméable farine":"Meja,ⵎⵊⴰ",
  "être trituré":"Nghed,ⵏⵖⴷ",
  "être déplumé":"Nchef,ⵏⵛⴼ",
  "mûrir fruits":"Nḍy,ⵏⴹⵢ",
  "avoir l’intention":"Nwa,ⵏⵡⴰ / ⵏⵓⴰ",
  "s’infiltrernNaturellement":"NeS,ⵏⵙ",
  "faire nuit":"Ndeṛ,Ṭram,ⵏⴷⵕ ⵟⵔⴰⵎ",
  "être exténué":"Nzef,ⵏⵣⴼ",
  "se griffer le visage":"Ndeb,ⵏⴷⴱ",
  "mordre goulûment":"Nhech,ⵏⵀⵛ",
  "se vexer":"Ndqaṛ,ⵏⴷⵇⴰⵕ",
  "secouer pour nettoyer":"Nfaḍ,ⵏⴼⴰⴹ",
  "sursauter":"Nekhfeḍ,ⵏⵅⴼⴹ",
  "déambuler":"Neḍ,ⵏⴹ",
  "se délier":"Nufsar,ⵏⵓⴼⵙⴰⵔ",
  "enlever les tâches":"Nqeḍ,ⵏⵇⴹ",
  "couvrir ,enterrer":"Nt,ⵏⵜ",
  "se tordre pieds":"Neɛqaṛ,ⵏⵄⵇⴰⵕ",
  "être baratté":"Ndu,ⵏⴷⵓ",
  "avaler de travers":"Nezreq,ⵏⵣⵔⵇ",
  "osciller":"Neyrur,ⵏⵢⵔⵓⵔ",
  "coûter":"Nqam,ⵏⵇⴰⵎ",
  "rendre visite":"Newju,ⵏⵡⵊⵓ",
  "prendre peur":"NekhreƐ,ⵏⵅⵔⵄ",
  "se sauver de Peur":"Nejref,ⵏⵊⵔⴼ",
  "s’égarer":"Nejra,ⵏⵊⵔⴰ",
  "se lever soleil":"Nqaṛ,ⵏⵇⴰⵕ",
  "se désister":"Nqar,ⵏⵇⴰⵔ",
  "gronder":"Nhem,ⵏⵀⵎ",
  "perdre quelqu’un de proche":"Nury,ⵏⵓⵔⵉ",
  "renier":"NKeṛ,ⵏⴽⵕ",
  "fleurir":"NeWaṛ,ⵏⵡⴰⵕ / ⵏⵓⴰⵔ",
  "trimer":"Nber,ⵏⴱⵔ (ⵏⴲⵔ)",
  "pleuvoir en fine gouttes":"Nefnef,ⵏⴼⵏⴼ",
  "scier":"Njaṛ,ⵏⵊⴰⵕ",
  "sauter":"Ngez,ⵏⴳⵣ",
  "être cuit":"Nw,ⵏⵡ",
  "sangloter":"Nikhsis,ⵏⵉⵅⵙⵉⵙ",
  "enterrer":"Nḍer,ⵏⴹⵔ",
  "dresser un piège":"Ndi,ⵏⴷⵉ",
  "somnoler":"Nudem,ⵏⵓⴷⵎ",
  "avouer":"Nɛem,ⵏⵄⵎ",
  "dissuader":"Nha,ⵏⵀⴰ",
  "aviser":"NeBeh,ⵏⴱⵀ",
  "jeter":"Nḍar,ⵏⴹⴰⵔ",
  "être mal élevé":"Ndsaṛ,ⵏⴷⵙⴰⵕ",
  "echanger ,transposer":"Neqer,ⵏⵇⵔ",
  "taquiner":"Nbech,ⵏⴱⵛ",
  "exiler":"Nfa,ⵏⴼⴰ",
  "picorer":"Nqeb,ⵏⵇⴱ",
  "réprimer":"Nqem,ⵏⵇⵎ",
  "parler D’une Voix Nasillarde":"Neghnegh,ⵏⵖⵏⵖ",
  "Être Bien Battu (blé)":"Nghed,ⵏⵖⴷ",
  "parler,dire":"Nḍeq,ⵏⴹⵇ",
  "passer la nuit":"Ns,ⵏⵙ",
  "se sauver":"Njem,ⵏⵊⵎ",
  "tirer brusquement":"Nder,ⵏⴷⵔ",
  "regretter":"Ndem,ⵏⴷⵎ",
  "être utile":"Nfeɛ,ⵏⴼⵄ",
  "s’habituer":"Nam,ⵏⴰⵎ",
  "diminuer":"Nqes,ⵏⵇⵙ",
  "s’apprêter à":"Nawr,ⵏⴰⵡⵔ",
  "s’en aller ,marcher":"Ujur,ⵓⵊⵓⵔ",
  "être haut ,aller vers le haut":"Uɛra,ⵓⵄⵔⴰ",
  "tousser":"Usu,ⵓⵙⵓ",
  "être mouillé":"UF,ⵓⴼ",
  "être gonflé":"UF,ⵓⴼ",
  "griller grains":"Urf,ⵓⵔⴼ",
  "monde toucher à sa fin":"UQa,ⵓⵇⴰ",
  "rêver":"Urja,ⵓⵔⵊⴰ",
  "s’insurger":"UMugh,ⵓⵎⵓⵖ",
  "se faire rare":"Udrus,ⵓⴷⵔⵓⵙ",
  "avoir une belle allure":"Ungud,ⵓⵏⴳⵓⴷ",
  "être ,devenir épais":"UZur,ⵓⵣⵓⵔ",
  "dépasser":"Ujar,ⵓⵊⴰⵔ",
  "manquer d’eau puits":"Udun,ⵓⴷⵓⵏ",
  "s’asseoir comme un singe":"QuRed,ⵇⵓⵔⴷ",
  "être ,rendre impuissant":"Qen,ⵇⵏ",
  "s’ennuyer":"Qneḍ,ⵇⵏⴹ",
  "être originaire de":"Qarch,ⵇⴰⵔⵛ",
  "être abondant":"Qwa,ⵇⵡⴰ",
  "être tordu":"Qwes,ⵇⵡⵙ",
  "dépenser":"Qarḍ,ⵇⴰⵔⴹ",
  "frapper aux deux pieds":"Qarḍ,ⵇⴰⵔⴹ",
  "être pénétrant savon":"QaṚ,ⵇⴰⵕ",
  "s’amuser":"QeṢar,ⵇⵚⴰⵔ",
  "écourter ,rapetisser":"Quḍeḍ,ⵇⵓⴹⴻⴹ",
  "faire tomber avec force":"QaṚeɛ,ⵇⴰⵕⵄ",
  "jouer au jeu du hasard":"QeMaṛ,ⵇⵎⴰⵕ",
  "goûter":"Qas,ⵇⴰⵙ",
  "éplucher":"Qechaṛ,ⵇⵛⴰⵕ",
  "carder la laine":"Qarḍech,ⵇⴰⵔⴹⵛ",
  "satisfaire ses invités":"QeWem,ⵇⵡⵎ",
  "aplatir le pain":"QaṚes,ⵇⴰⵕⵙ",
  "être sévère avec":"QeSeḥ,ⵇⵙⵃ",
  "se satisfaire de peu":"Qneɛ,ⵇⵏⵄ",
  "heurter":"Qarqeb,ⵇⴰⵔⵇⴱ",
  "se mettre face à l’Est":"QeBer,ⵇⴱⵔ",
  "être capable de":"QeD,ⵇⴷ",
  "s’approcher":"QaṚeb,ⵇⴰⵕⴱ",
  "tourner":"Qreb,ⵇⵔⴱ",
  "frire":"Qra,ⵇⵔⴰ",
  "couper":"QeS,ⵇⵙ",
  "veiller sur":"Qaber,ⵇⴰⴱⵔ",
  "attacher":"Qen,ⵇⵏ",
  "goûter ,essayer":"Qedjeb,ⵇⴶⴱ",
  "faire du bruit":"Qarqeb,ⵇⴰⵔⵇⴱ",
  "se terminer":"Qḍa,ⵇⴹⴰ",
  "lever en l’air":"QeẒeɛ,ⵇⵥⵄ",
  "préparer le thé":"Qam atay,ⵇⴰⵎ ⴰⵜⴰⵢ",
  "saisir":"QeBeḍ,ⵇⴱⴹ",
  "faire des roulades":"Qrujeɛ,ⵇⵔⵓⵊⵄ",
  "être/ devenir consistant":"Quṛ,ⵇⵓⵕ",
  "être dur ,difficile":"Qseḥ,ⵇⵙⵃ",
  "rester ,s’asseoir":"Qim,ⵇⵉⵎ",
  "partir":"Raḥ,ⵔⴰⵃ",
  "pleurer":"Ru,ⵔⵓ",
  "apprendre":"Rmed,ⵔⵎⴷ",
  "appeler":"Ragha,ⵔⴰⵖⴰ",
  "attendre":"Raja,ⵔⴰⵊⴰ",
  "rencontrer":"Rqa,ⵔⵇⴰ",
  "relever , Caler":"ReQem,ⵔⵇⵎ",
  "arriver":"ReḤeg,ⵔⵃⴳ",
  "s’occuper":"Rha,ⵔⵀⴰ",
  "se Couvrir":"ReḤef,ⵔⵃⴼ",
  "asperger":"Ṛuch,ⵕⵓⵛ",
  "atteindre la cible":"Rqef,ⵔⵇⴼ",
  "ramasser":"Rqeḍ,ⵔⵇⴹ",
  "coller":"Rseq,ⵔⵙⵇ",
  "convenir":"RiQ,ⵔⵉⵇ",
  "revitaliser plantes":"ReQeḥ,ⵔⵇⵃ",
  "coûter":"Swa,ⵙⵡⴰ",
  "être en bonne santé":"ṢeḤ,ⵚⵃ",
  "élever,éduquer":"Syem,ⵙⵢⵎ",
  "chauffer de l’orge":"Sri,ⵙⵔⵉ",
  "faire un noeud":"Charf,ⵛⴰⵔⴼ",
  "terminer un verset":"Srek,ⵙⵔⴽ",
  "envoyer":"Sifeḍ,ⵙⵉⴼⴹ",
  "tamiser":"SeYar,ⵙⵢⴰⵔ",
  "tendre la main pour prendre":"SwiZeḍ,ⵙⵡⵉⵣⴹ",
  "prendre un bain de soleil":"SuMar,ⵙⵓⵎⴰⵔ",
  "devenir":"Ṣbeḥ,ⵚⴱⵃ",
  "dorloter":"SḥiNeb,ⵙⵃⵉⵏⴱ",
  "prendre le large":"Sebseb,ⵙⴱⵙⴱ",
  "mentir":"SkhaReq,ⵙⵅⴰⵔⵇ",
  "respirer bruyamment":"Shunchef,ⵙⵀⵓⵏⵛⴼ",
  "Donner Une Paire De Claques":"SmeDarḍar,ⵙⵎⴷⴰⵔⴹⴰⵔ",
  "Rendre Droit":"Semrended,ⵙⵎⵔⵏⴷⴻⴷ",
  "faire semblant de":"Sniɛmer,ⵙⵏⵉⵄⵎⵔ",
  "être turbulent":"Ṣreb,ⵚⵔⴱ",
  "réconcilier":"Ṣreḥ,ⵚⵔⵃ",
  "féconder une vache":"Ṣreḥ,ⵚⵔⵃ",
  "faire paître":"Sarḥ,ⵙⴰⵔⵃ",
  "mélanger":"Sur,ⵙⵓⵔ",
  "aller doucement":"Saha,ⵙⴰⵀⴰ",
  "commencer quelque chose":"SeHer (di),ⵙⵀⵔ",
  "vexer":"Seɛqar,ⵙⵄⵇⴰⵔ",
  "être souffrant":"SḥuS,ⵙⵃⵓⵙ",
  "Voiler / Cacher":"Saṛ,ⵙⴰⵕ",
  "Tire Un Fil":"Stew,ⵙⵜⵡ",
  "Jeter Un Coup D’oeil":"SiJ,ⵙⵉⵊ",
  "Sourire":"Sfarnen,ⵙⴼⴰⵔⵏⴻⵏ",
  "Poindre (le Jour)":"Sungem,ⵙⵓⵏⴳⵎ",
  "Se Voiler La Tête":"Squmbar,ⵙⵇⵓⵎⴱⴰⵔ",
  "Lancer Des You-You":"Srewrew,ⵙⵔⵡⵔⵡ",
  "Tendre La Main":"Sigh Fus,ⵙⵉⵖ ⴼⵓⵙ",
  "Avancer Vers L’ennemi":"Sug,ⵙⵓⴳ",
  "Démarrer":"Sent,ⵙⵏⵜ",
  "Se Taire":"Sghed,ⵙⵖⴷ",
  "Écouter":"SḥeS,ⵙⵃⵙ",
  "Caqueter":"Sqaqa,ⵙⵇⴰⵇⴰ",
  "Se Laver Les Cheveux":"Sry,ⵙⵔⵢ",
  "regarder":"Sweḍ,ⵙⵡⴹ",
  "Tirer Augure":"ṢeBeḥ,ⵚⴱⵃ",
  "Entendre":"Ser,ⵙⵔ",
  "Souffler":"Suḍ,ⵙⵓⴹ",
  "Tremper Le Pain Dans La Sauce":"Sisen,ⵙⵉⵙⵏ",
  "Redresser":"SeGed,ⵙⴳⵯⴷ",
  "Beugler":"Smuhart,ⵙⵎⵓⵀⴰⵔⵜ",
  "Faire Avec":"SeLek,ⵙⵍⴽ",
  "Poser La Tête Sur Un Oreiller":"SuMet,ⵙⵓⵎⵜ",
  "Vanner":"ṢeFa,ⵚⴼⴰ",
  "Commercer":"SeBeb,ⵙⴱⴱ",
  "Respecter / Être Timide":"Sedḥa,ⵙⴷⵃⴰ",
  "Déborder":"Sfy,ⵙⴼⵢ",
  "Manger La Nuit (carême)":"ṢeḤar,ⵚⵃⴰⵔ",
  "Se Prosterner":"Sjed,ⵙⵊⴷ",
  "Se Reposer En S’appuyant":"SeNed,ⵙⵏⴷ",
  "Parler":"Siwer,ⵙⵉⵡⵔ",
  "Changer (argent)":"ṢaRef,ⵚⴰⵔⴼ",
  "Boire":"Su,ⵙⵓ",
  "Saluer":"Sedjem,ⵙⴶⵎ",
  "Battre (céréales)":"Sarwet,ⵙⴰⵔⵡⵜ",
  "Récolter":"ṢeYef,ⵚⵢⴼ",
  "Pardonner":"Smeḥ,ⵙⵎⵃ",
  "Faire / Être Froid / Refroidir":"Ṣmeḍ,ⵚⵎⴹ",
  "écouter":"SeNeṭ,ⵙⵏⵟ",
  "Ensorceler":"SeḤar,ⵙⵃⴰⵔ",
  "Scintiller":"Seqseq,ⵙⵇⵙⵇ",
  "Arroser":"Sew,ⵙⵡ",
  "Etendre / (parterre)":"SaReḥ,ⵙⴰⵔⵃ",
  "Tomber Sur / Trouver":"Saṛ,ⵙⴰⵕ",
  "Agacer":"ṢeDeɛ,ⵚⴷⵄ",
  "Acheter":"Segh,ⵙⵖ",
  "Filer La Laine":"Srew,ⵙⵔⵡ",
  "Renverser":"SeYeḥ,ⵙⵢⴻⵃ",
  "Embrasser":"Sudem,ⵙⵓⴷⵎ",
  "Trouver Difficelement":"SeDaṛ,ⵙⴷⴰⵕ",
  "Mériter":"SḥeQ,ⵙⵃⵇ",
  "envoyer":"SeK,ⵙⴽ",
  "Allumer":"Sigh,ⵙⵉⵖ",
  "Demander":"Seqsa,ⵙⵇⵙⴰ",
  "Connaître / Savoir":"Sen,ⵙⵏ",
  "Prendre Soin De":"Ṣun,ⵚⵓⵏ",
  "Ranger":"SeD,ⵙⴷ",
  "Clouer":"SeMaṛ,ⵙⵎⴰⵕ",
  "Rincer":"Srir,ⵙⵔⵉⵔ",
  "Manger Goulûment":"Sarḍ,ⵙⴰⵔⴹ",
  "Aller Au Marché":"SeWeq,ⵙⵡⵇ",
  "Errer":"Suḥ,ⵙⵓⵃ",
  "Voyager":"Safaṛ,ⵙⴰⴼⴰⵕ",
  "Prendre Place (bêtes)":"ṢeMeṭ,ⵚⵎⵟ",
  "Être Habile":"Says,ⵙⴰⵢⵙ",
  "Patienter":"Ṣbar,ⵚⴱⴰⵔ",
  "Tourner / Fermenter":"Smen,ⵙⵎⵏ",
  "Se Promener":"Sara,ⵙⴰⵔⴰ",
  "se Taire":"Sqar,ⵙⵇⴰⵔ",
  "Être Limpide / Pur":"Ṣfa,ⵚⴼⴰ",
  "Dégager Des Bulles":"Stekhtekh,ⵙⵜⵅⵜⵅ",
  "Siffler":"ṢeFar,ⵚⴼⴰⵔ",
  "Être Beau/ Bon":"Ṣebeḥ,ⵚⴱⵃ",
  "Placer Un Toit":"SeQef,ⵙⵇⴼ",
  "Crier":"SghuY,ⵙⵖⵓⵢ",
  "Laver Le Parterre":"SeYeq,ⵙⵢⴻⵇ",
  "s’affaisser":"Ṣter,ⵚⵜⵔ",
  "Enjamber":"Suṛf,ⵙⵓⵕⴼ",
  "Demeurer (le Jour)":"Cher,ⵛⵔ",
  "Être Dû Au Sort":"Chtab,ⵛⵜⴰⴱ",
  "Danser":"Chḍeḥ,ⵛⴹⵃ",
  "Être Beau / Charmant":"CheWaṛ,ⵛⵡⴰⵕ",
  "Ne Plus Oser Faire":"Chɛef,ⵛⵄⴼ",
  "Émigrer À L’Est":"ChaReq,ⵛⴰⵔⵇ",
  "Témoigner":"Chhed,ⵛⵀⴷ",
  "Devenir Avare":"CheḤ,ⵛⵃ",
  "Devenir Blanc":"Chemrer,ⵛⵎⵔⴻⵔ",
  "Être Affairé":"Chgher,ⵛⵖⵔ",
  "Être Brûlé":"Chmeḍ,ⵛⵎⴹ",
  "Pleuvoir Obliquement":"Cheryeḍ,ⵛⵔⵢⴻⴹ",
  "Profession De Foi En Islam":"CheHed,ⵛⵀⴷ (ⵛⵀⴸ)",
  "Tinter":"Chenchen,ⵛⵏⵛⵏ",
  "Être Handicapé":"Chrured,ⵛⵔⵓⵔⴷ (ⵛⵔⵓⵔⴸ)",
  "Cailler (lait)":"CHer,ⵛⵔ",
  "Griller":"Chnef,ⵛⵏⴼ",
  "Aspirer De L’air":"CheM,ⵛⵎ",
  "Arrêter (quelqu’un)":"Chneq,ⵛⵏⵇ",
  "Emballer":"Chmes,ⵛⵎⵙ",
  "Faire La Publicité":"CheHar,ⵛⵀⴰⵔ",
  "Tromper":"Chmet,ⵛⵎⵜ",
  "Pincer":"Chwi,ⵛⵡⵉ",
  "Demander Conseil":"Chawar,ⵛⴰⵡⴰⵔ",
  "Douter":"CheK,ⵛⴻⴽⴽ",
  "Radoter":"Charfeḥ,ⵛⴰⵔⴼⵃ",
  "Louer (maison)":"Chra,ⵛⵔⴰ",
  "Entraver":"Charf,ⵛⴰⵔⴼ",
  "Manger":"CH,ⵛ / ⵞ",
  "Labourer":"Charz,ⵛⴰⵔⵣ",
  "Fracasser":"CheQef,ⵛⵇⴼ",
  "Traverser Les Champs":"Chuq,ⵛⵓⵇ",
  "Être Préocupé":"Chḍen,ⵛⴹⵏ",
  "Remplir":"Chur,ⵛⵓⵔ",
  "Avilir":"CheYen,ⵛⵢⴻⵏ",
  "allumer":"Cheɛ,ⵛⵄ",
  "Secouer":"Chencher,ⵛⵏⵛⵔ",
  "déchirer":"CheReg,ⵛⵔⴳ",
  "Moucharder":"CheKem,ⵛⴽⵎ",
  "Avoir Les Cheveux Qui Commences À Blanchir Avec Le Temps":"Chab,ⵛⴰⴱ",
  "Pratiquer La Moisson":"CheWer,ⵛⵡⵔ",
  "Être Associé Avec":"Charch,ⵛⴰⵔⵛ",
  "Marchander":"CheṬar,ⵛⵟⴰⵔ",
  "se Plaindre":"Chetcha,ⵛⵜⵛⴰ",
  "Faire Paître Illégalement":"ChaReɛ,ⵛⴰⵔⵄ",
  "Détacher En Cassant":"Chreq,ⵛⵔⵇ",
  "Mesurer Avec La Main":"CheBar,ⵛⴱⴰⵔ",
  "Attraper":"CheBaṛ,ⵛⴱⴰⵕ",
  "Suffire":"Chfa,ⵛⴼⴰ",
  "Être Joli / Bon":"Chna,ⵛⵏⴰ",
  "Casser Violemment":"Chrekh,ⵛⵔⵅ",
  "Froncer Les Sourcils":"Chars,ⵛⴰⵔⵙ",
  "Avoir Les Cheveux Hérissés":"ChiRu,ⵛⵉⵔⵓ",
  "Fendre":"Chedjeq,ⵛⴶⵇ",
  "Bailler":"Tfa,ⵜⴼⴰ",
  "Abandonner":"Tark,ⵜⴰⵔⴽ",
  "Disperser":"TaRech,ⵜⴰⵔⵛ",
  "Être Borné":"ṬeMes,ⵟⵎⵙ",
  "Frapper Au Visage":"ṬeMes,ⵟⵎⵙ",
  "errer":"TeWeḥ,ⵜⵡⵃ",
  "s’égarer":"TeWej,ⵜⵡⵊ",
  "oublier":"Tu,ⵜⵓ",
  "se maîtriser":"TeBet,ⵜⴱⵜ",
  "têter":"Teḍ,ⵜⴹ",
  "tomber amoureux":"Tarbeṭ,ⵜⴰⵔⴱⵟ",
  "Dormir":"Ṭes,ⵟⵙ",
  "Se Perdre":"TLef,ⵜⵍⴼ",
  "Compter Sur":"Tcher,ⵜⵛⵔ",
  "Être Dans De Mauvais Draps":"Tkhed,ⵜⵅⴷ",
  "prendre":"Tef,ⵜⴼ",
  "capituler":"Trighar,ⵜⵔⵉⵖⴰⵔ",
  "bouillir (lait)":"Tartar,ⵜⴰⵔⵝⴰⵔ",
  "Dilapider":"Ṭeqṭeq,ⵟⵇⵟⵇ",
  "Mendier / Demander":"Tar,ⵜⴰⵔ",
  "se repentir":"Tub,ⵜⵓⴱ",
  "changer de nationalité":"Turizi,ⵜⵓⵔⵉⵣⵉ",
  "faire faillite":"ṬeBeg,ⵟⴱⴳ",
  "tâtonner":"Teftef,ⵜⴼⵜⴼ",
  "Être Saturé":"Tbeṛ,ⵜⴱⵕ",
  "miser":"Tawer,ⵜⴰⵡⵔ",
  "Avoir Lieu":"Wqeɛ,ⵡⵇⵄ",
  "Abonder":"Wseɛ,ⵡⵙⵄ",
  "Avoir Un Poste":"WeḌef,ⵡⴹⴼ",
  "être Difficile":"Wɛaṛ,ⵡⵄⴰⵕ",
  "revenir":"WeLeh,ⵡⵍⵀ",
  "vieillir":"Wsar,ⵡⵙⴰⵔ",
  "être jaune ":"Wargh,ⵡⴰⵔⵖ",
  "acheter de la viande":"WeZeɛ,ⵡⵣⵄ",
  "répartir la viande":"WeZeɛ,ⵡⵣⵄ",
  "être prêt":"Wjed,ⵡⵊⴷ (ⵡⵊⴸ)",
  "peser":"Wzen,ⵡⵣⵏ",
  "Prendre (place)":"Wɛed,ⵡⵄⴷ (ⵡⵄⴸ)",
  "frapper":"Wet,ⵡⵜ (ⵡⵝ)",
  "offrir":"Wheb,ⵡⵀⴱ",
  "répondre":"Wajeb,ⵡⴰⵊⴱ",
  "laisser des consignes":"WeṢa,ⵡⵚⴰ",
  "s’habituer à":"WeLef,ⵡⵍⴼ",
  "Avoir Des Scruples":"Weswes,ⵡⵙⵡⵙ",
  "voir":"Wara,ⵡⴰⵔⴰ",
  "donner":"Wch,ⵡⵛ",
  "se photographier":"Wṣef,ⵡⵚⴼ",
  "donner la parole":"Wch Awar,ⵡⵛ ⴰⵡⴰⵔ",
  "faire de la poésie":"Wzen Izri,ⵡⵣⵏ ⵉⵣⵔⵉ",
  "Sentir Le Besoin De Voir Quelqu’un":"WeḤech,ⵡⵃⵛ",
  "hériter":"Wert,ⵡⵔⵝ",
  "Reculer Pour Prendre De L’élan":"WeSeɛ,ⵡⵙⵄ",
  "briller":"SweṢeg,ⵙⵡⵚⴳ",
  "revendre":"Wadja,ⵡⴰⴶⴰ",
  "emuler":"Ɛaned,ⵄⴰⵏⴷ (ⵄⴰⵏⴸ)",
  "médire":"ƐeYeb,ⵄⵢⴻⴱ",
  "mettre au courant":"Ɛrem,ⵄⵔⵎ",
  "se tenir marché":"Ɛmaṛ,ⵄⵎⴰⵕ",
  "être tortueux":"ƐaṚeq,ⵄⴰⵕⵇ",
  "attendre":"Ɛayn,ⵄⴰⵢⵏ",
  "être hantée maison":"Ɛmaṛ,ⵄⵎⴰⵕ",
  "se marier":"Ɛmaṛ,ⵄⵎⴰⵕ",
  "fréquenter":"Ɛachar,ⵄⴰⵛⴰⵔ",
  "Aller Vers Quelqu’un":"ƐaReḍ,ⵄⴰⵔⴹ",
  "inviter":"Ɛarḍ,ⵄⴰⵔⴹ (ⵄⴰⵔⴺ)",
  "répéter":"Ɛawd,ⵄⴰⵡⴷ (ⵄⴰⵡⴸ)",
  "contrarier":"ƐeKes,ⵄⴽⵙ",
  "surveiller":"ƐeS,ⵄⵙ",
  "plaire":"Ɛjeb,ⵄⵊⴱ",
  "se nourrir":"Ɛteq,ⵄⵜⵇ",
  "être chéri":"ƐiZ,ⵄⵉⵣ",
  "séparer":"Ɛzer,ⵄⵣⵔ",
  "aider":"Ɛawn,ⵄⴰⵡⵏ",
  "se laver, se baigner":"ƐuM,ⵄⵓⵎ",
  "se blesser":"Yzem,ⵢⵣⵎ",
  "Jouer À La Trompette":"ẒeMer,ⵥⵎⵔ",
  "ramasser Du Bois":"Zdem,ⵣⴸⵎ",
  "se divertir":"Zhu,ⵣⵀⵓ",
  "se Régaler":"ZaRed,ⵣⴰⵔⴷ",
  "Rougir":"Zwegh,ⵣⵡⵖ",
  "s’étendre pour se reposer":"Ẓer,ⵥⵔ",
  "Être / Devenir Misérable":"Zreḍ,ⵣⵔⴹ",
  "mordre":"Zɛef,ⵣⵄⴼ",
  "secouer":"Zerz,ⵣⵔⵣ",
  "Contraindre / Serrer":"ZeYaṛ,ⵣⵢⴰⵕ",
  "rendre visite / Visiter":"Ẓur,ⵥⵓⵔ",
  "vendre":"Zenz,ⵣⵏⵣ",
  "pouvoir":"ZeMar,ⵣⵎⴰⵔ",
  "prier":"Zadj,ⵣⴰⴶ",
  "jeûner":"ẒuM,ⵥⵓⵎ",
"merch":"se marier,ⵎⴻⵔⵛ"

  };