window.dico2 = {
 "Prendre":"Agh,ⴰⵖ",
  "Sécher":"Azgh,ⴰⵣⵖ",
  "Être Accessible (prix)":"Arfeq,ⴰⵔⴼⵇ",
  "Être Bon Marché":"Arkhes,ⴰⵔⵅⵙ",
  "Se Fatiguer":"Aher,ⴰⵀⵔ",
  "S’enfuir":"Arwer,ⴰⵔⵡⴻⵔ",
  "Refuser":"Ag,ⴰⴳ",
  "S ‘éloigner":"Agwj,ⴰⴳⵡⵊ",
  "Revenir":"ArjeƐ,ⴰⵔⴷⵄ",
  "S’user/ Être Usé":"Archa,ⴰⵔⵛⴰ",
  "Se Pencher":"Adar,ⴰⴷⴰⵔ",
  "Courir":"Azer,ⴰⵣⵔ",
  "Entrer":"Adef,ⴰⴷⴼ",
  "Trouver":"Af,ⴰⴼ",
  "Apporter":"Awi,ⴰⵡⵉ",
  "Vider":"Ar,ⴰⵔ",
  "Prêter / Emprunter":"ArḌeri,ⴰⵔⴹⵔⵉ",
  "Endosser":"Arbu,ⴰⵔⴱⵓ",
  "Se Poser Se Percher (sur La Branche)":"Ars,ⴰⵔⵙ",
  "Ouvrir":"ArẒam,ⴰⵔⵥⴰⵎ",
  "Ajouter":"Arni,ⴰⵔⵏⵉ",
  "Écrire":"Ari,ⴰⵔⵉ",
  "Être Prés De":"Ades,ⴰⴷⵙ",
  "Venir":"As,ⴰⵙ",
  "Manger (+excès)":"Argheb,ⴰⵔⵖⴱ",
  "Enfanter":"Aru,ⴰⵔⵓ",
  "Prendre Le Petit Déjeuner":"Argheq,ⴰⵔⵖⵇ",
  "Casser":"ArẒ,ⴰⵔⵥ",
  "Puiser (eau)":"Ajam,ⴰⵊⴰⵎ",
  "Rentrer Chez Soi":"ArkuḤ,ⴰⵔⴽⵯⵃ",
  "Chercher":"Arzu,ⴰⵔⵣⵓ",
  "Croire":"Amen,ⴰⵎⵏ",
  "Donner Une Fortune":"Arzeq,ⴰⵔⵣⵇ",
  "Dépecer":"Azu,ⴰⵣⵓ",
  "Voler (biens D’autrui)":"Achar,ⴰⵛⴰⵔ",
  "Devoir (dettes)":"Ars,ⴰⵔⵙ",
  "Avoir Un Rapport Parenté":"As,ⴰⵙ",
  "Trembler":"Arjij,ⴰⵔⵊⵉⵊ",
  "Donner L’ordre":"AmaṚ,ⴰⵎⴰⵕ",
  "(se) Replier":"ArẒ ,ⴰⵔⵥ",
  "Avoir Mal Aux Yeux":"AḌen,ⴰⴹⵏ",
  "Accrocher":"Ajer,ⴰⵊⵔ",
  "(se) Salir":"Ames,ⴰⵎⵙ",
  "Être Au Courant…":"Argeb,ⴰⵔⴳⴱ",
  "Brûler":"Argh,ⴰⵔⵖ",
  "Mélanger":"AṚwi,ⴰⵕⵡⵉ",
  "Lâcher":"Arkhu,ⴰⵔⵅⵓ",
  "Accepter":"ArḌa,ⴰⵔⴹⴰ",
  "Arriver":"AWḌ,ⴰⵡⴹ",
  "En Avoir Assez":"AẒ,ⴰⵥ",
  "Garder (bétail)":"Arwes,ⴰⵔⵡⵙ",
  "Être Jaloux":"Assem,ⴰⵙⵎ",
  "Être Amer":"ArẒeg,ⴰⵔⵥⴳ",
  "Bénir":"ArḌa,ⴰⵔⴹⴰ",
  "Être / Devenir Mou":"ArḌab,ⴰⵔⴹⴰⴱ",
  "Tressaillir":"ArmiMi,ⴰⵔⵎⵉⵎⵉ",
  "Triompher":"Arna,ⴰⵔⵏⴰ",
  "Vomir":"AṚ,ⴰⵕ",
  "Pointer":"AṚcham,ⴰⵕⵛⴰⵎ",
  "Être Content":"AṚcheq,ⴰⵕⵛⵇ",
  "Se Mettre Dans Un Coin":"ArKen,ⴰⵔⴽⴰⵏ",
  "Donner Des Coups De Pieds":"Archer,ⴰⵔⵛⵔ",
  "Grincer (les Dent)":"ARugses,ⴰⵔⵓⴳⵙⴻⵙ",
  "Eparpiller":"ArDej,ⴰⵔⴷⴻⵊ",
  "Se Rendre Compte":"Acha,ⴰⵛⴰ",
  "Acheter Des Céréales":"Aju,ⴰⵊⵓ",
  "Se Reposer / Rester Calme":"ArYeḤ,ⴰⵔⵢⵃ",
  "Piquer (âne)":"Achem,ⴰⵛⵎ",
  "Être Profond":"Adjegh,ⴰⴶⵖ",
  "Monter":"Ari,ⴰⵔⵉ",
  "Obliger À…":"BeZez,ⴱⵣⴻⵣ",
  "Dépasser L’âge Du Mariage":"Bur,ⴱⵓⵔ",
  "Doubler Un Tissu":"BeṬen,ⴱⵟⵏ",
  "Être Très Tendre":"Bzuzi,ⴱⵣⵓⵣⵉ",
  "Manquer (travail)":"BaṬer,ⴱⴰⵟⵔ",
  "Être Usés (habits)":"Buri,ⴱⵓⵔⵉ",
  "Se Plaindre":"Bara,ⴱⴰⵔⴰ",
  "S’affaisser":"Barch,ⴱⴰⵔⵛ",
  "Se Ceundre":"Byes,ⴱⵢⵙ",
  "Moudre En Grosses Graines":"Bri,ⴱⵔⵉ",
  "Eventrer":"BƐeẒ,ⴱⵄⵥ",
  "S’èloigner":"BaƐed,ⴱⴰⵄⴷ",
  "Enfoncer":"BeẒ,ⴱⵥ",
  "Changer":"BeDer,ⴱⴷⵔ",
  "Construire":"Bna,ⴱⵏⴰ",
  "Remplir (+excès)":"Beghbegh,ⴱⵖⴱⵖ",
  "Entamer":"BdeƐ ,ⴱⴷⵄ",
  "Annoncer Une Bonne Nouvelle":"BechaṚ,ⴱⵛⴰⵕ",
  "Déshonorer":"Bahter,ⴱⴰⵀⵜⵔ",
  "Coller Avec Force":"BeqaḌ,ⴱⵇⴰⴹ",
  "Placer Dans Une Cachette":"Bar,ⴱⴰⵔ",
  "Epurer La Laine":"Barwer,ⴱⴰⵔⵡⵔ",
  "Se Mettre Debout":"BeD,ⴱⴷ",
  "Noircir /Être Noir":"Barchene,ⴱⴰⵔⵛⵏ",
  "Devenir Fou":"Buhri,ⴱⵓⵀⵔⵉ",
  "Etouffer":"Bukhsi,ⴱⵓⵅⵙⵉ",
  "Sourire Timidement":"BiSem,ⴱⵉⵙⵎ",
  "Être / Devenir Enroué":"BuybeḤ,ⴱⵓⵢⴱⵃ",
  "Être Avare":"Bkher,ⴱⵅⵔ",
  "Être Pubère":"Bregh,ⴱⵔⵖ",
  "Regarder (+ Étonnement)":"Beheg,ⴱⵀⴳ",
  "Être Trop Mouillé":"Bejbej,ⴱⵊⴱⵊ",
  "Bâter":"BardeƐ,ⴱⴰⵔⴷⵄ",
  "Se Rouler Par Terre":"BarkikeḌ,ⴱⴰⵔⴽⵉⴽⴹ",
  "Crier (en Public)":"BareḤ,ⴱⴰⵔⵃ",
  "Faire Le Fier-À-Bras":"BaṚen,ⴱⴰⵕⵏ",
  "Être Muet / Muselé":"BKem,ⴱⴽⵎ",
  "Se Fâcher":"BaReq,ⴱⴰⵔⵇ",
  "(ap) Paraître":"Ḍehar,ⴹⵀⴰⵔ",
  "Retourner / (revenir)":"Dwer,ⴷⵡⵔ",
  "Vivre":"Dar,ⴷⴰⵔ",
  "Grater Les Cordes D’une Guitar":"Denden,ⴷⴻⵏⴷⴻⵏ",
  "Cheminer Lentement":"Darej,ⴷⴰⵔⵊ",
  "Se Cacher":"DuRi,ⴷⵓⵔⵉ",
  "Galoper":"DaƐlak,ⴷⴰⵄⵍⴰⴽ",
  "Suer":"Ded,ⴷⴻⴷ",
  "Durer":"Dum,ⴷⵓⵎ",
  "Bouder":"Ḍiq,ⴹⵉⵇ",
  "Être / Devenir Fragile":"ḌƐef,ⴹⵄⴼ",
  "Réparer Les Chaussures":"Ḍaref,ⴹⴰⵔⴼ",
  "Dresser (animal)":"ḌweƐ,ⴹⵡⵄ",
  "Boire D’un Seul Trait":"Dardar,ⴷⴰⵔⴷⴰⵔ",
  "Bousculer":"DaRem,ⴷⴰⵔⵎ",
  "Suivre":"Ḍfar,ⴹⴼⴰⵔ",
  "Faire Du Mal":"ḌaR,ⴹⴰⵔ",
  "Voler (ailes)":"Ḍu,ⴹⵓ",
  "Garantir":"Ḍmen,ⴹⵎⵏ",
  "Parvenir":"Dark,ⴷⴰⵔⴽ",
  "Appeler À La Prière":"Den,ⴷⵏ",
  "Construire Un Toit":"Ḍarz,ⴹⴰⵔⵣ",
  "Meurtrir":"Degdeg,ⴷⴳⴷⴳ",
  "Se Débrouiller":"ḌeBar,ⴹⴱⴰⵔ",
  "Convoiter":"ḌmeƐ,ⴹⵎⵄ",
  "Se Rouiler":"Dra,ⴷⵔⴰ",
  "Descendre":"Ḍar,ⴹⴰⵔ",
  "Préserver":"DƐem,ⴷⵄⵎ",
  "Attacher\n(+ Paître)":"ḌeweṚ,ⴹⵡⵕ",
  "(se) Perdre":"ḌaYeƐ,ⴹⴰⵢⵄ",
  "Mettre Une Matière Grasse":"Dhen,ⴷⵀⵏ",
  "S’éloigner":"ḌaReq,ⴹⴰⵔⵇ",
  "Faire Un Acte Maladroit":"Dfech,ⴷⴼⵛ",
  "Battre Les Cartes":"ḌmeṢ,ⴹⵎⵚ",
  "(re) Couvrir":"Der,ⴷⵔ",
  "Donner Un Coup":"Dkhem,ⴷⵅⵎ",
  "Rendre Responsable":"DeNa,ⴷⵏⴰ",
  "Introduire Dans Le Four":"Ḍarkh,ⴹⴰⵔⵅ",
  "Repousser":"DeMer,ⴷⵎⵔ",
  "Devenir Sourd":"Duhcher,ⴷⵓⵀⵛⵔ",
  "Être Glacés De Froid (pieds)":"DuBez,ⴷⵓⴱⵣ",
  "Détonner":"DarḌeq,ⴷⴰⵔⴹⵇ",
  "Exploser":"DeƐdeƐ,ⴷⵄⴷⵄ",
  "Préparer Une Purée De Fèves":"Ḍarz TamṚaqt,ⴹⴰⵔⵣ ⵜⴰⵎⵕⴰⵇⵜ",
  "Rire":"ḌḤech,ⴹⵃⵛ",
  "Avoir Bon Goût":"Ḍab,ⴹⴰⴱ",
  "Plier":"Ḍfes,ⴹⴼⵙ",
  "(re) Tourner":"Ḍarn,ⴹⴰⵔⵏ",
  "Être Charmant":"Ḍarf,ⴹⴰⵔⴼ",
  "Être / Devenir Aveugle":"Ḍarger,ⴹⴰⵔⴳⵔ",
  "Se Brûler /avoir Trop Chaud":"DƐeq,ⴷⵄⵇ",
  "Se Précipiter Sur":"DaRech,ⴷⴰⵔⵛ",
  "Être Lourd":"Dqer,ⴷⵇⵔ",
  "Devenir":"Deḥa,ⴷⵃⴰ",
  "Travailler Le Cuir":"Dbegh,ⴷⴱⵖ",
  "Retourner La Terre":"Fars,ⴼⴰⵔⵙ",
  "Loucher":"FaryeḌ,ⴼⴰⵔⵢⴹ",
  "Se Rétablir":"Faja,ⴼⴰⵊⴰ",
  "Distinguer":"Farz,ⴼⴰⵔⵣ",
  "Se Casser En Mille Morceaux":"FtuTes,ⴼⵜⵓⵜⵙ",
  "Grelotter":"Frires,ⴼⵔⵉⵔⵙ",
  "Attraper Le Fou-Rire":"Farkikeḥ,ⴼⴰⵔⴽⵉⴽⵃ",
  "Bâcler":"Farfech,ⴼⴰⵔⴼⵛ",
  "Nager":"FteḤ,ⴼⵜⵃ",
  "Devenir Léger":"Fses,ⴼⵙⴻⵙ",
  "Nettoyer La Laine":"Fsu,ⴼⵙⵓ",
  "Mettre À Sécher":"Fsar,ⴼⵙⴰⵔ",
  "Être Gâté (enfant)":"FcheḤ,ⴼⵛⴻⵃ",
  "Se Lever À L’aube":"Fejar,ⴼⵊⴰⵔ",
  "Tâtonner":"Fafa,ⴼⴰⴼⴰ",
  "S’envoler":"Farfar,ⴼⴰⵔⴼⴰⵔ",
  "Se Distraire":"FuRej,ⴼⵓⵔⵊ",
  "Libérer":"FeK,ⴼⴽ",
  "Tailler / Découper":"FeṢer,ⴼⵚⵔ",
  "Découdre":"Fteq,ⴼⵜⵇ",
  "Verser":"FaRegh,ⴼⴰⵔⵖ",
  "Rouler Du Couscous":"Fter,ⴼⵜⵔ",
  "Détacher":"Fsy,ⴼⵙⵢ",
  "Penser":"FeKeṚ,ⴼⴽⵕ",
  "Dévoyer":"Feles,ⴼⵍⵙ",
  "Déchirer D’un Seul Coup":"Fri,ⴼⵔⵉ",
  "Déjeuner":"FḌar,ⴼⴹⴰⵔ",
  "Balayer":"FarḌ,ⴼⴰⵔⴹ",
  "Cuire À La Vapeur":"FeWaṚ,ⴼⵡⴰⵕ",
  "Comprendre":"Fhem,ⴼⵀⵎ",
  "Inspecter":"FeṬech,ⴼⵟⵛ",
  "Dévoiler":"F ḌeḤ,ⴼⴹⵃ",
  "Trier / Nettoyer":"Farn,ⴼⴰⵔⵏ",
  "Mâcher":"FeẒ,ⴼⵥ",
  "Manquer De Pudeur":"Fuhart,ⴼⵓⵀⴰⵔⵜ",
  "Se Déverser":"FeYeḌ,ⴼⵢⴻⴹ",
  "S’essouffler":"FqiQas,ⴼⵇⵉⵇⴰⵙ",
  "Être / Devenir Tordu":"Fargh,ⴼⴰⵔⵖ",
  "Se Lasser":"Fcher,ⴼⵛⵔ",
  "Avoir Soif":"Fad,ⴼⴰⴷ",
  "Diviser":"Farq,ⴼⴰⵔⵇ",
  "Sortir De La Coquille":"Fruri,ⴼⵔⵓⵔⵉ",
  "Eclater":"Fekhs,ⴼⵅⵙ",
  "Avoir Bonne Mine":"FuNek,ⴼⵓⵏⴽ",
  "Mourir / Être Épuisé":"Fna,ⴼⵏⴰ",
  "Sortir":"Fegh,ⴼⵖ",
  "Se Réveiller":"Faq,ⴼⴰⵇ",
  "(se) Cacher":"Far,ⴼⴰⵔ",
  "S’avérer":"Fu,ⴼⵓ",
  "Pratiquer L’agriculture":"FadjeḤ,ⴼⴰⴶⵃ",
  "Croire / Sembler":"Ghir,ⵖⵉⵔ",
  "S’éclipser / Être Avalé":"Ghri,ⵖⵔⵉ",
  "Sombrer":"GhḌes,ⵖⴹⵙ",
  "Avoir Mauvaise Mine":"GhaYaṚ,ⵖⴰⵢⴰⵕ",
  "Pousser\n(plantes)":"Ghmi,ⵖⵎⵉ",
  "Avoir Faim":"DjaẒ,ⴶⴰⵥ",
  "Guérir":"Genfa,ⴳⵏⴼⴰ",
  "Être Épais":"GdaṚ,ⴳⴷⴰⵕ",
  "Couler":"Gharq,ⵖⴰⵔⵇ",
  "Disparaître":"Ghab,ⵖⴰⴱ",
  "Déménager":"Gaj,ⴳⴰⵊ",
  "Trahir":"Ghdar,ⵖⴷⴰⵔ",
  "Se Régaler":"GheBa,ⵖⴱⴰ",
  "Compenser":"Gharm,ⵖⴰⵔⵎ",
  "Grignoter":"GheẒ,ⵖⵥ",
  "Tamiser":"Gharber,ⵖⴰⵔⴱⵔ",
  "Faire/mettre / Être":"G,ⴳ",
  "Reprocher":"Djem,ⴶⵎ",
  "Étudier / Lire":"Ghar,ⵖⴰⵔ",
  "Guider":"GeWed,ⴳⵡⴷ",
  "Creuser":"Ghez,ⵖⵣ",
  "Tricher":"Ghech,ⵖⵛ",
  "Faire Tomber":"GhḌer,ⵖⴹⵔ",
  "(Se ) Relever":"GaƐed,ⴳⴰⵄⴷ",
  "Cligner De L’oeil":"Ghmez,ⵖⵎⵣ",
  "Corriger Quelq’un (mérite)":"Ghzu,ⵖⵣⵓ",
  "Mettre En Prison":"GheYes,ⵖⵢⵙ",
  "Avoir Peur":"Gwed,ⴳⵡⴷ",
  "Se Révolter":"GheWegh,ⵖⵡⵖ",
  "Manger Plus De Pain":"GeWez,ⴳⵡⵣ",
  "Déchirer":"Ghars,ⵖⴰⵔⵙ",
  "Pétrir":"Gw,ⴳⵡ",
  "Égorger":"Ghars,ⵖⴰⵔⵙ",
  "Divorcer":"Djef,ⴶⴼ",
  "Faire Des Présages":"GeZen,ⴳⵣⵏ",
  "Se Hâter":"Ghawer,ⵖⴰⵡⵔ",
  "Avorter":"Ghry,ⵖⵔⵢ",
  "Piller":"GecheḌ,ⴳⵛⴹ",
  "Chanter":"GheNej,ⵖⵏⵊ",
  "Gagner":"Ghreb,ⵖⵔⴱ",
  "Avaler En Grandes Quantités":"Gharghar,ⵖⴰⵔⵖⴰⵔ",
  "Secourir":"Ghat,ⵖⴰⵜ",
  "Se Fouler Le Pied":"Djaghzem,ⴶⴰⵖⵣⵎ",
  "Boire À Tire-Larigot":"Gargeb,ⴳⴰⵔⴳⴱ",
  "Être Distrait":"Ghfer,ⵖⴼⵔ",
  "Dégringoler":"HruBez,ⵀⵔⵓⴱⵣ",
  "Lyncher":"Hicher,ⵀⵉⵛⵔ",
  "Érrer":"Hum,ⵀⵓⵎ",
  "S’habiller Élégamm-Ent":"HeẒet,ⵀⵥⵜ",
  "Couler À Flots (eau)":"Harhar,ⵀⴰⵔⵀⴰⵔ",
  "Arriver (lieu)":"KhḌer,ⵅⴹⵔ",
  "Vouloir":"Khes,ⵅⵙ",
  "(se) Limiter":"Ḥed,ⵃⴷ",
  "Retirer Brusquement":"KhḌef,ⵅⴹⴼ",
  "Avoir Besoin":"Ḥdej,ⵃⴷⵊ",
  "Brûler Vivement":"Ḥdeq,ⵃⴷⵇ",
  "Compatir":"Ḥin,ⵃⵉⵏ",
  "Obetenir Sa Part":"Ḥart,ⵃⴰⵔⵜ",
  "Surveiller":"ḤḌa,ⵃⴹⴰ",
  "Être Chaud":"Ḥma,ⵃⵎⴰ",
  "Être Étroit / Bloquer Le Passage":"Ḥsar,ⵃⵙⴰⵔ",
  "Frissonner":"ḤtiTi,ⵃⵜⵉⵜⵉ",
  "Vagabonder":"ḤaḤa,ⵃⴰⵃⴰ",
  "Chasser Les Mouches":"ḤaReb,ⵃⴰⵔⴱ",
  "Avoir Des Soucis":"ḤiSef,ⵃⵉⵙⴼ",
  "Glisser Entre Les Mains":"ḤruṬef,ⵃⵔⵓⵟⴼ",
  "Boiter":"ḤiḌar,ⵃⵉⴹⴰⵔ",
  "S’écarter":"ḤaYed,ⵃⴰⵢⴻⴷ",
  "Laisser":"Hta,ⵀⵜⴰ",
  "Compter":"Ḥseb,ⵃⵙⴱ",
  "Couper De L’herbe":"Ḥtech,ⵃⵜⵛ",
  "(se) Raser":"ḤeF,ⵃⴼ",
  "Jeter Qq. Chose Violement":"Ḥri,ⵃⵔⵉ",
  "Embêter":"Hwer,ⵀⵡⵔ",
  "Casser En Petits Morceaux":"Hechem,ⵀⵛⵎ",
  "Donner Un Supplément":"HeDaṚ,ⵀⴷⴰⵕ",
  "Gâcher / Renier":"ḤaRem,ⵃⴰⵔⵎ",
  "Ramasser Du Bois":"Ḥarwech,ⵃⴰⵔⵡⵛ",
  "Envier":"Ḥsed,ⵃⵙⴷ",
  "Obliger":"ḤeTem,ⵃⵜⵎ",
  "Ramasser Vite":"Ḥru,ⵃⵔⵓ",
  "Dire / Faire Des Bêtises":"HeGar,ⵀⴳⴰⵔ",
  "Remuer":"ḤaRech,ⵃⴰⵔⵛ",
  "Enduire":"ḤeNech,ⵃⵏⵛ",
  "Menacer":"HuD,ⵀⵓⴷ",
  "Jeter Des Pierres":"Ḥejar,ⵃⵊⴰⵔ",
  "Frictionner":"Ḥek,ⵃⴽ",
  "Tirer Le Sceau Du Puits":"Ḥreb,ⵃⵔⴱ",
  "Niveler La Terre":"ḤeMaṚ,ⵃⵎⴰⵕ",
  "Demander En Mariage":"KhḌeb,ⵅⴹⴱ",
  "Gouverner / Toucher":"Ḥkem,ⵃⴽⵎ",
  "Remplacer":"Khref,ⵅⵔⴼ",
  "Circoncire":"Khten,ⵅⵜⵏ",
  "Être Métayer":"KheMes,ⵅⵎⵙ",
  "Esquiver":"Khnes,ⵅⵏⵙ",
  "Travailler":"Khdem,ⵅⴷⵎ",
  "Se Tromper":"KhḌa,ⵅⴹⴰ",
  "Moudre":"Ḥri,ⵃⵔⵉ",
  "Rattraper":"Ḥart,ⵃⴰⵔⵜ",
  "Faire Attention":"Ḥawr,ⵃⴰⵡⵔ",
  "Être En Crue (rivière)":"Ḥmer,ⵃⵎⵔ",
  "Être Pris / Coincé":"ḤṢer,ⵃⵚⵔ",
  "Se Lancer":"HuB,ⵀⵓⴱ",
  "Tourner Autour De":"Ḥrara,ⵃⵔⴰⵔⴰ",
  "Être Enroulé Dans Un Tissu":"ḤnuNeḌ,ⵃⵏⵓⵏⴹ",
  "Ramper / Glisser":"Ḥrurd,ⵃⵔⵓⵔⴷ",
  "Être / Devenir Mécontent":"KheYeq,ⵅⵢⵇ",
  "Inquiéter":"Khewej,ⵅⵡⵊ",
  "Confisquer":"ḤeWes,ⵃⵡⵙ",
  "Cafouiller":"KharweḌ,ⵅⴰⵔⵡⴹ",
  "Apprendre":"ḤfeḌ,ⵃⴼⴹ",
  "Être Dans Le Besoin":"ḤeWej,ⵃⵡⵊ",
  "Remercier Dieu":"Ḥmed,ⵃⵎⴷ",
  "Démolir":"Hdem,ⵀⴷⵎ",
  "Limiter":"ḤeD,ⵃⴷ",
  "Frapper Brusquement":"KhbeḌ,ⵅⴱⴹ",
  "Arracher":"KhḌef,ⵅⴹⴼ",
  "Prendre Sa Part":"Ḥuz,ⵃⵓⵣ",
  "Paître":"Hda,ⵀⴷⴰ",
  "Toucher":"Ḥada,ⵃⴰⴷⴰ",
  "Payer":"KhedjeṢ,ⵅⴶⵚ",
  "Cacher":"KheMer,ⵅⵎⵔ",
  "Être Déréglé":"Khsar,ⵅⵙⴰⵔ",
  "Griffer":"Khbech,ⵅⴱⵛ",
  "Perdre":"Khsar,ⵅⵙⴰⵔ",
  "(faire) Tourner":"ḤeNeḌ,ⵃⵏⴹ",
  "Créer Le Désordre":"HarweḌ,ⵀⴰⵔⵡⴹ",
  "Coudre":"KheYeḌ,ⵅⵢⴻⴹ",
  "Regarder":"Khzar,ⵅⵣⴰⵔ",
  "Avoir Des Hallucinations":"Khayer,ⵅⴰⵢⵔ",
  "Maudire":"Khza,ⵅⵣⴰ",
  "Mettre Au Dépôt":"Khzen,ⵅⵣⵏ",
  "Faire Choisir":"KheyaṚ,ⵅⵢⴰⵕ",
  "Soulever":"HeZ,ⵀⵣ",
  "Briser":"HaRem,ⵀⴰⵔⵎ",
  "Être Enfin Prêt":"ḤeZem,ⵃⵣⵎ",
  "Glisser":"ḤrudjeḌ,ⵃⵔⵓⴶⴹ",
  "Être Présent":"ḤḌar,ⵃⴹⴰⵔ",
  "Être Facile":"Hwen,ⵀⵡⵏ",
  "Ne Pas Supporter":"Ḥmer,ⵃⵎⵔ",
  "Rougir (peau)":"HaRa,ⵀⴰⵔⴰ",
  "Cogiter":"KhaRaṢ,ⵅⴰⵔⴰⵚ",
  "S’écrouler":"Hrura,ⵀⵔⵓⵔⴰ",
  "(se) Brûler":"Ḥraq,ⵃⵔⴰⵇ",
  "Naître":"Khreq,ⵅⵔⵇ",
  "Être / Devenir Rond":"ḤnuNi,ⵃⵏⵓⵏⵉ",
  "Réfléchir":"Hendez,ⵀⵏⴷⵣ",
  "Se Faire":"Khreq,ⵅⵔⴻⵇ",
  "Planter":"Ẓu,ⵥⵓ",
  "Falloir / Manquer":"KheṢ,ⵅⵚ",
  "Être / Exister":"Iri,ⵉⵔⵉ",
  "Être Cher (objets)":"Ighra,ⵉⵖⵔⴰ",
  "Se Faner":"ISraw,ⵉⵙⵔⴰⵡ",
  "Être Large":"Iriw,ⵉⵔⵉⵡ",
  "Choisir":"IkhḌar,ⵉⵅⴹⴰⵔ",
  "Avoir Des Envies":"Init,ⵉⵏⵉⵜ",
  "S’habiller":"IrḌ,ⵉⵔⴹ",
  "Jouer":"Irar,ⵉⵔⴰⵔ",
  "Dire":"Ini,ⵉⵏⵉ",
  "Être Filtré / Tamisé":"Ifif,ⵉⴼⵉⴼ",
  "Évoquer":"Idar,ⵉⴷⴰⵔ",
  "Être Lavé":"Irid,ⵉⵔⵉⴷ",
  "Être Délicieux":"IziḌ,ⵉⵣⵉⴹ",
  "Être Propre":"Izdeg,ⵉⵣⴷⴳ",
  "Peser Les Céréales":"IzeḌ,ⵉⵣⴹ",
  "Devancer":"Izar,ⵉⵣⴰⵔ",
  "Surpasser":"If / Uf,ⵉⴼ,ⴼ",
  "Mourir (non-Lusulman)":"Jef,ⵊⴼ",
  "Donner Naissance":"J (d),ⵊ,(ⴷ)",
  "Peindre Les Murs (chaux)":"JeYar,ⵊⵢⴰⵔ",
  "Être / Devenir Muet":"Jnew,ⵊⵏⵡ",
  "Geler":"Jres,ⵊⵔⵙ",
  "Jurer":"Jadj,ⵊⴰⴶ",
  "Ne Pas Prendre (plantes)":"JaReḤ,ⵊⴰⵔⵃ",
  "Devenir Granuleux":"Jben,ⵊⴱⵏ",
  "Réunir / Accumuler":"Jru,ⵊⵔⵓ",
  "Faire La Guerre Sainte":"Jahed,ⵊⴰⵀⴷ",
  "Pousser ( Humains)":"Jma,ⵊⵎⴰ",
  "Passer La Serpilliére":"Jef,ⵊⴼ",
  "Répartir Les Cartes":"JaRa,ⵊⴰⵔⴰ",
  "Essayer":"JaṚeb,ⵊⴰⵕⴱ",
  "Être Dernier":"Jura,ⵊⵓⵔⴰ",
  "Être Gelé":"Jmed,ⵊⵎⴷ",
  "Regarder (+ Surprise)":"JƐaṚ,ⵊⵄⴰⵕ",
  "Crier Fort":"JeƐjeƐ,ⵊⵄⵊⵄ",
  "Tirer":"Jbed,ⵊⴱⴷ",
  "Ramasser":"Jru,ⵊⵔⵓ",
  "Entraîner":"JaṚ,ⵊⴰⵕ",
  "Mijoter":"JeMaṚ,ⵊⵎⵕ",
  "Réparer":"JbaṚ,ⵊⴱⵕ",
  "Étrangler":"JeYef,ⵊⵢⴼ",
  "Laper":"Jer,ⵊⵔ",
  "Gazouiller":"Jaw,ⵊⴰⵡ",
  "Boire D’une Seul Gorgée":"Jghem,ⵊⵖⵎ",
  "Pécher / Chasser":"Jmar,ⵊⵎⴰⵔ",
  "Être Fort":"Jhed,ⵊⵀⴷ",
  "Se Rassasier":"Jiwen,ⵊⵉⵡⵏ",
  "Se Lever":"Kar,ⴽⴰⵔ",
  "Se Maquiller (les Yeux)":"KeḤer,ⴽⵃⵔ",
  "Geler / Être Gelé":"Kuchem,ⴽⵓⵛⵎ",
  "Se Recroqueviller":"KuMech,ⴽⵓⵎⵛ",
  "Ricaner":"KeḤkeḤ,ⴽⵃⴽⵃ",
  "Être Crépu":"KarnuNi,ⴽⴰⵔⵏⵓⵏⵉ",
  "S’rsclaffer":"KeƐkeƐ,ⴽⵄⴽⵄ",
  "Enlever":"Kes,ⴽⵙ",
  "Dévaliser":"KecheḌ,ⴽⵛⴹ",
  "Charger Quelqu’un De Quelque Chose":"KeLef,ⴽⵍⴼ",
  "Couvrir D’un Linceul":"KeFen,ⴽⴼⵏ",
  "Terminer":"KeMer,ⴽⵎⵔ",
  "Bien Traiter Quelqu’un":"KeBaṚ,ⴽⴱⴰⵕ",
  "Fumer":"KeYef,ⴽⵢⴼ",
  "Tenir Bon":"Kabar,ⴽⴰⴱⴰⵔ",
  "Perdre Sa Couleur":"Kchef,ⴽⵛⴼ",
  "Deviner":"Kachef,ⴽⴰⵛⴼ",
  "Démentir":"KeDeb,ⴽⴷⴱ",
  "Saigner Du Nez":"Kunzar,ⴽⵓⵏⵣⴰⵔ",
  "Jouir":"KuKeḌ,ⴽⵓⴽⴹ",
  "Mettre À L’excès":"KeTar,ⴽⵜⴰⵔ",
  "Gâter":"KeFes,ⴽⴼⵙ",
  "Être Entamé (pain)":"Ku Ṭef,ⴽⵓⵟⴼ",
  "Briller (multicolore)":"Lulech,ⵍⵓⵍⵛ",
  "Prononcer “Allah”":"Lehleh,ⵍⵀⵍⵀ",
  "(se) Peigner":"McheḌ,ⵎⵛⴹ",
  "Grandir":"MghaṚ,ⵎⵖⴰⵕ",
  "Être Petit / Rapetisser":"MẒy,ⵎⵥⵢ",
  "Avoir Une Bonne Santé":"MneƐ,ⵎⵏⵄ",
  "Mourir":"Met,ⵎⵜ",
  "Ramper":"Mudjegh,ⵎⵓⴶⵖ",
  "Être Houleux / Tourner (tête)":"Muj,ⵎⵓⵊ",
  "Avancer À 4 Pattes":"Murd,ⵎⵓⵔⴷ",
  "Mourir Asphyxié":"MurḌes,ⵎⵓⵔⴹⵙ",
  "S’étendre À Même Le Sol":"MaReḤ,ⵎⴰⵔⵃ",
  "Malmener":"Mermed,ⵎⵔⵎⴷ",
  "Accompagner":"Mun,ⵎⵓⵏ",
  "Effacer":"MḤa,ⵎⵃⴰ",
  "Essuyer":"MseḤ,ⵎⵙⵃ",
  "Moissonner":"Mjar,ⵎⵊⴰⵔ",
  "Comparer":"MeTer,ⵎⵜⵔ",
  "Attacher Solidement":"MḤeḌ,ⵎⵃⴹ",
  "Dîner":"Munsu,ⵎⵓⵏⵙⵓ",
  "(faire) Souffrir":"MeḤen,ⵎⵃⵏ",
  "Se Marier":"Mrech,ⵎⵔⵛ",
  "(se) Pencher":"MeYer,ⵎⵢⵔ",
  "Manquer De Sel":"Mses,ⵎⵙⴻⵙ",
  "Être Enragé":"MuZar,ⵎⵓⵣⴰⵔ",
  "Se Déplacer":"MuṬi,ⵎⵓⵟⵉ",
  "Devenir Ami":"Mduker,ⵎⴷⵓⴽⵔ",
  "Être Égaux":"MquDa,ⵎⵇⵓⴷⴰ",
  "Se Rencontrer":"Msagar,ⵎⵙⴰⴳⴰⵔ",
  "Tresser":"Mud,ⵎⵓⴷ",
  "Battre Fortement":"Marḥ,ⵎⴰⵔⵃ",
  "(se) Fatiguer":"MaRat,ⵎⴰⵔⴰⵜ",
  "Être / Devenir Blanc":"Mrer,ⵎⵔⴻⵔ",
  "Être Salé":"Mreḥ,ⵎⵔⵃ",
  "Avoir Mal À La Tête":"Mrudji,ⵎⵔⵓⴶⵉ",
  "Frotter":"Msed,ⵎⵙⴷ",
  "Frapper À La Tête (sang)":"Marz,ⵎⴰⵔⵣ",
  "Être Solide":"Mten,ⵎⵜⵏ",
  "Se Quereller (femme)":"MchuBech,ⵎⵛⵓⴱⵛ",
  "Se Disputer Debout\n(hommes)":"MughẒer,ⵎⵓⵖⵥⵔ",
  "Être Difficile":"Mra,ⵎⵔⴰ",
  "Se Moquer":"Marḍen,ⵎⴰⵔⴹⵏ",
  "Perdre Le Nord":"Mhafa,ⵎⵀⴰⴼⴰ",
  "Être Imperméable\n(farine)":"Meja,ⵎⵊⴰ",
  "Être Trituré":"Nghed,ⵏⵖⴷ",
  "Être Déplumé":"Nchef,ⵏⵛⴼ",
  "Mûrir (fruits)":"Nḍy,ⵏⴹⵢ",
  "Avoir L’intention":"Nwa,ⵏⵡⴰ,ⵏⵓⴰ",
  "S’infiltrer Naturellement":"NeS,ⵏⵙ",
  "Faire Nuit":"Ndeṛ\nṬram,ⵏⴷⵕ ⵟⵔⴰⵎ",
  "Être Exténué":"Nzef,ⵏⵣⴼ",
  "Se Griffer Le Visage":"Ndeb,ⵏⴷⴱ",
  "Mordre Goulûment":"Nhech,ⵏⵀⵛ",
  "Se Vexer":"Ndqaṛ,ⵏⴷⵇⴰⵕ",
  "Secouer Pour Nettoyer":"Nfaḍ,ⵏⴼⴰⴹ",
  "Sursauter":"Nekhfeḍ,ⵏⵅⴼⴹ",
  "Déambuler":"Neḍ,ⵏⴹ",
  "Se Délier":"Nufsar,ⵏⵓⴼⵙⴰⵔ",
  "Enlever Les Tâches":"Nqeḍ,ⵏⵇⴹ",
  "Couvrir / Enterrer":"Nt,ⵏⵜ",
  "(Se) Tordre (pieds)":"Neɛqaṛ,ⵏⵄⵇⴰⵕ",
  "Être Baratté":"Ndu,ⵏⴷⵓ",
  "Avaler De Travers":"Nezreq,ⵏⵣⵔⵇ",
  "Osciller":"Neyrur,ⵏⵢⵔⵓⵔ",
  "Coûter":"Nqam,ⵏⵇⴰⵎ",
  "Rendre Visite":"Newju,ⵏⵡⵊⵓ",
  "Prendre Peur":"NekhreƐ,ⵏⵅⵔⵄ",
  "Se Sauver (de Peur)":"Nejref,ⵏⵊⵔⴼ",
  "S’égarer":"Nejra,ⵏⵊⵔⴰ",
  "Se Lever\n(soleil)":"Nqaṛ,ⵏⵇⴰⵕ",
  "Se Désister":"Nqar,ⵏⵇⴰⵔ",
  "Gronder":"Nhem,ⵏⵀⵎ",
  "Perdre Quelqu’un De Proche":"Nury,ⵏⵓⵔⵉ",
  "Renier":"NKeṛ,ⵏⴽⵕ",
  "Fleurir":"NeWaṛ,ⵏⵡⴰⵕ,ⴰⵔ",
  "Trimer":"Nber,ⵏⴱⵔ (ⵏⴲⵔ)",
  "Pleuvoir En Fine Gouttes":"Nefnef,ⵏⴼⵏⴼ",
  "Scier":"Njaṛ,ⵏⵊⴰⵕ",
  "Sauter":"Ngez,ⵏⴳⵣ",
  "Être Cuit":"Nw,ⵏⵡ",
  "Sangloter":"Nikhsis,ⵏⵉⵅⵙⵉⵙ",
  "Enterrer":"Nḍer,ⵏⴹⵔ",
  "Dresser Un Piège":"Ndi,ⵏⴷⵉ",
  "Somnoler":"Nudem,ⵏⵓⴷⵎ",
  "Avouer":"Nɛem,ⵏⵄⵎ",
  "Dissuader":"Nha,ⵏⵀⴰ",
  "Aviser":"NeBeh,ⵏⴱⵀ",
  "Jeter":"Nḍar,ⵏⴹⴰⵔ",
  "Être Mal Élevé":"Ndsaṛ,ⵏⴷⵙⴰⵕ",
  "Echanger / Transposer":"Neqer,ⵏⵇⵔ",
  "Taquiner":"Nbech,ⵏⴱⵛ",
  "Exiler":"Nfa,ⵏⴼⴰ",
  "Picorer":"Nqeb,ⵏⵇⴱ",
  "Réprimer":"Nqem,ⵏⵇⵎ",
  "Parler D’une Voix Nasillarde":"Neghnegh,ⵏⵖⵏⵖ",

  "Être Bien Battu (blé)":"Nghed,ⵏⵖⴷ",
  "Parler / Dire":"Nḍeq,ⵏⴹⵇ",
  "Passer La Nuit":"Ns,ⵏⵙ",
  "Se Sauver":"Njem,ⵏⵊⵎ",
  "Tirer Brusquement":"Nder,ⵏⴷⵔ",
  "Regretter":"Ndem,ⵏⴷⵎ",
  "Être Utile":"Nfeɛ,ⵏⴼⵄ",
  "S’habituer":"Nam,ⵏⴰⵎ",
  "Diminuer":"Nqes,ⵏⵇⵙ",
  "S’apprêter À":"Nawr,ⵏⴰⵡⵔ",
  "S’en Aller / Marcher":"Ujur,ⵓⵊⵓⵔ",
  "Être Haut / Aller Vers Le Haut":"Uɛra,ⵓⵄⵔⴰ",
  "Tousser":"Usu,ⵓⵙⵓ",
  "Être Mouillé":"UF,ⵓⴼ",
  "Être Gonflé":"UF,ⵓⴼ",
  "Griller (grains)":"Urf,ⵓⵔⴼ",
  "(monde) Toucher À Sa Fin":"UQa,ⵓⵇⴰ",
  "Rêver":"Urja,ⵓⵔⵊⴰ",
  "S’insurger":"UMugh,ⵓⵎⵓⵖ",
  "Se Faire Rare":"Udrus,ⵓⴷⵔⵓⵙ",
  "Avoir Une Belle Allure":"Ungud,ⵓⵏⴳⵓⴷ",
  "Être / Devenir Épais":"UZur,ⵓⵣⵓⵔ",
  "Dépasser":"Ujar,ⵓⵊⴰⵔ",
  "Manquer D’eau (puits)":"Udun,ⵓⴷⵓⵏ",
  "S’asseoir Comme Un Singe":"QuRed,ⵇⵓⵔⴷ",
  "Être / Rendre Impuissant":"Qen,ⵇⵏ",
  "S’ennuyer":"Qneḍ,ⵇⵏⴹ",
  "Être Originaire De":"Qarch,ⵇⴰⵔⵛ",
  "Être Abondant":"Qwa,ⵇⵡⴰ",
  "Être Tordu":"Qwes,ⵇⵡⵙ",
  "Dépenser":"Qarḍ,ⵇⴰⵔⴹ",
  "Frapper Aux Deux Pieds":"Qarḍ,ⵇⴰⵔⴹ",
  "Être Pénétrant (savon)":"QaṚ,ⵇⴰⵕ",
  "S’amuser":"QeṢar,ⵇⵚⴰⵔ",
  "Écourter / Rapetisser":"Quḍeḍ,ⵇⵓⴹⴻⴹ",
  "Faire Tomber Avec Force":"QaṚeɛ,ⵇⴰⵕⵄ",
  "Jouer Au Jeu Du Hasard":"QeMaṛ,ⵇⵎⴰⵕ",
  "Goûter":"Qas,ⵇⴰⵙ",
  "Éplucher":"Qechaṛ,ⵇⵛⴰⵕ",
  "Carder La Laine":"Qarḍech,ⵇⴰⵔⴹⵛ",
  "Satisfaire Ses Invités":"QeWem,ⵇⵡⵎ",
  "Aplatir Le Pain":"QaṚes,ⵇⴰⵕⵙ",
  "Être Sévère Avec":"QeSeḥ,ⵇⵙⵃ",
  "Se Satisfaire De Peu":"Qneɛ,ⵇⵏⵄ",
  "Heurter":"Qarqeb,ⵇⴰⵔⵇⴱ",
  "Se Mettre Face À L’Est":"QeBer,ⵇⴱⵔ",
  "Être Capable De":"QeD,ⵇⴷ",
  "(s’)\nApprocher":"QaṚeb,ⵇⴰⵕⴱ",
  "Tourner":"Qreb,ⵇⵔⴱ",
  "Frire":"Qra,ⵇⵔⴰ",
  "Couper":"QeS,ⵇⵙ",
  "Veiller Sur":"Qaber,ⵇⴰⴱⵔ",
  "Attacher":"Qen,ⵇⵏ",
  "Goûter / Essayer":"Qedjeb,ⵇⴶⴱ",
  "Faire Du Bruit":"Qarqeb,ⵇⴰⵔⵇⴱ",
  "(se) Terminer":"Qḍa,ⵇⴹⴰ",
  "Lever En L’air":"QeẒeɛ,ⵇⵥⵄ",
  "Préparer Le Thé":"Qam(atay),ⵇⴰⵎ (ⴰⵜⴰⵢ)",
  "Saisir":"QeBeḍ,ⵇⴱⴹ",
  "Faire Des Roulades":"Qrujeɛ,ⵇⵔⵓⵊⵄ",
  "Être / Devenir Consistant":"Quṛ,ⵇⵓⵕ",
  "Être Dur / Difficile":"Qseḥ,ⵇⵙⵃ",
  "Rester / S’asseoir":"Qim,ⵇⵉⵎ",
  "Partir":"Raḥ,ⵔⴰⵃ",
  "Pleurer":"Ru,ⵔⵓ",
  "apprendre":"Rmed,ⵔⵎⴷ",
  "Appeler":"Ragha,ⵔⴰⵖⴰ",
  "Attendre":"Raja,ⵔⴰⵊⴰ",
  "Rencontrer":"Rqa,ⵔⵇⴰ",
  "Relever / Caler":"ReQem,ⵔⵇⵎ",
  "arriver":"ReḤeg,ⵔⵃⴳ",
  "S’occuper":"Rha,ⵔⵀⴰ",
  "(se) Couvrir":"ReḤef,ⵔⵃⴼ",
  "Asperger":"Ṛuch,ⵕⵓⵛ",
  "Atteindre La Cible":"Rqef,ⵔⵇⴼ",
  "ramasser":"Rqeḍ,ⵔⵇⴹ",
  "Coller":"Rseq,ⵔⵙⵇ",
  "Convenir":"RiQ,ⵔⵉⵇ",
  "Revitaliser (plantes)":"ReQeḥ,ⵔⵇⵃ",
  "coûter":"Swa,ⵙⵡⴰ",
  "Être En Bonne Santé":"ṢeḤ,ⵚⵃ",
  "Élever / Éduquer":"Syem,ⵙⵢⵎ",
  "Chauffer De L’orge":"Sri,ⵙⵔⵉ",
  "Faire Un Noeud":"Charf,ⵛⴰⵔⴼ",
  "Terminer Un Verset":"Srek,ⵙⵔⴽ",
  "Envoyer":"Sifeḍ,ⵙⵉⴼⴹ",
  "tamiser":"SeYar,ⵙⵢⴰⵔ",
  "Tendre La Main Pour Prendre":"SwiZeḍ,ⵙⵡⵉⵣⴹ",
  "Prendre Un Bain De Soleil":"SuMar,ⵙⵓⵎⴰⵔ",
  "devenir":"Ṣbeḥ,ⵚⴱⵃ",
  "Dorloter":"SḥiNeb,ⵙⵃⵉⵏⴱ",
  "Prendre Le Large":"Sebseb,ⵙⴱⵙⴱ",
  "Mentir":"SkhaReq,ⵙⵅⴰⵔⵇ",
  "Respirer Bruyamment":"Shunchef,ⵙⵀⵓⵏⵛⴼ",
  "Donner Une Paire De Claques":"SmeDarḍar,ⵙⵎⴷⴰⵔⴹⴰⵔ",
  "Rendre Droit":"Semrended,ⵙⵎⵔⵏⴷⴻⴷ",
  "Faire Semblant De":"Sniɛmer,ⵙⵏⵉⵄⵎⵔ",
  "Être Turbulent":"Ṣreb,ⵚⵔⴱ",
  "Réconcilier":"Ṣreḥ,ⵚⵔⵃ",
  "Féconder Une Vache":"Ṣreḥ,ⵚⵔⵃ",
  "Faire Paître":"Sarḥ,ⵙⴰⵔⵃ",
  "mélanger":"Sur,ⵙⵓⵔ",
  "Aller Doucement":"Saha,ⵙⴰⵀⴰ",
  "Commencer Quelque Chose":"SeHer (di),ⵙⵀⵔ",
  "Vexer":"Seɛqar,ⵙⵄⵇⴰⵔ",
  "Être Souffrant":"SḥuS,ⵙⵃⵓⵙ",
  "Voiler / Cacher":"Saṛ,ⵙⴰⵕ",
  "Tire Un Fil":"Stew,ⵙⵜⵡ",
  "Jeter Un Coup D’oeil":"SiJ,ⵙⵉⵊ",
  "Sourire":"Sfarnen,ⵙⴼⴰⵔⵏⴻⵏ",
  "Poindre (le Jour)":"Sungem,ⵙⵓⵏⴳⵎ",
  "Se Voiler La Tête":"Squmbar,ⵙⵇⵓⵎⴱⴰⵔ",
  "Lancer Des You-You":"Srewrew,ⵙⵔⵡⵔⵡ",
  "Tendre La Main":"Sigh Fus,ⵙⵉⵖ ⴼⵓⵙ",
  "Avancer Vers L’ennemi":"Sug,ⵙⵓⴳ",
  "Démarrer":"Sent,ⵙⵏⵜ",
  "Se Taire":"Sghed,ⵙⵖⴷ",
  "Écouter":"SḥeS,ⵙⵃⵙ",
  "Caqueter":"Sqaqa,ⵙⵇⴰⵇⴰ",
  "Se Laver Les Cheveux":"Sry,ⵙⵔⵢ",
  "regarder":"Sweḍ,ⵙⵡⴹ",
  "Tirer Augure":"ṢeBeḥ,ⵚⴱⵃ",
  "Entendre":"Ser,ⵙⵔ",
  "Souffler":"Suḍ,ⵙⵓⴹ",
  "Tremper Le Pain Dans La Sauce":"Sisen,ⵙⵉⵙⵏ",
  "Redresser":"SeGed,ⵙⴳⵯⴷ",
  "Beugler":"Smuhart,ⵙⵎⵓⵀⴰⵔⵜ",
  "Faire Avec":"SeLek,ⵙⵍⴽ",
  "Poser La Tête Sur Un Oreiller":"SuMet,ⵙⵓⵎⵜ",
  "Vanner":"ṢeFa,ⵚⴼⴰ",
  "Commercer":"SeBeb,ⵙⴱⴱ",
  "Respecter / Être Timide":"Sedḥa,ⵙⴷⵃⴰ",
  "Déborder":"Sfy,ⵙⴼⵢ",
  "Manger La Nuit (carême)":"ṢeḤar,ⵚⵃⴰⵔ",
  "Se Prosterner":"Sjed,ⵙⵊⴷ",
  "Se Reposer En S’appuyant":"SeNed,ⵙⵏⴷ",
  "Parler":"Siwer,ⵙⵉⵡⵔ",
  "Changer (argent)":"ṢaRef,ⵚⴰⵔⴼ",
  "Boire":"Su,ⵙⵓ",
  "Saluer":"Sedjem,ⵙⴶⵎ",
  "Battre (céréales)":"Sarwet,ⵙⴰⵔⵡⵜ",
  "Récolter":"ṢeYef,ⵚⵢⴼ",
  "Pardonner":"Smeḥ,ⵙⵎⵃ",
  "Faire / Être Froid / Refroidir":"Ṣmeḍ,ⵚⵎⴹ",
  "écouter":"SeNeṭ,ⵙⵏⵟ",
  "Ensorceler":"SeḤar,ⵙⵃⴰⵔ",
  "Scintiller":"Seqseq,ⵙⵇⵙⵇ",
  "Arroser":"Sew,ⵙⵡ",
  "Etendre / (parterre)":"SaReḥ,ⵙⴰⵔⵃ",
  "Tomber Sur / Trouver":"Saṛ,ⵙⴰⵕ",
  "Agacer":"ṢeDeɛ,ⵚⴷⵄ",
  "Acheter":"Segh,ⵙⵖ",
  "Filer La Laine":"Srew,ⵙⵔⵡ",
  "Renverser":"SeYeḥ,ⵙⵢⴻⵃ",
  "Embrasser":"Sudem,ⵙⵓⴷⵎ",
  "Trouver Difficelement":"SeDaṛ,ⵙⴷⴰⵕ",
  "Mériter":"SḥeQ,ⵙⵃⵇ",
  "envoyer":"SeK,ⵙⴽ",
  "Allumer":"Sigh,ⵙⵉⵖ",
  "Demander":"Seqsa,ⵙⵇⵙⴰ",
  "Connaître / Savoir":"Sen,ⵙⵏ",
  "Prendre Soin De":"Ṣun,ⵚⵓⵏ",
  "Ranger":"SeD,ⵙⴷ",
  "Clouer":"SeMaṛ,ⵙⵎⴰⵕ",
  "Rincer":"Srir,ⵙⵔⵉⵔ",
  "Manger Goulûment":"Sarḍ,ⵙⴰⵔⴹ",
  "Aller Au Marché":"SeWeq,ⵙⵡⵇ",
  "Errer":"Suḥ,ⵙⵓⵃ",
  "Voyager":"Safaṛ,ⵙⴰⴼⴰⵕ",
  "Prendre Place (bêtes)":"ṢeMeṭ,ⵚⵎⵟ",
  "Être Habile":"Says,ⵙⴰⵢⵙ",
  "Patienter":"Ṣbar,ⵚⴱⴰⵔ",
  "Tourner / Fermenter":"Smen,ⵙⵎⵏ",
  "Se Promener":"Sara,ⵙⴰⵔⴰ",
  "se Taire":"Sqar,ⵙⵇⴰⵔ",
  "Être Limpide / Pur":"Ṣfa,ⵚⴼⴰ",
  "Dégager Des Bulles":"Stekhtekh,ⵙⵜⵅⵜⵅ",
  "Siffler":"ṢeFar,ⵚⴼⴰⵔ",
  "Être Beau/ Bon":"Ṣebeḥ,ⵚⴱⵃ",
  "Placer Un Toit":"SeQef,ⵙⵇⴼ",
  "Crier":"SghuY,ⵙⵖⵓⵢ",
  "Laver Le Parterre":"SeYeq,ⵙⵢⴻⵇ",
  "s’affaisser":"Ṣter,ⵚⵜⵔ",
  "Enjamber":"Suṛf,ⵙⵓⵕⴼ",
  "Demeurer (le Jour)":"Cher,ⵛⵔ",
  "Être Dû Au Sort":"Chtab,ⵛⵜⴰⴱ",
  "Danser":"Chḍeḥ,ⵛⴹⵃ",
  "Être Beau / Charmant":"CheWaṛ,ⵛⵡⴰⵕ",
  "Ne Plus Oser Faire":"Chɛef,ⵛⵄⴼ",
  "Émigrer À L’Est":"ChaReq,ⵛⴰⵔⵇ",
  "Témoigner":"Chhed,ⵛⵀⴷ",
  "Devenir Avare":"CheḤ,ⵛⵃ",
  "Devenir Blanc":"Chemrer,ⵛⵎⵔⴻⵔ",
  "Être Affairé":"Chgher,ⵛⵖⵔ",
  "Être Brûlé":"Chmeḍ,ⵛⵎⴹ",
  "Pleuvoir Obliquement":"Cheryeḍ,ⵛⵔⵢⴻⴹ",
  "Profession De Foi En Islam":"CheHed,ⵛⵀⴷ (ⵛⵀⴸ)",
  "Tinter":"Chenchen,ⵛⵏⵛⵏ",
  "Être Handicapé":"Chrured,ⵛⵔⵓⵔⴷ (ⵛⵔⵓⵔⴸ)",
  "Cailler (lait)":"CHer,ⵛⵔ",
  "Griller":"Chnef,ⵛⵏⴼ",
  "Aspirer De L’air":"CheM,ⵛⵎ",
  "Arrêter (quelqu’un)":"Chneq,ⵛⵏⵇ",
  "Emballer":"Chmes,ⵛⵎⵙ",
  "Faire La Publicité":"CheHar,ⵛⵀⴰⵔ",
  "Tromper":"Chmet,ⵛⵎⵜ",
  "Pincer":"Chwi,ⵛⵡⵉ",
  "Demander Conseil":"Chawar,ⵛⴰⵡⴰⵔ",
  "Douter":"CheK,ⵛⴻⴽⴽ",
  "Radoter":"Charfeḥ,ⵛⴰⵔⴼⵃ",
  "Louer (maison)":"Chra,ⵛⵔⴰ",
  "Entraver":"Charf,ⵛⴰⵔⴼ",
  "Manger":"CH,ⵛ / ⵞ",
  "Labourer":"Charz,ⵛⴰⵔⵣ",
  "Fracasser":"CheQef,ⵛⵇⴼ",
  "Traverser Les Champs":"Chuq,ⵛⵓⵇ",
  "Être Préocupé":"Chḍen,ⵛⴹⵏ",
  "Remplir":"Chur,ⵛⵓⵔ",
  "Avilir":"CheYen,ⵛⵢⴻⵏ",
  "allumer":"Cheɛ,ⵛⵄ",
  "Secouer":"Chencher,ⵛⵏⵛⵔ",
  "déchirer":"CheReg,ⵛⵔⴳ",
  "Moucharder":"CheKem,ⵛⴽⵎ",
  "Avoir Les Cheveux Qui Commences À Blanchir Avec Le Temps":"Chab,ⵛⴰⴱ",
  "Pratiquer La Moisson":"CheWer,ⵛⵡⵔ",
  "Être Associé Avec":"Charch,ⵛⴰⵔⵛ",
  "Marchander":"CheṬar,ⵛⵟⴰⵔ",
  "se Plaindre":"Chetcha,ⵛⵜⵛⴰ",
  "Faire Paître Illégalement":"ChaReɛ,ⵛⴰⵔⵄ",
  "Détacher En Cassant":"Chreq,ⵛⵔⵇ",
  "Mesurer Avec La Main":"CheBar,ⵛⴱⴰⵔ",
  "Attraper":"CheBaṛ,ⵛⴱⴰⵕ",
  "Suffire":"Chfa,ⵛⴼⴰ",
  "Être Joli / Bon":"Chna,ⵛⵏⴰ",
  "Casser Violemment":"Chrekh,ⵛⵔⵅ",
  "Froncer Les Sourcils":"Chars,ⵛⴰⵔⵙ",
  "Avoir Les Cheveux Hérissés":"ChiRu,ⵛⵉⵔⵓ",
  "Fendre":"Chedjeq,ⵛⴶⵇ",
  "Bailler":"Tfa,ⵜⴼⴰ",
  "Abandonner":"Tark,ⵜⴰⵔⴽ",
  "Disperser":"TaRech,ⵜⴰⵔⵛ",
  "Être Borné":"ṬeMes,ⵟⵎⵙ",
  "Frapper Au Visage":"ṬeMes,ⵟⵎⵙ",
  "errer":"TeWeḥ,ⵜⵡⵃ",
  "s’égarer":"TeWej,ⵜⵡⵊ",
  "Oublier":"Tu,ⵜⵓ",
  "Se Maîtriser":"TeBet,ⵜⴱⵜ\n(ⵜⴱⵝ)",
  "Têter":"Teḍ,ⵜⴹ",
  "Tomber Amoureux":"Tarbeṭ,ⵜⴰⵔⴱⵟ",
  "Dormir":"Ṭes,ⵟⵙ",
  "Se Perdre":"TLef,ⵜⵍⴼ",
  "Compter Sur":"Tcher,ⵜⵛⵔ",
  "Être Dans De Mauvais Draps":"Tkhed,ⵜⵅⴷ",
  "prendre":"Tef,ⵜⴼ",
  "Capituler":"Trighar,ⵜⵔⵉⵖⴰⵔ",
  "Bouillir (lait)":"Tartar,ⵜⴰⵔⵝⴰⵔ",
  "Dilapider":"Ṭeqṭeq,ⵟⵇⵟⵇ",
  "Mendier / Demander":"Tar,ⵜⴰⵔ",
  "Se Repentir":"Tub,ⵜⵓⴱ",
  "Changer De Nationalité":"Turizi,ⵜⵓⵔⵉⵣⵉ",
  "Faire Faillite":"ṬeBeg,ⵟⴱⴳ",
  "tâtonner":"Teftef,ⵜⴼⵜⴼ",
  "Être Saturé":"Tbeṛ,ⵜⴱⵕ",
  "Miser":"Tawer,ⵜⴰⵡⵔ",
  "Avoir Lieu":"Wqeɛ,ⵡⵇⵄ",
  "Abonder":"Wseɛ,ⵡⵙⵄ",
  "Avoir Un Poste":"WeḌef,ⵡⴹⴼ",
  "être Difficile":"Wɛaṛ,ⵡⵄⴰⵕ",
  "revenir":"WeLeh,ⵡⵍⵀ",
  "Vieillir":"Wsar,ⵡⵙⴰⵔ",
  "Être Jaune / Jaunir":"Wargh,ⵡⴰⵔⵖ",
  "Acheter De La Viande":"WeZeɛ,ⵡⵣⵄ",
  "Répartir La Viande":"WeZeɛ,ⵡⵣⵄ",
  "Être Prêt":"Wjed,ⵡⵊⴷ (ⵡⵊⴸ)",
  "Peser":"Wzen,ⵡⵣⵏ",
  "Prendre (place)":"Wɛed,ⵡⵄⴷ (ⵡⵄⴸ)",
  "Frapper":"Wet,ⵡⵜ (ⵡⵝ)",
  "Offrir":"Wheb,ⵡⵀⴱ",
  "Répondre":"Wajeb,ⵡⴰⵊⴱ",
  "Laisser Des Consignes":"WeṢa,ⵡⵚⴰ",
  "S’habituer À":"WeLef,ⵡⵍⴼ",
  "Avoir Des Scruples":"Weswes,ⵡⵙⵡⵙ",
  "Voir":"Wara,ⵡⴰⵔⴰ",
  "Donner":"Wch,ⵡⵛ",
  "Se Photographier":"Wṣef,ⵡⵚⴼ",
  "Donner La Parole":"Wch Awar,ⵡⵛ ⴰⵡⴰⵔ",
  "Faire De La Poésie":"Wzen Izri,ⵡⵣⵏ ⵉⵣⵔⵉ",
  "Sentir Le Besoin De Voir Quelqu’un":"WeḤech,ⵡⵃⵛ",
  "Hériter":"Wert,ⵡⵔⵝ",
  "Reculer Pour Prendre De L’élan":"WeSeɛ,ⵡⵙⵄ",
  "Briller":"SweṢeg,ⵙⵡⵚⴳ",
  "Revendre":"Wadja,ⵡⴰⴶⴰ",
  
  
    "ⵎⴻⵔⵛ":"merch,se marier",
  "se marier":"merch,ⵎⴻⵔⵛ",
  "egg":"faire,ⵉⴳⴳ",
  "ⵉⴳⴳ":"egg,faire",
  "faire":"ⵉⴳⴳ,egg",
  "sqa":"se taire,ⵙⵇⴰⵔ",
  "ⵙⵇⴰⵔ":"sqa,se taire",
"se taire":"ⵙⵇⴰⵔ,sqa",
  "kar":"se lever,ⴽⴰⵔ",
  "ⴽⴰⵔ":"kar,se lever",
    "se lever":"ⴽⴰⵔ,kar",
  "Ini":"dire,ⵉⵏⵉ",
  "ⵉⵏⵉ":"Ini,dire",
  "dire":"ⵉⵏⵉ,Ini",
  "khdem":"travailler,ⵅⴷⴰⵎ",
  "ⵅⴷⴰⵎ":"khdem,travailler",
  "travailler":"khdem,ⵅⴷⴰⵎ",
  "anabdou":"Été,ⴰⵏⴱⴷⵓ",
  "ⴰⵏⴱⴷⵓ":"anabdou,Été",
  "été":"anabdou,ⴰⵏⴱⴷⵓ",
  "tissira":"chaussures,ⵜⵉⵙⵙⵉⵔⴰ",
  "ⵜⵉⵙⵙⵉⵔⴰ":"tissira,chaussures",
  "chaussures":"tissira,ⵜⵉⵙⵙⵉⵔⴰ",
  "takon":"Talon,ⵜⴰⴽⵓⵏ",
  "ⵜⴰⴽⵓⵏ":"takon,Talon",
  "talon":"takon,ⵜⴰⴽⵓⵏ",
  "tqacha":"Chaussettes,ⵜⴰⵇⵛⴰⵔ",
  "ⵜⴰⵇⵛⴰⵔ":"tqacha,Chaussettes",
"chaussettes":"tqacha,ⵜⴰⵇⵛⴰⵔ",
  "sawar":"pantalon,pantalon",
  "ⵙⴰⵡⴰⵔ":"sawar,pantalon",
  "pantalon":"sawar,ⵙⴰⵡⴰⵔ",
  "kamisita":"tee-shirt,ⴽⴰⵎⵉⵙⵉⵜⴰ",
  "ⴽⴰⵎⵉⵙⵉⵜⴰ":"kamisita,tee-shirt",
  "tee-shirt":"ⴽⴰⵎⵉⵙⵉⵜⴰ,kamisita",
  "falda":"jupe,ⴼⴰⵍⴷⴰ",
  "ⴼⴰⵍⴷⴰ":"falda,jupe",
  "jupe":"falda,ⴼⴰⵍⴷⴰ",
  "qandoura":"robe,ⵇⴰⵏⴷⵓⵔⴰ",
  "ⵇⴰⵏⴷⵓⵔⴰ":"qandoura,robe",
  "robe":"qandoura,ⵇⴰⵏⴷⵓⵔⴰ",
  "aqaftan":"caftan,ⴰⵇⴰⴼⵟⴰⵏ",
  "ⴰⵇⴰⴼⵟⴰⵏ":"aqaftan,caftan",
  "caftan":"aqaftan,ⴰⵇⴰⴼⵟⴰⵏ",
  "palto":"manteau,ⴱⴰⵍⵟⵓ",
  "ⴱⴰⵍⵟⵓ":"palto,manteau",
  "manteau":"palto,ⴱⴰⵍⵟⵓ",
  "takhambochte":"foulard,ⵜⴰⵅⴰⵎⴱⵓⵛⵜ",
  "ⵜⴰⵅⴰⵎⴱⵓⵛⵜ":"takhambochte,foulard",
"foulard":"takhambochte,ⵜⴰⵅⴰⵎⴱⵓⵛⵜ",
  "sawar":"pantalon,pantalon",
  "ⵙⴰⵡⴰⵔ":"sawar,pantalon",
  "t3jibay":"J'aime bien,ⵜⵄⵊⵉⴱⴰⵢ",
  "ⵜⵄⵊⵉⴱⴰⵢ":"t3jibay,J'aime bien",
  "j'aime bien":"t3jibay,ⵜⵄⵊⵉⴱⴰⵢ",
  "tatokh":"j'oublie,ⵜⴰⵜⵓⵅ",
  "ⵜⴰⵜⵓⵅ":"tatokh,j'oublie",
  "j'oublie":"tatokh,ⵜⴰⵜⵓⵅ",
"ma3lich":"pas grave,ⵎⴰⵄⵍⵉⵛ",
  "ⵎⴰⵄⵍⵉⵛ":"ma3lich,pas grave",
  "pas grave":"ma3lich,ⵎⴰⵄⵍⵉⵛ",
  "za3ma":"genre,ⵣⴰⵄⵎⴰ",
  "ⵣⴰⵄⵎⴰ":"za3ma,genre",
  "genre":"za3ma,ⵣⴰⵄⵎⴰ",
  "rcaghed":"papier,ⵔⴽⴰⵖⵉⴹ",
  "ⵔⴽⴰⵖⵉⴹ":"rcaghed,papier",
  "papier":"rcaghed,ⵔⴽⴰⵖⵉⴹ",
  "tawriqt":"feuille,ⵜⴰⵡⵔⵉⵇⵜ",
  "ⵜⴰⵡⵔⵉⵇⵜ":"tawriqt,feuille",
"feuille":"tawriqt,ⵜⴰⵡⵔⵉⵇⵜ",
  "tfawt":"lumière,ⵜⴼⴰⵡⵜ",
  "ⵜⴼⴰⵡⵜ":"tfawt,lumière",
  "lumière":"tfawt,ⵜⴼⴰⵡⵜ",
  "tsadjest":"sombre,ⵜⵙⴰⴶⴻⵙⵜ",
  "ⵜⵙⴰⴶⴻⵙⵜ":"tsadjest,sombre",
  "sombre":"tsadjest,ⵜⵙⴰⴶⴻⵙⵜ",
  "itaqsay":"j'ai mal,  ⵉⵜⴰⵇⵙⴰⵢ",
  "ⵉⵜⴰⵇⵙⴰⵢ":"itaqsay,j'ai mal",
  "j'ai mal":"itaqsay,ⵉⵜⴰⵇⵙⴰⵢ",
"iteqsay or ino":"j'ai mal au cœur,ⵉⵜⴰⵇⵙⴰⵢ ⵓⵔ ⵉⵏⵓ",
  "ⵉⵜⴰⵇⵙⴰⵢ ⵓⵔ ⵉⵏⵓ":"iteqsay or ino,j'ai mal au cœur",
  "j'ai mal au cœur":"iteqsay or ino,ⵉⵜⴰⵇⵙⴰⵢ ⵓⵔ ⵉⵏⵓ",
  "inza":"nez,ⵉⵏⵣⴰ",
  "ⵉⵏⵣⴰ":"inza,nez",
  "nez":"inza,ⵉⵏⵣⴰ",
  "aqemouch":"bouche,ⴰⵇⴻⵎⵓⵛ",
  "ⴰⵇⴻⵎⵓⵛ":"aqemouch,bouche",
  "bouche":"aqemouch,ⴰⵇⴻⵎⵓⵛ",
  "aqyou3":"crane,ⴰⵇⵢⵓⵄ",
  "crane":"aqyou3,ⴰⵇⵢⵓⵄ",
"ⴰⵇⵢⵓⵄ":"aqyou3,crane",
  "azdjif":"tete,ⴰⵣⴶⵉⴼ",
  "ⴰⵣⴶⵉⴼ":"azdjif,tete",
  "tete":"azdjif,ⴰⵣⴶⵉⴼ",
  "aghoumboub":"visage,ⴰⵖⵓⵎⴱⵓⴱ",
  "ⴰⵖⵓⵎⴱⵓⴱ":"aghoumboub,visage",
  "visage":"aghoumboub,ⴰⵖⵓⵎⴱⵓⴱ",
  "bourourou":"colon,ⴱⵓⵔⵓⵔⵓ",
  "colon":"bourourou,ⴱⵓⵔⵓⵔⵓ",
  "ⴱⵓⵔⵓⵔⵓ":"bourourou,colon",
"fakkar":"penser,ⴼⴰⴽⴽⴰ",
  "ⴼⴰⴽⴽⴰ":"fakkar,penser",
  "penser":"fakkar,ⴼⴰⴽⴽⴰ",
  "moun":"accompagner,ⵎⵓⵏ",
  "ⵎⵓⵏ":"moun,accompagner",
  "accompagner":"moun,ⵎⵓⵏ",
  "smoun":"rassembler,ⵙⵎⵓⵏ",
  "ⵙⵎⵓⵏ":"smoun,rassembler",
"rassembler":"smoun,ⵙⵎⵓⵏ",
  "jbedr":"tirer,ⵊⴱⴰⴷⵔ",
  "ⵊⴱⴰⴷⵔ":"jbedr,tirer",
  "tirer":"jbedr,ⵊⴱⴰⴷⵔ",
  "ksi":"prendre, enlever, supprimer,ⴽⵙⵉ",
  "ⴽⵙⵉ":"ksi,supprimer",
  "supprimer":"ksi,ⴽⵙⵉ",
  "chti":"prendre,ⵛⵜⵉ",
  "ⵛⵜⵉ":"chti,prendre",
  "prendre":"chti,ⵛⵜⵉ",
"harlch":"etre malade,ⵀⴰⵔⵍⵛ",
  "ⵀⴰⵔⵍⵛ":"harlch,etre malade",
  "etre malade":"ⵀⴰⵔⵍⵛ,harlch",
  "souw":"boire,ⵙⵓⵡ",
  "ⵙⵓⵡ":"souw,boire",
  "boire":"souw,ⵙⵓⵡ",
  "az":"casser, taper,ⴰⵣ",
  "ⴰⵣ":"az,casser, taper",
"taper":"az,ⴰⵣ",
  "ari":"monter,ⴰⵔⵉ",
  "monter":"ⴰⵔⵉ,ari",
    "ⴰⵔⵉ":"monter,ari",
  "ari":"écrire,ⴰⵕⵉ",
  "écrire":"Ari,ⴰⵕⵉ",
  "ⴰⵕⵉ":"Ari,écrire",
  "safar":"voyager,ⵚⴰⴼⴰⵔ",
  "ⵚⴰⴼⴰⵔ":"safar,voyager",
  "voyager":"ⵚⴰⴼⴰⵔ,safar",
"sara":"se promener,ⵙⴰⵔⴰ",
  "ⵙⴰⵔⴰ":"sara,se promener",
  "se promener":"ⵙⴰⵔⴰ,sara",
  "saqsi":"demander,ⵚⴰⵇⵙⵉ",
  "ⵚⴰⵇⵙⵉ":"saqsi,demander",
  "demander":"saqsi,ⵚⴰⵇⵙⵉ",
  "harq":"avoir mal,ⵃⴰⵔⵇ",
  "ⵃⴰⵔⵇ":"harq,avoir mal",
"avoir mal":"harq,ⵃⴰⵔⵇ",
  "adef":"entrer,ⴰⴷⴼ",
  "ⴰⴷⴼ":"adef,entrer",
    "entrer":"adef,ⴰⴷⴼ",
  "af":"trouver,ⴰⴼ",
  "ⴰⴼ":"af,trouver",
  "trouver":"af,ⴰⴼ",
  "khes":"vouloir,ⵅⵙ",
  "ⵅⵙ":"khes,vouloir",
  "vouloir":"khes,ⵅⵙ",
"tekhs":"aimer,ⵜⴻⵅⵙ",
  "ⵜⴻⵅⵙ":"tekhs,aimer",
  "aimer":"tekhs,ⵜⴻⵅⵙ",
  "azou":"chercher,ⴰⵣⵓ",
  "ⴰⵣⵓ":"azou,chercher",
  "chercher":"azou,ⴰⵣⵓ",
  "hyène":"ⵉⴼⵉⵙ",
  "mot":"ⴰⵡⴰⵔ",
  "chèvre":"ⵜⵖⴰⴺⵔⴺ",
  "au clair de la lune":"ⵜⴰⵣⵉⵔⵉ ⵜⴰⵎⵉⵔⵉ",
  "salut, ça va ?":"ⵍⴰⴱⴰⵙ",
  "quoi de neuf ?":"ⵛⵏⵓ ⵊⴷⵉⴷ",
  "lait":"ⴰⵖⵉ",
  "eau":"ⴰⵎⴰⵏ",
  "figue":"ⵔⴱⴰⵛⵓⴰ",
  "oignon":"ⵜⵉⴱⵙⴼⵉⵏ",
  "pastèque":"ⴷⵍⵍⵉⵛ",
  "savon":" ⵚⴰⴱⵓⵏ",
  "pomme":"ⵜⴰⵜⴻⴼⴰⵃⵉⵜ",
  "bœuf":"ⴰⴼⵓⵏⴰⵙ",
  "vache":"ⵜⴰⴼⵓⵏⴰⵙⵜ",
"agharrabou":"bateau",
  "ⴰⵖⴰⵔⵔⴰⴱⵓ":"Agharrabou,Bateau",
  "aghanaj":"ⴰⵖⴰⵏⴰⵊ,Chanson",
  "chanson":"Aghanaj,ⴰⵖⴰⵏⴰⵊ",
  "izri":"Poème,ⵉⵣⵔⵉ",
  "ⵉⵣⵔⵉ":"Izri,Poème",
  "thamouath":"Terre,Sol,Pays",
  "ⵜⴰⵎⵓⵔⵜ":"Thamouath",
  "amataw":"Une larme,ⴰⵎⴰⵟⵟⴰⵡ",
  "ⴰⵎⴰⵟⵟⴰⵡ":"Amataw,Une larme",
  "imattawen":"ⵉⵎⴰⵟⴰⵡⵏ,Les larmes",
  "ⵉⵎⴰⵟⴰⵡⵏ":"Imattawen,Une larme",
  "tadahacht":"ⵜⴰⴷⵃⴰⵛⵜ,Sourire",
  "ⵜⴰⴷⵃⴰⵛⵜ":"Tadahacht,Sourire",
"awar":"ⴰⵡⴰⵔ,La parole",
  "ⴰⵡⴰⵔ":"Awar,La parole",
  "la parole":"Awar,ⴰⵡⴰⵔ",
  "our":"ⵓⵔ,Coeur",
  "ⵓⵔ":"Our,Coeur",
  "coeur":"Our,ⵓⵔ",
  "thitawin":"ⵜⵉⵟⴰⵡⵉⵏ,Les yeux",
  "ⵜⵉⵟⴰⵡⵉⵏ":"Thitawin,Les yeux",
  "les yeux":"Thitawin,ⵜⵉⵟⴰⵡⵉⵏ",
  "Thimassi":"ⵜⵉⵎⴰⵙⵙⵉ,Le feu",
  "ⵜⵉⵎⴰⵙⵙⵉ":"Thimassi,Le feu",
  "le feu":"Thimassi,ⵜⵉⵎⴰⵙⵙⵉ",
  "rmawth":"ⵔⵎⴰⵡⵜ,La mort",
  "la mort":"Rmawth,ⵔⵎⴰⵡⵜ",
"makla,macha":"Nourriture,ⵎⴰⴽⵍⴰ,ⵎⴰⵛⴰ",
  "nourriture":"Makla,Macha,ⵎⴰⴽⵍⴰ,ⵎⴰⵛⴰ",
  "ⵎⴰⴽⵍⴰ,ⵎⴰⵛⴰ":"Makla,Macha,Nourriture",
  "aghrom":"Pain,ⴰⵖⵔⵓⵎ",
  "ⴰⵖⵔⵓⵎ":"Aghrom,Pain",
  "pain":"Aghrom,ⴰⵖⵔⵓⵎ",
  "tighmas":"Dent,ⵜⵉⵖⵎⴰⵙ",
  "ⵜⵉⵖⵎⴰⵙ":"Tighmas,Dent",
  "dent":"Tighmas,ⵜⵉⵖⵎⴰⵙ",
  "ires":"Langue,ⵍⵔⴻⵙ",
  "langue":"Ires,ⵍⵔⴻⵙ",
  "ⵍⵔⴻⵙ":"Ires,Langue",
  "timiwin":"ⵜⵉⵎⵉⵡⵉⵏ,Sourcil",
  "ⵜⵉⵎⵉⵡⵉⵏ":"Timiwin,Sourcil",
"sourcil":"Timiwin,ⵜⵉⵎⵉⵡⵉⵏ",
  "amazogh":"Oreil,ⴰⵎⴰⵣⵓⵖ",
  "oreil":"Amazogh,ⴰⵎⴰⵣⵓⵖ",
  "ⴰⵎⴰⵣⵓⵖ":"Amazogh,Oreil",
  "t3jabadayi":"ⵜⵄⵊⴱⴰⴷⴰⵢⵉ,Tu me plais",
  "tu me plais":"T3jabadayi,ⵜⵄⵊⴱⴰⴷⴰⵢⵉ",
  "ⵜⵄⵊⴱⴰⴷⴰⵢⵉ":"T3jabadayi,Tu me plais",
  "tekhsekhchem":"Je t'aime,ⵜⴰⵅⵙⵖⵛⴻⵎ",
  "ⵜⴰⵅⵙⵖⵛⴻⵎ":"Tekhsekhchem,Je t'aime",
  "je t'aime":"Tekhsekhchem,ⵜⴰⵅⵙⵖⵛⴻⵎ",
  "atahninte ino":"ⴰⵜⴰⵃⵏⵉⵏⵜ ⵉⵏⵓ,Ma douce",
  "ma douce":"Atahninte ino,ⴰⵜⴰⵃⵏⵉⵏⵜ ⵉⵏⵓ",
  "ⴰⵜⴰⵃⵏⵉⵏⵜ ⵉⵏⵓ":"Atahninte ino,Ma douce",
"twa7chekhchem":"Tu m'as manqué,ⵜⴻⵡⴰⵃⵖⵛⴻⵎ",
  "ⵜⴻⵡⴰⵃⵖⵛⴻⵎ":"Twa7chekhchem,Tu m'as manqué",
  "tu m'as manqué":"ⵜⴻⵡⴰⵃⵖⵛⴻⵎ,Twa7chekhchem",
  "mintagad":"Que fais-tu ?,ⵎⵉⵏⵜⴰⴳⴰⴷ",
  "que fais-tu ?":"Mintagad,ⵎⵉⵏⵜⴰⴳⴰⴷ",
  "ⵎⵉⵏⵜⴰⴳⴰⴷ":"Mintagad,Que fais-tu ?",
  "azokh achmawikh":"je veux prendre ta main,ⴰⵥⵓⵅ ⴰⵛⵎⴰⵡⵉⵅ",
  "ⴰⵥⵓⵅ ⴰⵛⵎⴰⵡⵉⵅ":"Azokh achmawikh,je veux prendre ta main",
  "je veux prendre ta main":"Azokh achmawikh,ⴰⵥⵓⵅ ⴰⵛⵎⴰⵡⵉⵅ",
  "cham tasabhante":"Tu es belle,ⵛⴰⵎ ⵜⴰⵚⴱⵃⴰⵏⵜ",
  "tu es belle":"Cham tasabhante,ⵛⴰⵎ ⵜⴰⵚⴱⵃⴰⵏⵜ",
  "ⵛⴰⵎ ⵜⴰⵚⴱⵃⴰⵏⵜ":"Cham tasabhante,Tu es belle",
  "semhay":"Pardonne-moi,ⵙⴻⵎⵃⴰⵢ",
  "ⵙⴻⵎⵃⴰⵢ":"Semhay,Pardonne-moi",
"pardonne-moi":"ⵙⴻⵎⵃⴰⵢ,Semhay",
  "tamghat ino":"ⵜⴰⵎⵖⴰⵔⵜ ⵉⵏⵓ,Ma femme",
  "ma femme":"Tamghat ino,ⵜⴰⵎⵖⴰⵔⵜ ⵉⵏⵓ",
  "ⵜⴰⵎⵖⴰⵔⵜ ⵉⵏⵓ":"Ma femme,Tamghat ino",
  "3afakom":"ⵄⴰⴼⴰⴽⵓⵎ,Je vous remercie",
  "ⵄⴰⴼⴰⴽⵓⵎ":"3afakom,Je vous remercie",
  "je vous remercie":"3afakom,ⵄⴰⴼⴰⴽⵓⵎ",
  "3adrokh":"Biensûr,ⵄⴰⴷⵔⵓⵅ",
  "ⵄⴰⴷⵔⵓⵅ":"3adrokh,Biensûr",
  "biensûr":"3adrokh,ⵄⴰⴷⵔⵓⵅ",
  "mamach tadjid":"ⵎⴰⵎⴰⵛ ⵜⴰⴷⵊⵉⴷ, Comment vas-tu ?",
  "comment vas-tu ?":"ⵎⴰⵎⴰⵛ ⵜⴰⴷⵊⵉⴷ,Mamach tadjid",
  "ⵎⴰⵎⴰⵛ ⵜⴰⴷⵊⵉⴷ":"Mamach tadjid,Comment vas-tu",
"radnech":"Moi aussi,ⵔⴰⴷⵏⴰⵛ",
  "ⵔⴰⴷⵏⴰⵛ":"Radnech,Moi aussi",
  "tfakakh dayem":"Je pense à toi,ⵜⴼⴰⴽⴰⵔⵖ ⴷⴰⵢⴻⵎ",
  "rebda":"Toujours,ⵔⴻⴱⴷⴰ",
  "ⵔⴻⴱⴷⴰ":"Rebda,Toujours",
  "toujours":"ⵔⴻⴱⴷⴰ,Rebda",
  "3amas":"Jamais,ⵄⴰⵎⴰⵙ",
  "ⵄⴰⵎⴰⵙ":"3amas,Jamais",
  "jamais":"ⵄⴰⵎⴰⵙ,3amas",
  "mintazod":"Que veux-tu ,ⵎⵉⵏⵜⴰⵣⵓⴷ",
  "ⵎⵉⵏⵜⴰⵣⵓⴷ":"Mintazod,Que veux-tu ",
  "que veux-tu ":"Mintazod,ⵎⵉⵏⵜⴰⵣⵓⴷ",
  "mermi":"ⵎⴻⵔⵎⵉ,Quand",
  "quand":"Mermi,ⵎⴻⵔⵎⵉ",
"ⵎⴰⵔⵎⵉ":"Mermi,Quand",
  "magha":"Pourquoi,ⵎⴰⵖⴰ",
  "pourquoi":"Magha,ⵎⴰⵖⴰ",
  "ⵎⴰⵖⴰ":"Pourquoi,Magha",
  "3rayen":"ⵄⵔⴰⵢⴻⵏ,Bientôt",
  "bientôt":"3rayen,Bientôt",
  "ⵄⵔⴰⵢⴻⵏ":"3rayen,ⵄⴰⴼⴰⴽⵓⵎ",
  "nech nem":"Je suis à toi,ⵏⴰⵛ ⵏⴻⵎ",
  "ⵏⴰⵛ ⵏⴻⵎ":"Nech nem,Je suis à toi",
  "cham ino":"Tu es à moi,ⵛⴰⵎ ⵉⵏⵓ",
  "ⵛⴰⵎ ⵉⵏⵓ":"Cham ino,Tu es à moi",
  "alhob ino":"Mon amour,ⴰⵍⵃⵓⴱ ⵉⵏⵓ",
  "ⴰⵍⵃⵓⴱ ⵉⵏⵓ":"Alhob ino,Mon amour",
"ayor ino":"Mon coeur,ⴰⵢⵓⵔ ⵉⵏⵓ",
  "ⴰⵢⵓⵔ ⵉⵏⵓ":"Ayor ino,Mon coeur",
  "da": "ici ⴷⴰ",
  "ⴷⴰ": "da ici",
  "ici": "ⴷⴰ da",
  "idess":"Sommeil,ⵉⴹⴹⴰⵙ",
  "ⵉⴹⴹⴰⵙ":"idess,Sommeil",
  "sommeil":"idess,ⵉⴹⴹⴰⵙ",
  "chihaja":"Un peu,ⵛⵉⵃⴰⵊⴰ",
  "ⵛⵉⵃⴰⵊⴰ":"chihaja,Un peu",
  "un peu":"chihaja,ⵛⵉⵃⴰⵊⴰ",
  "tamadith":"Nuit,ⵜⴰⵎⴰⴷⵉⵜ",
  "ⵜⴰⵎⴰⴷⵉⵜ":"tamadith,Nuit",
  "nuit":"tamadith,ⵜⴰⵎⴰⴷⵉⵜ",
  "sbeh":"Jour,ⵚⴱⴰⵃ",
  "jour":"sbeh,ⵚⴱⴰⵃ",
  "ⵚⴱⴰⵃ":"sbeh,jour",
  "tasrith":"ⵜⴰⵙⵔⵉⵜ,La mariée",
  "ⵜⴰⵙⵔⵉⵜ":"tasrith,La mariée",
"nivira":"Frigo",
  "mamita":"Marmite,ⵎⴰⵔⵎⵉⵜⴰ",
  "ⵎⴰⵔⵎⵉⵜⴰ":"mamita,Marmite",
  "Frigo":"nivira",
  "tomobin":"voiture,ⵜⵓⵎⵓⴱⵉⵏ",
  "voiture":"tomobin,ⵜⵓⵎⵓⴱⵉⵏ",
  "ⵜⵓⵎⵓⴱⵉⵏ":"tomobin,voiture",
  "bachaklite":"vélo,ⴱⴰⵛⴽⵍⵉⵟ",
  "vélo":"bachaklite,ⴱⴰⵛⴽⵍⵉⵟ",
  "ⴱⴰⵛⴽⵍⵉⵟ":"bachaklite,vélo",
  "akhariq":"Mensonge,ⴰⵅⴰⵔⵉⵇ",
  "ⴰⵅⴰⵔⵉⵇ":"akhariq,Mensonge",
  "mensonge":"akhariq,La ⴰⵅⴰⵔⵉⵇ",
  "neyeth":"Innocence, naïveté,ⵏⵉⵢⴰⵜ",
"ⵏⵉⵢⴰⵜ":"neyeth,innocence, ",
  "naïveté":"ⵏⵉⵢⴰⵜ,neyeth",
  "mighiss":"Intelligent,ⵎⵉⵖⵉⵙ",
  "ⵎⵉⵖⵉⵙ":"mighiss,Intelligent",
  "intelligent":"mighiss,ⵎⵉⵖⵉⵙ",
  "abarchan":"Noir,ⴰⴱⴰⵔⵛⴰⵏ",
  "ⴰⴱⴰⵔⵛⴰⵏ":"abarchan,Noir",
  "noir":"abarchan,ⴰⴱⴰⵔⵛⴰⵏ",
  "achamrar":"Blanc,ⴰⵛⴰⵎⵔⴰⵔ",
  "ⴰⵛⴰⵎⵔⴰⵔ":"achamrar,Blanc",
  "blanc":"achamrar,ⴰⵛⴰⵎⵔⴰⵔ",
  "adasekh":"Je viens,ⴰⴷⴰⵙⴻⵅ",
  "ⴰⴷⴰⵙⴻⵅ":"adasekh,Je viens",
  "tazregh":"Je cours,ⵜⴰⵣⵔⴻⵖ",
"ⵜⴰⵣⵔⴻⵖ":"tazregh,Je cours",
  "je cours":"tazregh,ⵜⴰⵣⵔⴻⵖ",
  "tessmed":"Il fait froid,ⵜⴰⵚⵎⵉⴹ",
  "ⵜⴰⵚⵎⵉⴹ":"tessmed,Il fait froid",
  "il fait froid":"tessmed,ⵜⴰⵚⵎⵉⴹ",
  "rahmo":"Il fait chaud,ⵔⴰⵃⵎⵓ",
  "ⵔⴰⵃⵎⵓ":"rahmo,Il fait chaud",
  "il fait chaud":"rahmo,ⵔⴰⵃⵎⵓ",
  "anza":"pluie,ⴰⵏⵣⴰ",
  "ⴰⵏⵣⴰ":"pluie,anza",
  "pluie":"anza,ⴰⵏⵣⴰ",
  "adfer":"neige,ⴰⴷⴼⴰⵔ",
  "ⴰⴷⴼⴻⵔ":"adfer,neige",
"neige":"ⴰⴷⴼⴻⵔ,adfer",
  "arih":"Le vent,ⴰⵔⵉⵃ",
  "ⴰⵔⵉⵃ":"arih,Le vent",
  "le vent":"arih,ⴰⵔⵉⵃ",
  "izi":"mouche,ⵉⵣⵉ",
  "namous":"moustique,ⵏⴰⵎⵓⵙ",
  "amchich":"chat,ⴰⵎⵛⵉⵛ",
  "aqzin":"chien,ⴰⵇⵥⵉⵏ",
  "ajdid":"oiseau,ⴰⵊⴹⵉⴹ",
  "ichfar":"tortue,ⵉⵛⴼⴰⵔ",
  "twaligh": "je vois ⵜⵡⴰⵍⵉⵖ",
  "je vois": "twaligh ⵜⵡⴰⵍⵉⵖ",
  "ⵜⵡⴰⵍⵉⵖ": "twaligh je vois",
  
  "ⵄⴰⵢⵏ ⵔⴰⵊⴰ": "raja 3ayne attendre",
  "raja 3ayne": "ⵄⴰⵢⵏ ⵔⴰⵊⴰ attendre",
  "attendre": "raja 3ayne ⵄⴰⵢⵏ ⵔⴰⵊⴰ",
  
  "ⵙⴰⵏⵃⴰⵢⵉⵖ": "senhayigh autorise-moi",
  "senhayigh": "ⵙⴰⵏⵃⴰⵢⵉⵖ autorise-moi",
  "autorise-moi": "senhayigh ⵙⴰⵏⵃⴰⵢⵉⵖ",
  
  "ⵉⵔⴰⵔ": "irar s'amuser",
  "irar": "ⵉⵔⴰⵔ s'amuser",
  "s'amuser": "irar ⵉⵔⴰⵔ",
  
  "ⵡⴰⴷⴷⴰⵔⵖ": "weddaregh perdue",
  "weddaregh": "ⵡⴰⴷⴷⴰⵔⵖ perdue",
  "perdue": "weddaregh ⵡⴰⴷⴷⴰⵔⵖ",
  
  "ⵉⵣⵡⴰⵔⴻⵎ": "izwarem après vous",
  "izwarem": "ⵉⵣⵡⴰⵔⴻⵎ après vous",
  "après vous": "izwarem ⵉⵣⵡⴰⵔⴻⵎ",
  
  "ⵓⴳⵉⵖ": "ugigh je refuse",
  "ugigh": "ⵓⴳⵉⵖ je refuse",
  "je refuse": "ugigh ⵓⴳⵉⵖ",
  
  "ⵃⴰⵡⵔⴻⵎ": "hawrem ralentir",
  "hawrem": "ⵃⴰⵡⵔⴻⵎ ralentir",
  "ralentir": "hawrem ⵃⴰⵡⵔⴻⵎ",
  
  "ⵎⴰⵎⴽ ⵜⴰⵙⵄⵜ": "mamek tesse3t quelle heure est-il ?",
  "quelle heure est-il ?": "ⵎⴰⵎⴽ ⵜⴰⵙⵄⵜ mamek tesse3t",
  
  "ⵉⵙⵙⴰⵇⵙⵙⵉⵜⴰⵏ": "isseqssiten questionner",
  "isseqssiten": "ⵉⵙⵙⴰⵇⵙⵙⵉⵜⴰⵏ questionner",
  "questionner": "isseqssiten ⵉⵙⵙⴰⵇⵙⵙⵉⵜⴰⵏ",
  
  "ⴰⴽⵓⴷ ⵢⴰⵄⴷⵓ": "akud ye3du temps écoulé",
  "akud ye3du": "ⴰⴽⵓⴷ ⵢⴰⵄⴷⵓ temps écoulé",
  "temps écoulé": "akud ye3du ⴰⴽⵓⴷ ⵢⴰⵄⴷⵓ",
  
  "ⵖⴰⵔ ⵙⴰⴱⵄⴰ": "ghar seb3a vers 7h",
  "ghar seb3a": "ⵖⴰⵔ ⵙⴰⴱⵄⴰ vers 7h",
  "vers 7h": "ghar seb3a ⵖⴰⵔ ⵙⴰⴱⵄⴰ",
  
  "ⵉⵏⵏⵉ ⵉⵏⵓ": "inni inou ce sont les miens",
  "inni inou": "ⵉⵏⵏⵉ ⵉⵏⵓ ce sont les miens",
          
          "how are you?": "mich thedjedh?,comment va tu?,ⵎⵉⵛ ⵝⴰⴶⵉⴷ?",
      "ⵎⵉⵛ ⵝⴰⴶⵉⴷ?": "mich thedjedh?,comment va tu?,ⵎⵉⵛ ⵝⴰⴶⵉⴷ?",
      "mich thedjedh?": "how are you?,comment va tu?,ⵎⵉⵛ ⵝⴰⴶⵉⴷ?",
      "mle7 cha?": "tu va biens?,ⵎⵍⵉⵃ ⵛⴰ?",
      "ⵎⵍⵉⵃ ⵛⴰ?": "tu va biens?,mle7 cha?",
      "tu va biens?": "ⵎⵍⵉⵃ ⵛⴰ?,mle7 cha?",
      "kuchi mle7?": "tous va biens?,ⴽⵓⵔⵛⵉ ⵎⵍⵉⵃ?",
      "ⴽⵓⵔⵛⵉ ⵎⵍⵉⵃ?": "tous va biens?,kuchi mle7?",
      "tous va biens?": "ⴽⵓⵔⵛⵉ ⵎⵍⵉⵃ?,kuchi mle7?",
      "fine": "a7amdoulilla7,kuchi meli7, trés bien merci,ⴰⵃⴰⵎⴷⵓⵍⴰⵀ ⴽⵓⵔⵛⵉ ⵎⵍⵉⵃ",
      "ⴰⵃⴰⵎⴷⵓⵍⴰⵀ": "a7amdoulilla7,kuchi meli7, trés bien merci,fine",
      "trés bien merci": "a7amdoulilla7,ⴰⵃⴰⵎⴷⵓⵍⴰⵀ ⴽⵓⵔⵛⵉ ⵎⵍⵉⵃ,fine",
      "not good": "ewa chwait,pas biens,ⵉⵡⴰ ⵛⵡⴰⵢⵜ",
      "ⵉⵡⴰ ⵛⵡⴰⵢⵜ": "ewa chwait,pas biens,not good",
      "pas biens": "ewa chwait,pas biens,ⵉⵡⴰ ⵛⵡⴰⵢⵜ",
      "ewa chwait": "ⵉⵡⴰ ⵛⵡⴰⵢⵜ,pas biens,not good",
      
      "whats your name?": "michdham 9an ?,quel est ton nom?,ⵎⵉⵛⴷⴰⵎ ⵇⴰⵏ?",
      "ⵎⵉⵛⴷⴰⵎ ⵇⴰⵏ?": "michdham 9an ?,quel est ton nom?,whats your name?",
      "michdham 9an?": "whats your name?,quel est ton nom?,ⵎⵉⵛⴷⴰⵎ ⵇⴰⵏ?",
      "quel est ton nom?": "michdham 9an,whats your name?,ⵎⵉⵛⴷⴰⵎ ⵇⴰⵏ?",
      "my name is fadma and yours?": "isam ino simane, o isam nem/nech?",
      "mon nom est fadma et toi?": "je m'appelle simane, et toi?,isam ino simane, o isam nem/nech?",
      "ism ino fadma o chem?": "je m'appelle simane, et toi?,isam ino simane, o isam nem/nech?",
      "ⵉⵙⵎ ⵉⵏⵓ ⴼⴰⴹⵎⴰ ⵓ ⵛⴰⵎ?": "ⵉⵙⴰⵎ ⵉⵏⵓ ⵙⵉⵎⴰⵏ, o isam nem/nech?",
      "where are you from?": "manis chim?,d'ou viens tu?,where are you from?",
      "ⵎⴰⵏⵉⵙ ⵛⴰⵎ?": "manis chim?,d'ou viens tu?,ⵎⴰⵏⵉⵙ ⵛⴰⵎ?",
      "manis chim?": "where are you from?,d'ou viens tu?,ⵎⴰⵏⵉⵙ ⵛⴰⵎ?",
      "d'ou viens tu?": "manis chim?,where are you from?,ⵎⴰⵏⵉⵙ ⵛⴰⵎ?",
      "what do you want?": "min takhssadh?,que veux tu?,ⵎⵉⵏ ⵜⴰⵅⵙⵙⴰⴷ?",
      "min takhssadh?": "what do you want?,que veux tu?,ⵎⵉⵏ ⵜⴰⵅⵙⵙⴰⴷ?",
      "ⵎⵉⵏ ⵜⴰⵅⵙⵙⴰⴷ?": "what do you want?,que veux tu?,min takhssadh?",
      "que veux tu?": "what do you want?,ⵎⵉⵏ ⵜⴰⵅⵙⵙⴰⴷ?,min takhssadh?",
      "what is your main hobbies?": "ewa min t3awadhedh?,ⵉⵡⴰ ⵎⵉⵏ ⵜⵄⴰⵡⴰⴷⴰⴷ?,quoi de neuf chez vous?",
      "ewa min t3awadhedh?": "what is your main hobbies?,ⵉⵡⴰ ⵎⵉⵏ ⵜⵄⴰⵡⴰⴷⴰⴷ?,quoi de neuf chez vous?",
      "quoi de neuf chez vous?": "ewa min t3awadhedh?,ⵉⵡⴰ ⵎⵉⵏ ⵜⵄⴰⵡⴰⴷⴰⴷ?,quoi de neuf chez vous?",
      "ⵉⵡⴰ ⵎⵉⵏ ⵜⵄⴰⵡⴰⴷⴰⴷ?": "ewa min t3awadhedh?,what is your main hobbies?,what is your main hobbies?",
      "dedans": "dedans,à l'intérieur,ghar dakher",
      "Ur ghar ttilifun": "Je n'ai pas de téléphone ⵓⵔ ⵖⴰⵔ ⵟⵉⵍⵉⴼⵓⵏ",
      "Je n'ai pas de téléphone": "Ur ghar ttilifun ⵓⵔ ⵖⴰⵔ ⵟⵉⵍⵉⴼⵓⵏ",
      "ⵓⵔ ⵖⴰⵔ ⵟⵉⵍⵉⴼⵓⵏ": "Je n'ai pas de téléphone Ur ghar ttilifun",
      "i d'ont have a telefone": "Ur ghar ttilifun ⵓⵔ ⵖⴰⵔ ⵟⵉⵍⵉⴼⵓⵏ",
      "aŷmi tinu ded asyun di imessi": "comme si tu tordais une corde dans le feu ⴰⵖⵎⵉ ⵜⵉⵏⵓ ⴷⴰⴷ ⴰⵙⵢⵓⵏ ⴷⵉ ⵉⵎⵙⵙⵉ",
      "comme si tu tordais une corde dans le feu": "aŷmi tinu ded asyun di imessi ⴰⵖⵎⵉ ⵜⵉⵏⵓ ⴷⴰⴷ ⴰⵙⵢⵓⵏ ⴷⵉ ⵉⵎⵙⵙⵉ",
      "ⴰⵖⵎⵉ ⵜⵉⵏⵓ ⴷⴰⴷ ⴰⵙⵢⵓⵏ ⴷⵉ ⵉⵎⵙⵙⵉ": "comme si tu tordais une corde dans le feu aŷmi tinu ded asyun di imessi",
      "aŷmi iseppeŷ i węlaryar, istiwrhu i węlehsuar": "c'est comme celui qui danse à un aveugle,fait des youyous à un sourd , ⴰⵖⵎⵉ ⵉⵙⵒⵒⴰⵖ ⵉ ⵡⴰⵍⴰⵔⵢⴰⵔ, ⵉⵙⵜⵉⵡⵔⵀⵓ ⵉ ⵡⴻⵍⵀⵙⵓⴰⵔ",
      "c'est comme celui qui danse à un aveugle,fait des youyous à un sourd ": "aŷmi iseppeŷ i węlaryar, istiwrhu i węlehsuar , ⴰⵖⵎⵉ ⵉⵙⵒⵒⴰⵖ ⵉ ⵡⴰⵍⴰⵔⵢⴰⵔ, ⵉⵙⵜⵉⵡⵔⵀⵓ ⵉ ⵡⴻⵍⵀⵙⵓⴰⵔ",
      "ⴰⵖⵎⵉ ⵉⵙⵒⵒⴰⵖ ⵉ ⵡⴰⵍⴰⵔⵢⴰⵔ, ⵉⵙⵜⵉⵡⵔⵀⵓ ⵉ ⵡⴻⵍⵀⵙⵓⴰⵔ": "c'est comme celui qui danse à un aveugle,fait des youyous à un sourd , aŷmi iseppeŷ i węlaryar, istiwrhu i węlehsuar",
      "igga yabrid": "il a aménagé une voie ⵉⴳⴳⴰ ⵢⴰⴱⵔⵉⴷ",
      "il a aménagé une voie": "igga yabrid ⵉⴳⴳⴰ ⵢⴰⴱⵔⵉⴷ",
      "ⵉⴳⴳⴰ ⵢⴰⴱⵔⵉⴷ": "il a aménagé une voie igga yabrid",
      "What is Your profession": "mindi itkhadmad quelle est ta profession ⵎⵉⵏⴷⵉ ⵉⵜⵅⴰⴷⵎⴰⴷ",
    "mindi itkhadmad": "What is Your profession quelle est ta profession ⵎⵉⵏⴷⵉ ⵉⵜⵅⴰⴷⵎⴰⴷ",
    "quelle est ta profession": "mindi itkhadmad What is Your profession ⵎⵉⵏⴷⵉ ⵉⵜⵅⴰⴷⵎⴰⴷ",
    "ⵎⵉⵏⴷⵉ ⵉⵜⵅⴰⴷⵎⴰⴷ": "mindi itkhadmad quelle est ta profession What is Your profession",
    "I'm a doctor": "nech dh doctor je suis un docteur ⵏⴰⵛ ⴷ ⴷⵓⴽⵜⵓⵔ",
    "I'm a manager": "nech dh modir je suis un manadeur ⵏⴰⵛ ⴷ ⵎⵓⴷⵉⵔ",
    "I'm a bussines man": "nech dh tajir je suis un marchand ⵏⴰⵛ ⴷ ⵜⴰⵊⵉⵔ",
    "ⴰⵛ ⴷ ⴷⵓⴽⵜⵓⵔ": "nech dh doctor je suis un docteur ⵏI'm a doctor",
    "Please": "3afak ⵄⴰⴼⴰⴽ",
    "ⵄⴰⴼⴰⴽ": "3afak Please",
    "3afak": "ⵄⴰⴼⴰⴽ Please",
    "Good": "Mli7 ⵎⵍⵉⵃ",
    "Mli7": "Good ⵎⵍⵉⵃ",
    "ⵎⵍⵉⵃ": "Good Mli7",
    "Room": "akham ⴰⵅⴰⵎ",
    "ⴰⵅⴰⵎ": "akham Room",
    "akham": "Room ⴰⵅⴰⵎ",
    "Espensive": "Yighra très cher ⵢⵉⵖⵔⴰ",
    "ⵢⵉⵖⵔⴰ": "Yighra très chèr Espensive",
    "très chèr": "Yighra ⵢⵉⵖⵔⴰ Espensive",
    "Yighra": "très chèr ⵢⵉⵖⵔⴰ Espensive",
    "It is Cheap": "Thxas pas cher ⵝⵔⵅⴰⵙ",
    "Thxas": "It is Cheap pas cher ⵝⵔⵅⴰⵙ",
    "pas cher": "It is Cheap Thxas ⵝⵔⵅⴰⵙ",
    "ⵝⵔⵅⴰⵙ": "It is Cheap Thxas pas cher",
    "What do you want to eat?": "Mintazzod Atachadh? que veux tu manger? ⵎⵉⵏ ⵜⴰⵣⵣⵓⴷ ⴰⵜⴰⵛⴷ?",
    "Mintazzod Atachadh?": "What do you want to eat? que veux tu manger? ⵎⵉⵏ ⵜⴰⵣⵣⵓⴷ ⴰⵜⴰⵛⴷ?",
    "que veux tu manger?": "What do you want to eat? intazzod Atachadh? ⵎⵉⵏ ⵜⴰⵣⵣⵓⴷ ⴰⵜⴰⵛⴷ?",
    "ⵎⵉⵏ ⵜⴰⵣⵣⵓⴷ ⴰⵜⴰⵛⴷ?": "What do you want to eat? intazzod Atachadh? que veux tu manger?",
    "I like": "Azzox je veux ⴰⵣⵓⵅ",
    "Azzox": "I like je veux ⴰⵣⵓⵅ",
    "je veux": "Azzox I like ⴰⵣⵓⵅ",
    "ⴰⵣⵓⵅ": "Azzox je veux I like",
    "Cheese": "D'han fromage ⴷⵀⴰⵏ",
    "fromage": "D'han Cheese ⴷⵀⴰⵏ",
    "ⴷⵀⴰⵏ": "D'han Cheese fromage",
    "D'han": "Cheese fromage ⴷⵀⴰⵏ",
    "Fruits": "Rxodath ⵔⵅⵓⴷⴰⵝ",
    "Rxodath": "Fruits ⵔⵅⵓⴷⴰⵝ",
    "ⵔⵅⵓⴷⴰⵝ": "Rxodath Fruits",
    "Potatos": "Batata ⴱⴰⵟⴰⵟⴰ",
    "Batata": "Potatos ⴱⴰⵟⴰⵟⴰ",
    "ⴱⴰⵟⴰⵟⴰ": "Potatos Batata",
    "les frites": "Frita ⴼⵔⵉⵟⴰ",
    "Frita": "les frites ⴼⵔⵉⵟⴰ",
    "ⴼⵔⵉⵟⴰ": "les frites Frita",
    "Grapes": "Adhir ⴰⴹⵉⵔ",
    "Adhir": "Grapes ⴰⴹⵉⵔ",
    "ⴰⴹⵉⵔ": "Grapes Adhir",
      "bedd": "stop ⴱⴰⴷⴷ",
      "stop": "bedd ⴱⴰⴷⴷ",
      "ⴱⴰⴷⴷ": "bedd stop",
      "zembu": "mets à base d'orge grillé ⵣⴰⵎⴱⵓ",
      "ⵣⴰⵎⴱⵓ": "mets à base d'orge grillé zembu",
      "tfawf n waXam": "la lumière de la maison 'épouse' ⵜⴼⴰⵡⵜ ⵏ ⵡⴰⵅⴰⵎ 'ⵜⴰⵙⵔⵉⵜ'",
      "ⵜⴼⴰⵡⵜ ⵏ ⵡⴰⵅⴰⵎ 'ⵜⴰⵙⵔⵉⵜ'": "la lumière de la maison 'épouse'tfawf n waXam'",
      "la lumière de la maison 'épouse'": "ⵜⴼⴰⵡⵜ ⵏ ⵡⴰⵅⴰⵎ 'ⵜⴰⵙⵔⵉⵜ'tfawf n waXam'",
      "tassrit n wanzar": "fiancée de la pluie 'arc-en-ciel' ⵜⴰⵙⵔⵉⵜ ⵏ ⵡⴰⵏⵣⴰⵔ",
      "arc-en-ciel": "tassrit n wanzar ⵜⴰⵙⵔⵉⵜ ⵏ ⵡⴰⵏⵣⴰⵔ",
      "ⵜⴰⵙⵔⵉⵜ ⵏ ⵡⴰⵏⵣⴰⵔ": "fiancée de la pluie 'arc-en-ciel 'tassrit n wanzar",
      "What kind of music You prefere?": "Mani music idam ita3jiben?,quelle music aimes-tu?,ⵎⴰⵏⵉ ⵎⵓⵙⵉⵇⴰ ⵉⴷⴰⵎ ⵉⵜⵄⵊⴱⴰⵏ?",
      "ⵎⴰⵏⵉ ⵎⵓⵙⵉⵇⴰ ⵉⴷⴰⵎ ⵉⵜⵄⵊⴱⴰⵏ?": "Mani music idam ita3jiben?,quelle music aimes-tu?,What kind of music You prefere?",
      "Mani music idam ita3jiben?": "What kind of music You prefere?,quelle music aimes-tu?,ⵎⴰⵏⵉ ⵎⵓⵙⵉⵇⴰ ⵉⴷⴰⵎ ⵉⵜⵄⵊⴱⴰⵏ?",
      "quelle music aimes-tu?": "Mani music idam ita3jiben?,What kind of music You prefere?,ⵎⴰⵏⵉ ⵎⵓⵙⵉⵇⴰ ⵉⴷⴰⵎ ⵉⵜⵄⵊⴱⴰⵏ?",
      "I like izran & Rai music": "ita3jibayi music narif ak rai,j'aime la music rif & rai,ⵉⵜⵄⵊⴱⴰⵢⵉ ⵉⵣⵔⴰⵏ ⴰⴽ ⵔⴰⵢ ⵎⵓⵙⵉⵇⴰ",
      "ita3jibayi music narif ak rai": "I like izran & Rai music,j'aime la music rif & rai,ⵉⵜⵄⵊⴱⴰⵢⵉ ⵉⵣⵔⴰⵏ ⴰⴽ ⵔⴰⵢ ⵎⵓⵙⵉⵇⴰ",
      "j'aime la music rif & rai": "ita3jibayi music narif ak rai,I like izran & Rai music,ⵉⵜⵄⵊⴱⴰⵢⵉ ⵉⵣⵔⴰⵏ ⴰⴽ ⵔⴰⵢ ⵎⵓⵙⵉⵇⴰ",
      "ⵉⵜⵄⵊⴱⴰⵢⵉ ⵉⵣⵔⴰⵏ ⴰⴽ ⵔⴰⵢ ⵎⵓⵙⵉⵇⴰ": "ita3jibayi music narif ak rai,j'aime la music rif & rai,I like izran & Rai music",
      "bedd":"stop ⴱⴰⴷⴷ",
"stop": "bedd ⴱⴰⴷⴷ",
"ⴱⴰⴷⴷ": "bedd stop",
"zembu":"mets à base d'orge grillé ⵣⴰⵎⴱⵓ",
"ⵣⴰⵎⴱⵓ":"mets à base d'orge grillé zembu",
"tassrit n wanzar": "fiancée de la pluie 'arc-en-ciel' ⵜⴰⵙⵔⵉⵜ ⵏ ⵡⴰⵏⵣⴰⵔ",
"fiancée de la pluie 'arc-en-ciel'": "tassrit n wanzar ⵜⴰⵙⵔⵉⵜ ⵏ ⵡⴰⵏⵣⴰⵔ",
"ⵜⴰⵙⵔⵉⵜ ⵏ ⵡⴰⵏⵣⴰⵔ": "fiancée de la pluie 'arc-en-ciel 'tassrit n wanzar",
"Ralla yemma":"ma chére maman ⵔⴰⵍⵍⴰ ⵢⴰⵎⵎⴰ",
"ⵔⴰⵍⵍⴰ ⵢⴰⵎⵎⴰ":"ma chérre aman Ralla yemma",
"ma chére maman":"Ralla yemma ⵔⴰⵍⵍⴰ ⵢⴰⵎⵎⴰ",
  "qqim": "Assieds-toi ! Sit down! ⵇⵉⵎ",
  "Assieds-toi !": "qqim ! Sit down! ⵇⵉⵎ",
  "ⵇⵉⵎ": "Assieds-toi ! Sit down! qqim",
  "timura": "pays country ⵜⵉⵎⵓⵔⴰ",
  "pays": "timura country ⵜⵉⵎⵓⵔⴰ",
  "ⵜⵉⵎⵓⵔⴰ": "pays country timura",
  "tammurt": "terre land ⵜⴰⵎⵓⵔⵜ",
  "terre": "tammurt land ⵜⴰⵎⵓⵔⵜ",
  "ⵜⴰⵎⵓⵔⵜ": "terre land tammurt",
  "timira": "barbes beards ⵜⵉⵎⵉⵔⴰ",
  "barbes": "ⵜⵉⵎⵉⵔⴰ timira beards",
  "ⵜⵉⵎⵉⵔⴰ": "barbes beards timira",
  "yabyutat": "mouettes seagulls ⵢⴰⴱⵢⵓⵜⴰⵜ",
  "mouettes": "yabyutat seagulls ⵢⴰⴱⵢⵓⵜⴰⵜ",
  "ⵢⴰⴱⵢⵓⵜⴰⵜ": "mouettes seagulls yabyutat",
  "mmi": "mon fils my son ⵎⵎⵉ",
  "mon fils": "mmi my son ⵎⵎⵉ",
  "ⵎⵎⵉ": "mon fils my son mmi",
  "utchma-s n Fatima": "sa sœur à Fatima his sister Fatima's ⵓⵞⵎⴰⵙ ⵏ ⴼⴰⵟⵉⵎⴰ",
  "ⵓⵞⵎⴰⵙ ⵏ ⴼⴰⵟⵉⵎⴰ": "sa sœur à Fatima his sister Fatima's utchma-s n Fatima",
  "sa sœur à Fatima": "utchma-s n Fatima his sister Fatima's ⵓⵞⵎⴰⵙ ⵏ ⴼⴰⵟⵉⵎⴰ",
  "djeddi-s n Mohamed": "son grand-père à Mohamed his grandfather Mohamed's ⴶⴰⴷⵉⵙ ⵏ ⵎⵓⵃⴰⵎⴰⴷ",
  "son grand-père à Mohamed": "djeddi-s n Mohamed his grandfather Mohamed's ⴶⴰⴷⵉⵙ ⵏ ⵎⵓⵃⴰⵎⴰⴷ",
  "ⴶⴰⴷⵉⵙ ⵏ ⵎⵓⵃⴰⵎⴰⴷ": "son grand-père à Mohamed his grandfather Mohamed's djeddi-s n Mohamed",
  "fad": "soif thirst ⴼⴰⴷ",
  "soif": "fad thirst ⴼⴰⴷ",
  "ⴼⴰⴷ": "soif thirst fad",
  "temzi": "jeunesse youth ⵜⵎⵣⵉ",
  "jeunesse": "temzi youth ⵜⵎⵣⵉ",
  "ⵜⵎⵣⵉ": "jeunesse youth temzi",
  "macha": "nourriture food ⵎⴰⵛⵛⴰ",
  "nourriture": "macha food ⵎⴰⵛⵛⴰ",
  "ⵎⴰⵛⵛⴰ": "nourriture food macha",
  "ameqqran": "grand big/large ⴰⵎⵇⵔⴰⵏ",
  "grand": "ameqqran big/large ⴰⵎⵇⵔⴰⵏ",
  "ⴰⵎⵇⵔⴰⵏ": "grand big/large ameqqran",
  "azru": "les cailloux stones ⴰⵥⵔⵓ",
  "ⴰⵥⵔⵓ": "les cailloux stones azru",
  "les cailloux": "azru stones ⴰⵥⵔⵓ",
  "tazrut": "la roche the rock ⵜⴰⵥⵔⵓⵜ",
  "ⵜⴰⵥⵔⵓⵜ": "tazrut the rock ⵜⴰⵥⵔⵓⵜ",
  "la roche": "tazrut the rock ⵜⴰⵥⵔⵓⵜ",
  "pabu": "dinde turkey ⵒabu",
  "ⵒabu": "dinde turkey pabu",
  "dinde": "pabu turkey ⵒabu",
  "t7anet": "boutique shop ⵝⵃⴰⵏⵓⵜ",
  "ⵝⵃⴰⵏⵓⵜ": "boutique shop t7anet",
  "boutique": "t7anet shop ⵝⵃⴰⵏⵓⵜ",
  "ṭamza": "ogresse ogress ⵝⴰⵎⵥⴰ",
  "adĭid": "oiseau bird ⴰⴶⵉⴹ",
  "oiseau": "adĭid bird ⴰⴶⵉⴹ",
  "ⴰⴶⵉⴹ": "oiseau bird adĭid",
  "vache": "tafunast cow ⵜⴰⴼⵓⵏⴰⵙⵜ",
  "homme": "aryaz man ⴰⵔⵢⴰⵣ",
  "aryaz": "aryaz man ⴰⵔⵢⴰⵣ",
  "ⴰⵔⵢⴰⵣ": "aryaz man ⴰⵔⵢⴰⵣ",
  "femme": "tamghart woman ⵝⴰⵎⵖⴰⵔⵝ",
  "tamghart": "femme woman ⵝⴰⵎⵖⴰⵔⵝ",
  "ⵝⴰⵎⵖⴰⵔⵝ": "tamghart woman femme",
  "bouc": "amyan billy goat ⴰⵎⵢⴰⵏ",
  "amyan": "bouc billy goat ⴰⵎⵢⴰⵏ",
  "ⴰⵎⵢⴰⵏ": "amyan billy goat bouc",
  "isari": "bélier ram ⵉⵙⴰⵔⵉ",
  "bélier": "isari ram ⵉⵙⴰⵔⵉ",
  "ⵉⵙⴰⵔⵉ": "bélier ram isari",
  "tikhsi": "brebis ewe ⵜⵉⵅⵙⵉ",
  "brebis": "tikhsi ewe ⵜⵉⵅⵙⵉ",
  "ⵜⵉⵅⵙⵉ": "brebis ewe tikhsi",
  "yis": "cheval horse ⵢⵉⵙ",
  "cheval": "yis horse ⵢⵉⵙ",
  "ⵢⵉⵙ": "cheval horse yis",
  "titt": "œil eye ⵜⵉⵟ",
  "ⵜⵉⵟ": "œil eye titt",
  "œil": "titt eye ⵜⵉⵟ",
  "attaw": "grand œil big eye ⴰⵟⴰⵡ",
  "grand œil": "attaw big eye ⴰⵟⴰⵡ",
  "ⴰⵟⴰⵡ": "grand œil big eye attaw",
  "Fus": "main hand ⴼⵓⵙ",
  "main": "Fus hand ⴼⵓⵙ",
  "ⴼⵓⵙ": "main hand Fus",
  "taghenadjachth": "cuillère spoon ⵜⴰⵖⵏⴶⴰⵛⵝ",
  "ⵜⴰⵖⵏⴶⴰⵛⵝ": "cuillère spoon taghenadjachth",
  "cuillère": "taghenadjachth spoon ⵜⴰⵖⵏⴶⴰⵛⵝ",
  "taqbucht": "jarre à eau water jar ⵝⴰⵇⴱⵓⵛⵜ",
  "jarre à eau": "taqbucht water jar ⵝⴰⵇⴱⵓⵛⵜ",
  "ⵝⴰⵇⴱⵓⵛⵜ": "jarre à eau water jar taqbucht",
  "yechur-it s waman": "il’a rempli avec de l’eau he filled it with water ⵢⵓⵛⵛⵓⵔ ⵉⵜ ⵙⵡⴰⵎⴰⵏ",
  "ⵢⵓⵛⵛⵓⵔ ⵉⵜ ⵙⵡⴰⵎⴰⵏ": "il’a rempli avec de l’eau he filled it with water yechur-it s waman",
  "il’a rempli avec de l’eau": "ⵢⵓⵛⵛⵓⵔ ⵉⵜ ⵙⵡⴰⵎⴰⵏ he filled it with water ⵢⴻⵛⵛⵓⵔ ⵉⵜ ⵙⵡⴰⵎⴰⵏ",
  "bonjour,salut": "mere7ba, chokran u chek ? hello, hi ⵎⴰⵔⵃⴱⴰ ⵛⵓⴽⵔⴰⵏ ⵓ ⵛⴻⴽ",
  "merci beaucoup": "ssa7it thank you very much ⵚⴰⵃⵉⵝ",
  "merci infiniment": "Achye7fed rebi thank you infinitely ⴰⵛⵢⵃⴼⴰⴹ ⵔⴰⴱⵉ",
  "ⴰⵛⵢⵃⴼⴰⴹ ⵔⴰⴱⵉ": "Achye7fed rebi thank you infinitely merci infiniment",
  "Achye7fed rebi": "ⴰⵛⵢⵃⴼⴰⴹ ⵔⴰⴱⵉ thank you infinitely merci infiniment",
  "au revoir adieu": "besselama goodbye ⴱⵉⵙⵍⴰⵎⴰ",
  "le numéro téléphone": "numru tilifone phone number ⵏⵓⵎⵔⵓ ⵜⵉⵍⵉⴼⵓⵏ",
  "un sachet de plastique": "Mika plastik plastic bag ⵎⵉⴽⴰ ⴷ ⵒⵍⴰⵙⵜⵉⴽ",
  "les saucisse grillées": "susiit mechwi grilled sausages ⵚⵓⵚⵉⵟ ⵎⵛⵓⵉ",
  "le lavabo de cuisine": "llababu d anwal kitchen sink ⵍⴰⴱⴰⴱⵓ ⴷⴰⵏⵓⴰⵍ",
  "l'adresse de la maison": "landris d tadart, home address ⵍⴰⵏⴷⵔⵉⵙ ⴷ ⵜⴰⴷⴰⵔⵝ",
  "la famille très importantes": "familya dyis lfayda, very important family ⴼⴰⵎⵉⵍⵢⴰ ⴷⴰⵢⵉⵙ ⴼⴰⵢⴷⴰ",
  "pourquoi tu manges du poissons": "purki atchet iserman, why are you eating fish? ⵒⵓⵔⴽⵉ ⴰⵜⵛⵝ ⵉⵙⵔⵎⴰⵏ",
  "le coco est tres bon": "kuku dasb7an, the coconut is very good ⴽⵓⴽⵓ ⴷⴰⵙⴱⵃⴰⵏ !",
  "zéro est un nombre": "ziru Raqem, zero is a number ⵣⵉⵔⵓ ⵔⴰⵇⴰⵎ",
  "le monde est grand": "ddənya tamqrante, the world is big ⴷⴻⵏⵢⴰ ⵝⴰⵎⵇⵔⴰⵏⵝ",
  "le combat est féroce": "ta3əjjacht tamjhedth, the fight is fierce ⵟⴰⵄⵊⵊⴰⵛⵟ ⵜⴰⵎⵊⴻⵀⴷⵝ",
  "la mer rouge": "reb7ar azogagh, the red sea ⵔⴰⴱⵃⴰ ⴰⵣⵓⴳⴰⵖ",
  "les vagues de la mer": "rmujjet d reb7ar, the waves of the sea ⵔⵎⵓⵊⵊⴻⵝ ⴷ ⵔⴰⴱⵃⴰⵔ",
  "ⵜⵓⵄⴰⵔ ⵢⴻⵎⴰⵛ ⵎⵛⵃⴰⵔ ⵜⵓⵄⴰⵔ": "tu3ar yemach mche7ar tu3ar, your mother is very strict",
  "ta mère est très sévère": "tu3ar yemach mche7ar tu3ar, your mother is very strict ⵜⵓⵄⴰⵔ ⵢⴻⵎⴰⵛ ⵎⵛⵃⴰⵔ ⵜⵓⵄⴰⵔ",
  "tu3ar yemach mche7ar tu3ar": "ⵜⵓⵄⴰⵔ ⵢⴻⵎⴰⵛ ⵎⵛⵃⴰⵔ ⵜⵓⵄⴰⵔ, your mother is very strict",
  "ⵜⴰⵔⵉⴼⵛⵜ ⵜⴰⵜⵖⵏⴻⵊ ⵉⵣⵔⴰⵏ": "Riffian women sing beautiful poems, tarifacht teghnajth izran",
  "tarifacht teghnajth izran": "Riffian women sing beautiful poems, ⵜⴰⵔⵉⴼⵛⵜ ⵜⴰⵜⵖⵏⴻⵊ ⵉⵣⵔⴰⵏ",
  "les femmes riffaines chantent de beaux poèmes": "tarifacht teghnajth izran, Riffian women sing beautiful poems ⵜⴰⵔⵉⴼⵛⵜ ⵜⴰⵜⵖⵏⴻⵊ ⵉⵣⵔⴰⵏ",
  "lmoustaqbal negh": "pour notre avenir for our future ⵅ ⵍⵎⵓⵙⵜⵇⴱⴰⵍ ⵏⴰⵖ",
  "pour notre avenir": "lmoustaqbal negh for our future ⵅ ⵍⵎⵓⵙⵜⵇⴱⴰⵍ ⵏⴰⵖ",
  "ⵍⵎⵓⵙⵜⵇⴱⴰⵍ ⵏⴰⵖ": "pour notre avenir for our future lmoustaqbal negh",
  "ithran dg ujenna": "les étoiles du ciel the stars in the sky ⵉⵝⵔⴰⵏ ⴷⴳ ⵓⵊⵏⵏⴰ",
 "les étoiles du ciel": "ithran dg ujenna the stars in the sky ⵉⵝⵔⴰⵏ ⴷⴳ ⵓⵊⵏⵏⴰ",
  "ⵉⵝⵔⴰⵏ ⴷⴳ ⵓⵊⵏⵏⴰ": "les étoiles du ciel the stars in the sky, ithran dg ujenna",
  "boire du thé": "swighe atay drink tea ⵙⵓⵉⵖ ⴰⵜⴰⵢ",
  "ⵙⵓⵉⵖ ⴰⵜⴰⵢ": "swighe atay drink tea",
  "swighe atay": "boire du thé drink tea ⵙⵓⵉⵖ ⴰⵜⴰⵢ",
  "rien du tout": "walou walou nothing at all ⵡⴰⵍⵓ ⵡⴰⵍⵓ",
  "walou walou": "rien du tout nothing at all ⵡⴰⵍⵓ ⵡⴰⵍⵓ",
  "ⵡⴰⵍⵓ ⵡⴰⵍⵓ": "walou walou nothing at all",
  "ⴽⴰⵙⵙ ⵏ ⵡⴰⵜⴰⵢ": "un verre de thé a glass of tea, kasse nwatay",
  "kasse nwatay": "un verre de thé a glass of tea ⴽⴰⵙⵙ ⵏ ⵡⴰⵜⴰⵢ",
  "un verre de thé": "kasse nwatay a glass of tea ⴽⴰⵙⵙ ⵏ ⵡⴰⵜⴰⵢ",
  "Khessegh titawin nem": "j'aime tes yeux de biche I love your doe eyes ⵅⵙⵖ ⵜⵉⵟⴰⵡⵉⵏ ⵏⴻⵎ",
  "j'aime tes yeux de biche": "Khessegh titawin nem I love your doe eyes ⵅⵙⵖ ⵜⵉⵟⴰⵡⵉⵏ ⵏⴻⵎ",
  "ⵅⵙⵖ ⵜⵉⵟⴰⵡⵉⵏ ⵏⴻⵎ": "j'aime tes yeux de biche I love your doe eyes, Khessegh titawin nem",
  "Dchar ino": "mon village my village ⴷⵛⴰⵔ ⵉⵏⵓ",
  "mon village": "Dchar ino my village ⴷⵛⴰⵔ ⵉⵏⵓ",
  "ⴷⵛⴰⵔ ⵉⵏⵓ": "mon village my village Dchar ino",
  "se mettre en colère": "ch3ch3 get angry ⵛⴰⵄⵛⵄ",
  "le forêt de chaîne": "rghabət rbeloth, the chain forest ⵕⵖⴰⴱⴰⵝ ⵔⴱⴻⵍⵓⵝ",
  "l'arbre de la forêt": "chəjjart d rghaba, the forest tree ⵛⴰⵊⵊⴰⵔⵜ ⴷ ⵔⵖⴰⴱⴰ",
  "le séisme de nador": "zzinzal d'anadur, the Nador earthquake ⵥⵉⵏⵣⴰⵍ ⴷ'ⴰⵏⴰⴷⵓⵔ",
  "ⵛⴻⵎ ⴷ ⵍⵃⵓⴱ ⴰⵎⵣⵡⴰⵔ": "you are my first love, chem d l7oub amzewar",
  "tu es mon premier amour": "chem d l7oub amzewar, you are my first love ⵛⴻⵎ ⴷ ⵍⵃⵓⴱ ⴰⵎⵣⵡⴰⵔ",
  "chem d l7oub amzewar": "tu es mon premier amour, you are my first love ⵛⴻⵎ ⴷ ⵍⵃⵓⴱ ⴰⵎⵣⵡⴰⵔ",
  "ⴰⵥⵔ": "Deghya, Act quickly, respond quickly",
  "Azer": "Deghya, Act quickly, respond quickly ⴰⵥⵔ",
  "Deghya": "Deghya, Act quickly, respond quickly ⴷⵖⵢⴰ",
  "tfucht wakham": "3emarte dare, moon of my life ⵜⴼⵓⵛⵜ ⵡⴰⵅⴰⵎ",
  "ⵜⴼⵓⵛⵜ ⵡⴰⵅⴰⵎ": "3emarte dare, moon of my life, tfucht wakham",
  "3emarte dare": "tfucht wakham, moon of my life ⵜⴼⵓⵛⵜ ⵡⴰⵅⴰⵎ",
  "tifayur": "plus belle que la lune more beautiful than the moon ⵜⵉⴼ ⴰⵢⵓⵔ",
  "ogresse": "ṭamza ogress ⵝⴰⵎⵥⴰ",
  "ⵝⴰⵎⵥⴰ": "ogresse ogress ṭamza",
  "tizi": "vallée valley ⵜⵉⵣⵉ",
  "vallée": "tizi valley ⵜⵉⵣⵉ",
  "ⵜⵉⵣⵉ": "vallée valley tizi",
  "karnu": "charrette cart ⴽⴰⵔⵏⵓ",
  "charrette": "karnu cart ⴽⴰⵔⵏⵓ",
  "ⴽⴰⵔⵏⵓ": "charrette cart karnu",
  "anu": "puits well ⴰⵏⵓ",
  "puits": "anu well ⴰⵏⵓ",
  "ⴰⵏⵓ": "puits well anu",
  "uchen": "chacal jackal ⵓⵛⴻⵏ",
  "chacal": "uchen jackal ⵓⵛⴻⵏ",
  "ⵓⵛⴻⵏ": "chacal jackal uchen",
  "afedja7": "agriculteur farmer ⴰⴼⴶⴰⵃ",
  "agriculteur": "afedja7 farmer ⴰⴼⴶⴰⵃ",
  "ⴰⴼⴶⴰⵃ": "agriculteur farmer afedja7",
  "poissons": "isserman fish ⵉⵙⵔⵎⴰⵏ",
  "isserman": "poissons fish ⵉⵙⵔⵎⴰⵏ",
  "ⵉⵙⵔⵎⴰⵏ": "poissons fish isserman",
  "udem": "visage face ⵓⴷⵎ",
  "visage": "udem face ⵓⴷⵎ",
  "ⵓⴷⵎ": "visage face udem",
  "ifis": "hyène hyena ⵉⴼⵉⵙ",
  "hyène": "ifis hyena ⵉⴼⵉⵙ",
  "ⵉⴼⵉⵙ": "hyène hyena ifis",
  "awar": "mot word ⴰⵡⴰⵔ",
  "mot": "awar word ⴰⵡⴰⵔ",
  "ⴰⵡⴰⵔ": "mot word awar",
  "azwagh": "racine root ⴰⵣⵡⴰⵖ",
  "racine": "azwagh root ⴰⵣⵡⴰⵖ",
  "ⴰⵣⵡⴰⵖ": "racine root azwagh",
  "imslemen": "musulmans muslims ⵉⵎⵙⵍⵎⴰⵏ",
  "musulmans": "imslemen muslims ⵉⵎⵙⵍⵎⴰⵏ",
  "ⵉⵎⵙⵍⵎⴰⵏ": "musulmans muslims imslemen",
  "itri": "étoile star ⵉⵝⵔⵉ",
  "étoile": "itri star ⵉⵝⵔⵉ",
  "ⵉⵝⵔⵉ": "étoile star itri",
  "izi": "mouche fly ⵉⵣⵉ",
  "mouche": "izi fly ⵉⵣⵉ",
  "ⵉⵣⵉ": "mouche fly izi",
  "djidj": "cheville ankle ⴶⵉⴶ",
  "ⴶⵉⴶ": "djidj ankle cheville",
  "cheville": "djidj ankle ⴶⵉⴶ",
  "dad": "doigt finger ⴹⴰⴹ",
  "ⴹⴰⴹ": "doigt finger dad",
  "doigt": "dad finger ⴹⴰⴹ",
  "tghaṭṛt": "chèvre goat ⵜⵖⴰⵝⵔⵝ",
  "chèvre": "tghaṭṛt goat ⵜⵖⴰⵝⵔⵝ",
  "ⵜⵖⴰⵝⵔⵝ": "chèvre goat tghaṭṛt",
  "ⵜⵉⴼ ⴰⵢⵓⵔ": "plus belle que la lune more beautiful than the moon,tifayur",
  "plus belle que la lune": "tifayur more beautiful than the moon,ⵜⵉⴼ ⴰⵢⵓⵔ",
  "ⵜⴰⵣⵉⵔⵉ ⵜⴰⵎⵉⵔⵉ": "au clair de la lune by the light of the moon,taziri tamiri",
  "taziri tamiri": "au clair de la lune by the light of the moon,ⵜⴰⵣⵉⵔⵉ ⵜⴰⵎⵉⵔⵉ",
  "au clair de la lune": "ⵜⴰⵣⵉⵔⵉ ⵜⴰⵎⵉⵔⵉ by the light of the moon,taziri tamiri",
  "vendre": "watzenouzegh sell, ⵡⴰⵜⵣⵏⵏⵓⵣⵖ",
  "ⵡⴰⵜⵣⵏⵏⵓⵣⵖ": "watzenouzegh sell, vendre",
  "watzenouzegh": "ⵡⴰⵜⵣⵏⵏⵓⵣⵖ sell, vendre",
  "ayourinou": "ma chérie my darling, ⴰⵢⵓⵔⵉⵏⵓ",
  "ma chérie": "ayourinou my darling, ⴰⵢⵓⵔⵉⵏⵓ",
  "ⴰⵢⵓⵔⵉⵏⵓ": "ayourinou my darling, ma chérie",
  "la rose du matin": "nnda morning rose, ⵏⵏⴷⴰ",
  "le vent glacial": "Assemid icy wind, ⴰⵚⵎⵉⴹ",
  "l'état semble mieux": "r7ar mzian the condition seems better, ⵕⵃⴰⵕ ⵎⴻⵣⵉⴰⵏ",
  "la fumée s'évapore": "dekhan tittl3 the smoke evaporates, ⵕⵃⴰⵕ ⵜⵉⵟⵍⵄ",
  "brûler le pain": "aghrum i7ār burn the bread, ⴰⵖⵔⵓⵎ ⵉⵃⴰⵔ",
  "allumer la bougie": "ch3er tacheme3 light the candle, ⵛⵄⵔ ⵝⴰⵛⵎⴰⵄⵝ",
  "compréhension de langue": "refħemgh n tutalayt language understanding, ⵕⴼⵃⵎⵖ ⵏ ⵝⵓⵜⴰⵍⴰⵢⵜ",
  "mariage et 7énnée": "mrach u r7enna wedding and honeymoon, ⵎⵕⴰⵛ ⵓ ⵔⵃⵏⵏⴰ",
  "papa et maman": "baba d yemma dad and mom, ⴱⴰⴱⴰ ⴷ ⵢⴻⵎⵎⴰ",
  "oncle maternel et oncle": "khari d 3zizi maternal uncle and uncle, ⵅⴰⵕⵉ ⴷ ⵄⵣⵉⵣⵉ",
  "tante maternelle et tante": "khatchi d 3enti maternal aunt and aunt, ⵅⴰⵞⵉ ⴷ ⵄⴰⵏⵜⵉ",
  "madame et monsieur": "Ralla d sidi madam and sir, ⵔⴰⵍⵍⴰ ⴷ ⵙⵉⴷⵉ",
  "beau fils et belle fille": "ārbib u tārbibt handsome son and beautiful daughter, ⵔⴱⵉⴱ ⵓ ⵝⴰⵔⴱⵉⵝ",
  "billets d'argent": "rmar wela temenyat money bills, ⵕⵎⴰⵕ ⵓⵍⴰ ⵝⵎⴰⵏⵢⴰⵝ",
  "comment ça va": "hmdlah, chokran u chek ! how are you?",
  "aide": "Je peux vous aider avec les questions générales. I can help you with general questions.",
  "au revoir": "besselama goodbye, ⴱⵉⵙⵍⴰⵎⴰ",
  "numéro": "numru number, ⵏⵉⵎⵔⵓ",
  "biens": "mziane goods/property, ⵎⵣⵉⴰⵏⴻ",
  "plastique": "plastik plastic, ⵒⵍⴰⵙⵜⵉⴽ",
  "saucisse": "susiit sausage, ⵚⵓⵚⵉⵟ",
  "carte postale": "kartpustal postcard, ⴽⴰⵔⵜⵒⵓⵙⵜⴰⵍ",
  "lavabo": "llababu sink, ⵍⴰⴱⴰⴱⵓ",
  "adresse": "landris address, ⵍⴰⵏⴷⵔⵉⵙ",
  "famille": "familya family, ⴼⴰⵎⵉⵍⵢⴰ",
  "pintar": "pintā paint, ⵒⵉⵏⵜⴰ",
  "lápiz": "lappis pencil, ⵍⴰⵒⵉⵙ",
  "irar ⵉⵔⴰⵔ": "jeux games",
  "ⵔⴰⵍⴰ ⴱⵓⵢⴰ": "ralla buya traditional Riffian song",
  "ralla buya": "ⵔⴰⵍⴰ ⴱⵓⵢⴰ traditional Riffian song",
  "pourquoi": "purki why, ⵒⵓⵔⴽⵉ",
  "je cherche du travail": "seqsigh kh takhdemith I'm looking for work, ⵙⵇⵙⵉⵖ ⵅ ⵜⴰⵅⴷⵎⵉⵝ",
  "seqsigh kh takhdemith": "I'm looking for work je cherche du travail, ⵙⵇⵙⵉⵖ ⵅ ⵜⴰⵅⴷⵎⵉⵝ",
  "ⵙⵇⵙⵉⵖ ⵅ ⵜⴰⵅⴷⵎⵉⵝ": "seqsigh kh takhdemith I'm looking for work",
  "coco": "kuku coconut, ⴽⵓⴽⵓ",
  "zéro": "ziru zero, ⵣⵉⵔⵓ",
  "canguro": "kangaru kangaroo, ⴽⴰⵏⴳⴰⵔⵓ",
  "monde": "ddənya world, ⴷⴻⵏⵢⴰ",
  "combat": "ta3əjjacht fight, ⵟⴰⵄⵊⵊⴰⵛⵟ",
  "la mer": "rəbħā sea ⵔⴰⴱⵃⴰ",
  "hwər": "hul water ⵀⵓⵍ",
  "les vagues": "rmujjət waves ⵔⵎⵓⵊⵊⴻⵝ",
  "chāchā": "chər7chər7 gossip ⵛⵔⵃⵛⵔⵃ",
  "la forêt": "rghabət forest ⵕⵖⴰⴱⴰⵟ",
  "arbre": "ssəjjāt tree ⵙⴰⵊⵊⴰⵟ",
  "seisme": "zzinzal earthquake ⵥⵉⵏⵣⴰⵍ",
  "t7t7ram": "d7ləm darkness ⴷⵃⵍⴻⵎ",
  "la rose": "nnda rose ⵏⵏⴸⴰ",
  "le vent": "lhawa wind ⵍⵃⴰⵡⴰ",
  "l'etat physique": "rħar physical state ⵕⵀⴰⵕ",
  "la fumée": "ddəkhkhan smoke ⴷⴻⵅⴰⵏ",
  "brûler": "7ārq burn ⵃⴰⵔⵇ",
  "allumer": "chch3ər light up ⵛⴻⵛⵄⵔ",
  "la comprehension": "rəfħəm understanding ⵕⴻⴼⵃⵎ",
  "être humain": "bnadəm human being ⴱⵏⴰⴸⵎ",
  "mariage": "mrəch marriage ⵎⵕⴰⵛ",
  "papa": "baba dad ⴱⴰⴱⴰ",
  "maman": "yəmma mom ⵢⴻⵎⵎⴰ",
  "les parents": "lwalidin parents ⵍⵓⴰⵍⵉⴷⵉⵏ",
  "grand père": "jəddi grandfather ⵊⴰⴷⴷⵉ",
  "grand mère": "ħənna grandmother ⵃⴰⵏⵏⴰ",
  "oncle maternel": "khari maternal uncle ⵅⴰⵕⵉ",
  "oncle": "3zizi uncle ⵄⵣⵉⵣⵉ",
  "tante maternelle": "khači maternal aunt ⵅⴰⵞⵉ",
  "tante": "3ənti aunt ⵄⴰⵏⵜⵉ",
  "madame": "Ralla madam ⵔⴰⵍⵍⴰ",
  "beau fils": "ābib handsome son ⵔⴱⵉⴱ",
  "belle fille": "tābift beautiful daughter ⵟⴰⵔⴱⵉⵟ",
  "predixe": "tajjach prefix ⵜⴰⵊⵊⴰⵛ",
  "predix": "ajjar prefix ⴰⵊⵊⴰⵕ",
  "les billets d'argent": "rmar money bills ⵕⵎⴰⵕ",
  "écurie": "rkuri stable ⵕⴽⵓⵔⵉ",
  "le veau": "a3əjmi calf ⴰⵄⴻⵊⵎⵉ",
  "le mouton": "aħuri sheep ⴰⵃⵓⵔⵉ",
  "akidā": "kid7ar green ⴽⵉⴷⵃⴰⵔ",
  "les fêtards": "afā7an partygoers ⴰⴼⴰⵃⴰⵏ",
  "les biens": "abākiw goods ⴰⴱⴰⴽⵉⵡ",
  "faucon": "rbaz falcon ⵕⴱⴰⵣ",
  "rwəd7wad7": "wət7wat7 butterfly ⵡⴻⵜⵃⵡⴰⵜⵃ",
  "perroquet": "babaghayyu parrot ⴱⴰⴱⴰⵖⴰⵢⵓ",
  "hibou": "muka owl ⵎⵓⴽⴰ",
  "requin": "rqirch shark ⵔⵇⵉⵔⵛ",
  "le foulard": "akhmār scarf ⴰⵅⵎⴰⵔ",
  "Moustiques": "nnamus mosquitoes ⵏⵏⴰⵎⵓⵙ",
  "escargots": "buchchər snails ⴱⵓⵛⴻⵛⴰⵔ",
  "le son de la grenouille": "tqāqra frog sound ⵟⵇⴰⵇⵔⴰ",
  "chch3ā": "ch3ər7 shine ⵛⵄⴻⵔⵃ",
  "éplucher les fèves": "aqchua peel beans ⴰⵇⵛⵓⴰ",
  "rayonnantes": "tanəwwāt radiant ⵝⴰⵏⵓⵡⴰⵝ",
    "griffer,scratch": "akhbuch ⴰⵅⴱⵓⵛ",
    "travailleur,worker": "akhəddam ⴰⵅⴷⴰⵎ",
    "plisser les yeux d'un mauvais regard,squint with a bad look": "akhənza ⴰⵅⴻⵏⵣⴰ",
    "tailleur,tailor": "akhəyyad ⴰⵅⴻⵢⴰⴹ",
    "bon prix,good price": "ārkhu ⵔⴰⵅⵓ",
    "une tente,a tent": "akham ⴰⵅⵅⴰⵎ",
    "voisin,neighbor": "ajjār ⴰⵊⵊⴰⵔ",
    "militaire,military": "a3əskari ⴰⵄⴰⵙⴽⴰⵔⵉ",
    "gardien de nuit,night guard": "a3əssas ⴰⵄⴻⵙⵙⴰⵙ",
    "le bouc,the billy goat": "a3ətrus ⴰⵄⴻⵜⵔⵓⵙ",
    "bicyclette,bicycle": "bachklit ⴱⴰⵛⴽⵍⵉⵜ",
    "les toilettes,the toilet": "bitəlma ⴱⵉⵜⴻⵍⵎⴰ",
    "Dehors,outside": "barra ⴱⴰⵕⵕⴰ",
    "hier,yesterday": "barrə7 ⴱⴰⵔⵔⴻⵃ",
    "parler à haute voix,speak loudly": "barra7 ⴱⴰⵔⵔⴰⵃ",
    "commencer à,start to": "bda ⴱⴷⴰ",
    "changer de,change": "bəddər ⴱⴻⴷⴻⵔ",
    "délicieux plat,delicious dish": "bna ⴱⵏⴰ",
    "bullôt,balloon": "bulun ⴱⵓⵍⵓⵏ",
    "serpent,snake": "busəkka ⴱⵓⵙⴻⴽⴰ",
    "Emuler":"Ɛaned,ⵄⴰⵏⴷ (ⵄⴰⵏⴸ)",
  "Médire":"ƐeYeb,ⵄⵢⴻⴱ",
  "Mettre Au Courant":"Ɛrem,ⵄⵔⵎ",
  "Se Tenir (marché)":"Ɛmaṛ,ⵄⵎⴰⵕ",
  "Être Tortueux":"ƐaṚeq,ⵄⴰⵕⵇ",
  "attendre":"Ɛayn,ⵄⴰⵢⵏ",
  "Être Hantée (maison)":"Ɛmaṛ,ⵄⵎⴰⵕ",
  "se Marier":"Ɛmaṛ,ⵄⵎⴰⵕ",
  "Fréquenter":"Ɛachar,ⵄⴰⵛⴰⵔ",
  "Aller Vers Quelqu’un":"ƐaReḍ,ⵄⴰⵔⴹ",
  "Inviter":"Ɛarḍ,ⵄⴰⵔⴹ (ⵄⴰⵔⴺ)",
  "Répéter":"Ɛawd,ⵄⴰⵡⴷ (ⵄⴰⵡⴸ)",
  "Contrarier":"ƐeKes,ⵄⴽⵙ",
  "surveiller":"ƐeS,ⵄⵙ",
  "Plaire":"Ɛjeb,ⵄⵊⴱ",
  "Se Nourrir":"Ɛteq,ⵄⵜⵇ",
  "Être Chéri":"ƐiZ,ⵄⵉⵣ",
  "Séparer":"Ɛzer,ⵄⵣⵔ",
  "Aider":"Ɛawn,ⵄⴰⵡⵏ",
  "Se Laver / Se Baigner":"ƐuM,ⵄⵓⵎ",
  "Se Blesser":"Yzem,ⵢⵣⵎ",
  "Jouer À La Trompette":"ẒeMer,ⵥⵎⵔ",
  "ramasser Du Bois":"Zdem,ⵣⴸⵎ",
  "Se Divertir":"Zhu,ⵣⵀⵓ",
  "se Régaler":"ZaRed,ⵣⴰⵔⴷ",
  "Rougir":"Zwegh,ⵣⵡⵖ",
  "S’étendre Pour Se Reposer":"Ẓer,ⵥⵔ",
  "Être / Devenir Misérable":"Zreḍ,ⵣⵔⴹ",
  "Mordre":"Zɛef,ⵣⵄⴼ",
  "secouer":"Zerz,ⵣⵔⵣ",
  "Contraindre / Serrer":"ZeYaṛ,ⵣⵢⴰⵕ",
  "Rendre Visite / Visiter":"Ẓur,ⵥⵓⵔ",
  "Vendre":"Zenz,ⵣⵏⵣ",
  "Pouvoir":"ZeMar,ⵣⵎⴰⵔ",
  "Prier":"Zadj,ⵣⴰⴶ",
  "Jeûner":"ẒuM,ⵥⵓⵎ"

  };

